### PR TITLE
Fixing ModelWeights Import for PySyTFF utils 🐛 

### PR DESCRIPTION
**Pull request by letv3**
## Description
Fixing [#7085](https://github.com/OpenMined/PySyft/issues/7085)

## Affected Dependencies
Nothing required

## How has this been tested?
PySyTFF notebooks from tutorial now should work fine.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by letv3** [comment]
@teo-milea  Hey, created the PR, can you review it? messed up with labels a bit, sorry 😄

**Review by teo-milea — APPROVED** [review]
LGTM! Thank you for your contribution!

**Comment by madhavajay** [comment]
@letv3 thanks, this is great. It looks like you unchecked the the tick box which allows us to make changes to the PR.
image
Are you able to change the permission otherwise you need to merge `dev` in as there were some changes to CI which happened after this PR was opened which will prevent it from passing some tests.

**Comment by letv3** [comment]
The problem is that I dont have this checkbox... 
image

**Pull request closed without merging**
