### PR TITLE
[WIP] Create Calculating Amplification Ratio (Twitter).ipynb

### PR DESCRIPTION
**Pull request by jackbandy**
Created new test notebook to calculate amplificaiton ratio for Twitter project

## Description
Adding in my test notebook folder and making sure I have a handle on the contribution workflow 🙂

## Affected Dependencies
None

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@jackbandy is this notebook good to merge?

**Comment by jackbandy** [comment]
@madhavajay yes I think it's good! I will be expanding it as the project goes on - is that okay with the workflow or should I wait until it's *complete*?

**Comment by madhavajay** [comment]
@jackbandy its fine to stay as a PR if its just a notebook. 😎

**Comment by iamtrask** [comment]
I've downloaded these notebooks and i'm moving them to another repo

**Pull request closed without merging**
