### PR TITLE
First attempt of adding gradual typing

### PR DESCRIPTION
**Pull request by abdulrahmanmazhar**
First attempt of adding gradual typing over the source code, i started by "utils.py" file and welling to continue working from there and making types even better :)

### CODE REVIEW

**Comment by abdulrahmanmazhar** [comment]
Hey @iamtrask, Here is the first attempt at adding gradual typing over the codebase :smile:

**Comment by iamtrask** [comment]
Nicely done @abdulrahmanmazhar!! Taking a look.

**Comment by abdulrahmanmazhar** [comment]
sure and thank you :)

**Comment by iamtrask** [comment]
When I run 

```
python setup.py test
```

on your branch I get the following errors.

```
======================================================================
ERROR: syft (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: syft
Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/atrask/PycharmProjects/PySyft/syft/__init__.py", line 2, in <module>
    from . import core
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/__init__.py", line 3, in <module>
    from . import workers
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/__init__.py", line 3, in <module>
    from .base import BaseWorker
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/base.py", line 8, in <module>
    from .. import utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/utils.py", line 11, in <module>
    from ._types import PYTHON_ENCODE_RETURN_TYPE, CUSTOM_OBJECT_HOOK_RETURN_TYPE, Dict, Any
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/_types.py", line 11, in <module>
    List[Union[Dict[str, str], Dict[str, ...], ..., ...]], ...]]],
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 652, in inner
    return func(*args, **kwds)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 369, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got Ellipsis.


======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/atrask/PycharmProjects/PySyft/test/__init__.py", line 2, in <module>
    from .core import workers_test
  File "/Users/atrask/PycharmProjects/PySyft/test/core/workers_test.py", line 2, in <module>
    import syft as sy
  File "/Users/atrask/PycharmProjects/PySyft/syft/__init__.py", line 2, in <module>
    from . import core
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/__init__.py", line 3, in <module>
    from . import workers
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/__init__.py", line 3, in <module>
    from .base import BaseWorker
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/base.py", line 8, in <module>
    from .. import utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/utils.py", line 11, in <module>
    from ._types import PYTHON_ENCODE_RETURN_TYPE, CUSTOM_OBJECT_HOOK_RETURN_TYPE, Dict, Any
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/_types.py", line 11, in <module>
    List[Union[Dict[str, str], Dict[str, ...], ..., ...]], ...]]],
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 652, in inner
    return func(*args, **kwds)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 369, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got Ellipsis.


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
atrask-macbookpro:PySyft atrask$ 
```

**Comment by abdulrahmanmazhar** [comment]
I will skip the "generics" for now then to design it in a better way later. but I have one concern about "tests" are we using python2 for testing?, for instance using "__future__" functions, because now I get a different error related to tenserflow and I don't know if this is a known issue or just for me?

python setup.py test

test_plus_is_minus_backward_local (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_backward_remote (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_tensor_local (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_tensor_remote (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_variable_local (test.torch_test.TestChainTensor) ... ok
test_plus_is_minus_variable_remote (test.torch_test.TestChainTensor) ... ok
test_gpc_add (test.torch_test.TestGPCTensor) ... ok
test_gpc_unwrapped_add (test.torch_test.TestGPCTensor) ... ok
test_mpc_matmul (test.torch_test.TestMPCTensor) ... ok
test_mpc_mul (test.torch_test.TestMPCTensor) ... ok
test_mpc_mul_3_workers (test.torch_test.TestMPCTensor) ... ok
test_mpc_negation_and_subtraction (test.torch_test.TestMPCTensor) ... ok
test_mpc_scalar_mult (test.torch_test.TestMPCTensor) ... ok
test_mpc_sum (test.torch_test.TestMPCTensor) ... ok
test_share (test.torch_test.TestMPCTensor) ... ok
test___repr__ (test.torch_test.TestTorchTensor) ... ok
test_add_remote_tensor (test.torch_test.TestTorchTensor) ... ok
test_chain_send_get_tensor (test.torch_test.TestTorchTensor) ... ok
test_local_tensor_binary_methods (test.torch_test.TestTorchTensor)
Unit tests for methods mentioned on issue 1385 ... ok
test_local_tensor_iterable_methods (test.torch_test.TestTorchTensor) ... ok
test_local_tensor_tertiary_methods (test.torch_test.TestTorchTensor) ... ok
test_local_tensor_unary_methods (test.torch_test.TestTorchTensor)
Unit tests for methods mentioned on issue 1385 ... ok
test_multiple_pointers_to_same_target (test.torch_test.TestTorchTensor) ... ok
test_remote_tensor_binary_methods (test.torch_test.TestTorchTensor) ... ok
test_remote_tensor_iterable_methods (test.torch_test.TestTorchTensor) ... ok
test_remote_tensor_tertiary_methods (test.torch_test.TestTorchTensor) ... ok
test_remote_tensor_unary_methods (test.torch_test.TestTorchTensor)
Unit tests for methods mentioned on issue 1385 ... ok
test_remote_tensor_unwrapped_addition (test.torch_test.TestTorchTensor) ... ok
test_send_get_tensor (test.torch_test.TestTorchTensor) ... ok
test_set_id (test.torch_test.TestTorchTensor) ... ok
test_encode_decode_json_python (test.torch_test.TestTorchVariable) ... ok
test_federated_learning (test.torch_test.TestTorchVariable) ... ok
test_local_var_binary_methods (test.torch_test.TestTorchVariable)
Unit tests for methods mentioned on issue 1385 ... ok
test_local_var_unary_methods (test.torch_test.TestTorchVariable)
Unit tests for methods mentioned on issue 1385 ... ok
test_operation_with_variable_and_parameter (test.torch_test.TestTorchVariable) ... ok
test_remote_backprop (test.torch_test.TestTorchVariable) ... ok
test_remote_optim_step (test.torch_test.TestTorchVariable) ... ok
test_remote_var_binary_methods (test.torch_test.TestTorchVariable)
Unit tests for methods mentioned on issue 1385 ... ok
test_remote_var_unary_methods (test.torch_test.TestTorchVariable)
Unit tests for methods mentioned on issue 1385 ... ok
test_send_var_with_gradient (test.torch_test.TestTorchVariable) ... ok
test_torch_F_conv2d_on_remote_var (test.torch_test.TestTorchVariable) ... ok
test_torch_F_relu_on_remote_var (test.torch_test.TestTorchVariable) ... ok
test_torch_function_on_remote_var (test.torch_test.TestTorchVariable) ... ok
test_torch_function_with_multiple_input_on_remote_var (test.torch_test.TestTorchVariable) ... ok
test_torch_function_with_multiple_output_on_remote_var (test.torch_test.TestTorchVariable) ... ok
test_torch_nn_conv2d_on_remote_var (test.torch_test.TestTorchVariable) ... ok
test_var_gradient_keeps_id_during_send_ (test.torch_test.TestTorchVariable) ... ok
test_variable_data_attribute_bug (test.torch_test.TestTorchVariable) ... ok
test_floattensor2json2floattensor (test.tensor_serde_test.TestTensorPointerSerde) ... WARNING:root:_LocalTensor sent to itself
ok
test_floattensordata2json2floattensordata (test.tensor_serde_test.TestTensorPointerSerde) ... WARNING:root:_LocalTensor sent to itself
ok
test_localtensor2json2localtensor (test.tensor_serde_test.TestTensorPointerSerde) ... WARNING:root:_LocalTensor sent to itself
ok
test_send_and_get_tensor (test.tensor_serde_test.TestTensorPointerSerde) ... ok
test_tensor2registered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde) ... WARNING:root:Do you really want a pointer pointing to itself? (self.location == self.owner)
ok
test_tensor2unregsitered_pointer2tensor (test.tensor_serde_test.TestTensorPointerSerde) ... ok
test_search_obj (test.core.workers_test.TestBaseWorker) ... WARNING:root:Torch was already hooked... skipping hooking process
ok

======================================================================
ERROR: federated_averaging_optimizer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: federated_averaging_optimizer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "~/PySyft/syft/core/frameworks/tensorflow/federated_averaging_optimizer.py", line 23, in <module>
    from tensorflow.python.framework import constant_op
ModuleNotFoundError: No module named 'tensorflow'


----------------------------------------------------------------------
Ran 56 tests in 0.490s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=56 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=56 errors=1 failures=0>

**Comment by iamtrask** [comment]
Hmmm - i'm still getting these errors

```======================================================================
ERROR: syft (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: syft
Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/atrask/PycharmProjects/PySyft/syft/__init__.py", line 2, in <module>
    from . import core
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/__init__.py", line 3, in <module>
    from . import workers
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/__init__.py", line 3, in <module>
    from .base import BaseWorker
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/base.py", line 8, in <module>
    from .. import utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/utils.py", line 11, in <module>
    from ._types import PYTHON_ENCODE_RETURN_TYPE, CUSTOM_OBJECT_HOOK_RETURN_TYPE, Dict, Any
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/_types.py", line 11, in <module>
    List[Union[Dict[str, str], Dict[str, ...], ..., ...]], ...]]],
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 652, in inner
    return func(*args, **kwds)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 369, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got Ellipsis.


======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/atrask/PycharmProjects/PySyft/test/__init__.py", line 2, in <module>
    from .core import workers_test
  File "/Users/atrask/PycharmProjects/PySyft/test/core/workers_test.py", line 2, in <module>
    import syft as sy
  File "/Users/atrask/PycharmProjects/PySyft/syft/__init__.py", line 2, in <module>
    from . import core
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/__init__.py", line 3, in <module>
    from . import workers
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/__init__.py", line 3, in <module>
    from .base import BaseWorker
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/base.py", line 8, in <module>
    from .. import utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/utils.py", line 11, in <module>
    from ._types import PYTHON_ENCODE_RETURN_TYPE, CUSTOM_OBJECT_HOOK_RETURN_TYPE, Dict, Any
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/_types.py", line 11, in <module>
    List[Union[Dict[str, str], Dict[str, ...], ..., ...]], ...]]],
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 652, in inner
    return func(*args, **kwds)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 1098, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/atrask/anaconda/lib/python3.6/typing.py", line 369, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got Ellipsis.


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
```

**Comment by abdulrahmanmazhar** [comment]
hey @iamtrask can you please check now? you will find the error i was talking about :)

**Comment by iamtrask** [comment]
Unit tests are passing for me! Great work @abdulrahmanmazhar!! This is an excellent start to https://github.com/OpenMined/PySyft/issues/1456

**Comment by alaaboudib** [comment]
Hello, I am new to OpenMined. 

I made an attempt to contribute to this issue, just a few type annotations to syft/workers/virutal.py.

Can I submit a PR?

Thanks

**Pull request merged**
