### PR TITLE
torch 1.7.1

### PR DESCRIPTION
**Pull request by marcalph**
## Description
add support for torch==1.7.1

## How has this been tested?
pytest markers  
- [x] torch
- [x] fast
- [x] slow >> ongoing
- [x] libs

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by marcalph** [comment]
about #5185

**Comment by madhavajay** [comment]
@marcalph The torch tests are failing (they don't run in the pr_tests.yml in CI only on merge).
I ran them on Python 3.8 and Torch 1.7.1 and there are hundreds of ops which have not been updated.
My guess is there are some issues with `scripts/autofix_allowlist_test.py`. The other thing which needs to be done is to confirm that there is no new functionality we need to add.

https://github.com/pytorch/pytorch/releases

I read the notes and diffed both `dir(torch)` and `dir(torch.Tensor)` and they are identical.

If you can fix the script so it generates a working .json file to pass the tests for `1.7.1` that would be greatly appreciated.

**Comment by marcalph** [comment]
i will!

**Comment by marcalph** [comment]
@madhavajay 
I must have done something wrong the first time... Cannot figure out what, so I've restarted with a fresh install just in case. 
The `allowlist_test.json` was missing some "not_available" rules, I've updated it.
Things should be better : 
pytest_torch_mark

About the duet_test that was failing in slow, I'll try something tomorrow.

**Comment by marcalph** [comment]
@madhavajay 
Finally! The **duet_test** was hitting the wrong route... 
Seems a bit late though...

**Comment by madhavajay** [comment]
I updated the compatibility report script and ran it.
It looks like a lot of the time you are just ignoring the tests rather than running them.

This rule on a pretty important op like `dot` is effectively saying that op is not supported on `1.7.1` for any data types so don't test it.


```json
{
  "dot": {
    "profile": "default",
    "data_types": ["common"],
    "tensors": ["tensor1"],
    "not_available": [
      {
        "inputs": [false, true, 0, 1, [0], [1]],
        "lte_version": "1.7.0"
      },
      {
        "data_types": ["bool", "bfloat16"],
        "lte_version": "1.7.0"
      },
      {
        "data_types": ["float16"],
        "lte_version": "1.5.1"
      },
      {
        "data_types": [
          "bool",
          "uint8",
          "int8",
          "int16",
          "int32",
          "int64",
          "float32",
          "float64",
          "float16",
          "bfloat16"
        ],
        "lte_version": "1.7.1",
        "gte_version": "1.7.1"
      }
    ]
  }
}
```

Screen Shot 2021-03-08 at 12 00 08 pm

There are many other examples like this in the compatibility report where 1.7.1 has been set to just ignore the tests.
This isn't really the solution we were looking for.

Also it seems that `pin_memory` is broken?
Screen Shot 2021-03-08 at 12 02 23 pm

**Pull request closed without merging**
