### PR TITLE
Add pointer tensor serialization

### PR DESCRIPTION
**Pull request by LaRiffle**
This aims at solving #1694 #1697, parts of #1695

This is still work in progress.

Simplify should work correctly.

Deserialization is not done yet.

### CODE REVIEW

**Comment by robert-wagner** [comment]
Other than the merge conflicts is this done?
Alternatively, just assign/ping me when you want it reviewed

**Comment by LaRiffle** [comment]
Not yet done, I want to make sure we answer correctly the problem, but we're close I think

**Comment by LaRiffle** [comment]
@robert-wagner relative imports are back, for your greatest pleasure ;)

**Comment by iamtrask** [comment]
I don't have much preference other than it's really nice that sphinx documentation gets automatically generated. Thoughts?

**Pull request merged**
