### PR TITLE
Add torch 1.7.1/#4906

### PR DESCRIPTION
**Pull request by devil-cyber**
Hey, @madhavajay I have created a draft pull request to get the feedback.

### CODE REVIEW

**Comment by madhavajay** [comment]
The lint checker failed, I have pushed a fix.
Please read the section in the CONTRIBUTING.md on code quality: https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md#code-quality

I highly recommend you run the `scripts/pre_commit.sh` before committing and pushing and to install the pre-commit hooks.

Also regarding the allowlist changes:
Those methods are already in 1.7.0.

Screen Shot 2020-12-24 at 12 22 10 pm

Screen Shot 2020-12-24 at 12 22 15 pm

We only want the new 1.7.1 methods since 1.7.0 to be included (if there are any, there might not be), plus any tests to be added in `allowlist_test.json`.

**Comment by devil-cyber** [comment]
ok thanks

**Comment by devil-cyber** [comment]
@madhavajay, as I have seen `torch.imag`, is missing in  1.7.0 so can I add this in 1.7.1
I am asking because I am a little bit confused and how to write the test in allowlist_test.json

**Comment by madhavajay** [comment]
Some ops are simply not added or tested yet across all torch versions, however we can still add any of the new ones for `1.7.1`.

**Pull request closed without merging**
