### PR TITLE
Automatically update Docker Hub using GitHub Actions (on push to master)

### PR DESCRIPTION
**Pull request by linamnt**
Automatically update Docker Hub image at [https://hub.docker.com/r/openmined/pysyft-notebook](https://hub.docker.com/r/openmined/pysyft-notebook) on push to Master (using GitHub Actions).

Addresses https://github.com/OpenMined/PySyft/issues/2528

Requires:
- [ ] DOCKER_LOGIN & DOCKER_PASSWORD need to be added by Project Maintainers as secrets in repo settings

Questions:
- not sure how to explicitly test that this works, so I'm not sure if there is a way and I'm missing that test...
- Python version set to '3.x', is this okay? 
    - In the test workflows, both 3.6 and 3.7 are specifically tested
    - in the publish to pypi, 3.x is used
- Did not include publishing to GitHub Packages as per [the example](https://github.com/arkhn/fhir-pipe/blob/master/.github/workflows/main.yml) listed in https://github.com/OpenMined/PySyft/issues/2528. Do you want this feature?

### CODE REVIEW

**Comment by vvmnnnkv** [comment]
Another way is to connect docker hub with PySyft repo and setup build(s). It will rebuild images automatically on repo update. The build may be faster than in GH Actions because docker hub leverages build cache.
https://docs.docker.com/docker-hub/builds/

**Comment by linamnt** [comment]
On a related note, GH Actions does support caching, which could eventually support Docker caching natively, but it's definitely not there yet in any elegant form, despite being able to maybe wrangle some working solution together with the available actions (see https://github.com/actions/cache/issues/31)

**Comment by karlhigley** [comment]
@linamnt Thanks for your work on this! Finally got it merged, and it looks like there's an issue with the process of building the Docker image on GH. It's failing with the error:
```
Step 8/10 : COPY ./entrypoint.sh /
COPY failed: stat /var/lib/docker/tmp/docker-builder735825847/entrypoint.sh: no such file or directory
##[error]Process completed with exit code 1.
```
Any idea what that's about or how to address it?

**Comment by linamnt** [comment]
Seems we need to pass the entrypoint.sh that goes along with the Dockerfile, but I think it needs to passed as it's not in the current working directory. I can work on it later today if it's not a rush.

**Comment by vvmnnnkv** [comment]
Docker context is pysyft root while `entrypoint.sh` referenced in Dockerfile is located in `docker-images/pysyft-notebook/` folder. Build command can be updated to specify correct context path:
`docker build -t $IMAGE -f docker-images/pysyft-notebook/Dockerfile docker-images/pysyft-notebook`
Alternatively, Dockerfile can be updated to specify `entrypoint.sh` location from pysyft root.

**Comment by karlhigley** [comment]
That sounds reasonable. Happy to merge a fix when you a get a chance to work on it. No rush.

**Comment by linamnt** [comment]
I made another PR here: https://github.com/OpenMined/PySyft/pull/3066 with the solution by @vvmnnnkv

**Comment by karlhigley** [comment]
@linamnt Thanks for the PR! Will merge once the tests pass.

**Pull request merged**
