### PR TITLE
Remove Darglint Warnings(Draft)

### LINKED ISSUE #5148: Fix all darglint docs warnings
## Description
Currently there are 419 warnings:
```
$ flake8 src tests | wc -l
419
```

We can progressively improve this with multiple PRs.
If you are interested, please run the checker on the `src` and `tests` folders and try to fix the warnings until there are none.
Some will require adding docs that don't exist while others are just fixes.

This will likely require multiple PRs so if you are interested open a PR with a few fixes and we will go from there.

## Definition of Done
All docstring warnings are fixed and CI has the darglint checker turned on to fail the build.

### PR DESCRIPTION
**Pull request by avinsit123**
## Description
Partially Addresses #5148 
Do not merge for now.
Fix all darglint warnings for `src/syft/utils.py` 

## Affected Dependencies
Darglint required to run tests
`pip install darglint`

## How has this been tested?
`darglint src tests | grep src/syft/util`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@avinsit123 This takes the number down to `406` but it doesn't close the issue, please update the description so that merging this PR doesn't close the original issue.

**Comment by avinsit123** [comment]
Oh ok sorry. Also should all the warnings be fixed in one PR or multiple PR's

**Comment by madhavajay** [comment]
@avinsit123 I have merged this for now. If you want to correct more open a new PR. 👍🏼

**Comment by avinsit123** [comment]
Thanks @madhavajay

**Pull request merged**
