### PR TITLE
Partition key bug

### PR DESCRIPTION
**Pull request by teo-milea**
## Description
When we try to create two objects that have the same user_verify_key but different other keys, the store will return an error because it will only match that key. I added a quick fix, but it seems the problem is deeper. 

## How has this been tested?
I have added a notebook to replicate the issue under notebooks/bugs

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@kiendang yes im pretty sure this just needs to be moved to `__attr_searchable__` since if it was unique then a user could only upload 1 UserCode object? @teo-milea is that the issue you were having?

**Comment by madhavajay** [comment]
@kiendang yes im pretty sure this just needs to be moved to `__attr_searchable__` since if it was unique then a user could only upload 1 UserCode object? @teo-milea is that the issue you were having?

**Comment by teo-milea** [comment]
@madhavajay yep that was the problem

**Comment by kiendang** [comment]
@teo-milea A change similar to #7399 would fix this.

**Pull request closed without merging**
