### PR TITLE
Added Japanese language translated tutorial notebooks from part 1 to 12

### PR DESCRIPTION
**Pull request by kouohhashi**
I translated tutorial from part 1 to 12 into Japanese.

### CODE REVIEW

**Comment by kouohhashi** [comment]
Is this because of part 10 ?
We can not run part 10 as is.

**Comment by karlhigley** [comment]
You can see the error logs on the “Checks” tab. Looks like an “invalid character in identifier” error and maybe a few other things.

**Comment by kouohhashi** [comment]
Thank you

**Comment by kouohhashi** [comment]
How can I avoid timeout error?
it looks like timeout=300 may not be big enough for Part 06.

**Pull request merged**
