### PR TITLE
Re-Implemented Default diag Functionality for Base Tensor Type with tests

### PR DESCRIPTION
**Pull request by tusharsoni08**
@iamtrask @bharathgs please review my PR.

### CODE REVIEW

**Comment by tusharsoni08** [comment]
@iamtrask @bharathgs please review again this PR.

**Comment by iamtrask** [comment]
@bharathgs thoughts on this one?

**Comment by tusharsoni08** [comment]
@iamtrask @bharathgs please review it.

**Comment by tusharsoni08** [comment]
@bharathgs please review this PR.

**Comment by tusharsoni08** [comment]
@iamtrask please also merge this https://github.com/OpenMined/PySyft/pull/297 PR for that remaining requested change.

**Pull request merged**
