### PR TITLE
Implement default set functionality resolves #93

### LINKED ISSUE #93: Implement Default set Functionality for Base Tensor Type
**User Story A:** As a Data Scientist using Syft's Base Tensor type, I want to leverage a default method for computing operations on a Tensor of arbitrary type. For this ticket to be complete, set_() should operate inline. For a reference on the operation this performs check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation.

**Acceptance Criteria:**
- If the Base Tensor type's attribute "encrypted" is set to True, it should return a NotImplemented error.
- a unit test demonstrating the correct operation on the Base Tensor type implemented over int and float Tensors.
- inline documentation in the python code. For inspiration on inline documentation, please check out [PyTorch](http://pytorch.org/docs/master/tensors.html)'s documentation for this operator.

### PR DESCRIPTION
**Pull request by sp4ke**
Resolves #93 

The methods added on TensorBase are:
- `storage_offset`
- `set_`

### CODE REVIEW

**Comment by sp4ke** [comment]
@bharathgs Can you give me a few hints ? Since PyTorch uses a custom Storage I struggled to understand what was the desired behavior for TensorBase

**Comment by bharathgs** [comment]
@sp4ke  
1. so [this (https://github.com/pytorch/pytorch/blob/9ef39a50ee16d4944240ac5cfa6489e3dd294c5f/torch/csrc/generic/methods/Tensor.cwrap#L194) and [this](https://apaszke.github.io/torch-internals.html) might be of interest to you. 

2. so with the current code I noticed that if I do something like:  

    a = TensorBase(np.array([1,2,3,4]))
    a.set_()

it will not change anything,(although I haven't tried your code, I think I'm right) but  the same operation in torch:  

    a = torch.tensor([1,2,3,4])
    a.set_() 

will result in `torch.FloatTensor with no dimension`. you should probably check that first link.

**Comment by sp4ke** [comment]
@iamtrask I'll try to finish it this week

**Comment by bharathgs** [comment]
@sp4ke any updates on this one?

**Comment by sp4ke** [comment]
Yes still in progress just didn't have enough time last week. I'll try to
make an update this weekend.

On Nov 3, 2017 4:11 AM, "bharath g s" <notifications@github.com> wrote:

@sp4ke <https://github.com/sp4ke> any updates on this one?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenMined/PySyft/pull/323#issuecomment-341613946>, or mute
the thread

**Comment by sp4ke** [comment]
With regard to #212 which implements size, why is not respecting the [PyTorch api](http://pytorch.org/docs/master/tensors.html#torch.Tensor.size) ?  PyTorch `size()` returns a tuple, shouldn't we do the same and have an other method if a flat size number is needed ?

I know this is not directly related to #212 but since I have it also on my PR and many of my tests rely on it I wanted to make sure this is what is expected.

**Comment by bharathgs** [comment]
1. Syft does return a tuple  I suppose because it's basically doing `np.array.shape`
(on other note, you might want to consider removing stride, as we already have it implemented)

**Comment by sp4ke** [comment]
@bharathgs Not sure what's wrong with the code coverage ?

**Pull request closed without merging**
