### PR TITLE
Added size() method for remote tensors

### PR DESCRIPTION
**Pull request by DanyEle**
Added a basic version of the size() method for remote tensors.

A lot of tests are still not passing though. Suggestions on what could be fixed so as to make all tests pass. If the size() method is successfully implemented, we would also "unlock" the usage of LSTMs in PySyft.

Implementation for issue #2201

### CODE REVIEW

**Comment by LaRiffle** [comment]
Can you add a test to this change to seee what is now possible?

**Comment by DanyEle** [comment]
Now the forward pass into LSTMs is working. I added a couple of tests for the size of remote tensors and the usage of the forward phase with LSTMs. 


```
def test_lstm(workers):
    bob = workers["bob"]
    lstm = nn.LSTM(3, 3)
    inputs = torch.randn(5, 1, 3)
    hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
    out, hidden = lstm(inputs, hidden)
    assert out.shape == torch.Size([5, 1, 3])
    lstm = nn.LSTM(3, 3)
    lstm.send(bob)
    inputs = torch.randn(5, 1, 3).send(bob)
    hidden = (
        torch.randn(1, 1, 3).send(bob),
        torch.randn(1, 1, 3).send(bob),
    )  # clean out hidden state
    out, hidden = lstm(inputs, hidden)
    #This test will pass once the .size() method is implemented for
    #remote tensors
    assert out.shape == torch.Size([5, 1, 3])
```

**Comment by LaRiffle** [comment]
Good, add also basic .size() tests for all tensors where you added ( in the test_<tensor_type>.py files), or don't forget to push the work if you already added them :)

**Comment by DanyEle** [comment]
> Good, add also basic .size() tests for all tensors where you added ( in the test_<tensor_type>.py files), or don't forget to push the work if you already added them :)

Yep, I re-named a test for the size of local tensors to test_local_size and create a new test case for testing the size() method using remote tensors.

**Comment by LaRiffle** [comment]
The numerous tests failing in this PR confirm the hypothesis made in #2221 
https://github.com/OpenMined/PySyft/issues/2201#issuecomment-497712040
Hooking size() is not possible because it is used internally

**Comment by DanyEle** [comment]
Once #2349 is merged, we may as well close this PR.

**Comment by DanyEle** [comment]
Actually, it looks like https://github.com/OpenMined/PySyft/pull/2349 is not overriding the forward pass of LSTMs / GRUs, so this method would still be needed for them.

**Pull request closed without merging**
