### PR TITLE
PIL.Image.Image for torchvision

### LINKED ISSUE #5324: Add PIL.Image.Image for torchvision
## Description
Add `PIL.Image.Image` return type support for `torchvision`.

## Definition of Done
`torchvision/allowlist.py` can enable `to_pil_image` and `to_grayscale`.

### PR DESCRIPTION
**Pull request by Koukyosyumei**
## Description
Closes #5324 

## Affected Dependencies
PIL

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by Param-29** [comment]
A couple of small reviews
1. You could install `pre-commit` to run **Python-Linting** tests before you commit (You can read more about it [here](https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md#pre-commit))
2. Lookout for merge conflict, when (#5152) gets merged. 

Hope this helps!

**Comment by madhavajay** [comment]
@Koukyosyumei  thats awesome work. Any chance you could also quickly throw in a PR with `numpy.ndarray` which also uses Torch to transport it across the serde? That would mean a lot of other code which returns ndarrays like `sklearn` could also be worked on. ❤️

**Comment by Koukyosyumei** [comment]
@madhavajay 
That would be fine!

**Comment by madhavajay** [comment]
@Koukyosyumei Last thing would be some tests just to show it works, so just create a test with a virtualmachine and load an image, send it to the client and retrieve it back and assert it matches. Then use the remote API to create the PIL image remotely if you can. That might require creating one with torchvision via a tensor first and then passing the PIL in the store into the PIL constructor.

**Comment by Koukyosyumei** [comment]
@madhavajay 
Should I edit tests/syft/lib/torchvision/allowlist_test.py or add a new test file?

**Comment by madhavajay** [comment]
@Koukyosyumei let's add its own set of tests and it should be added to the `requirements.libs.txt` file as well.

**Comment by madhavajay** [comment]
Feel free to use an existing image like the syft or duet logo from the existing repo in `/docs/img`.

**Comment by Koukyosyumei** [comment]
@madhavajay 
I added tests, and it worked!

**Review by madhavajay — APPROVED** [review]
@Koukyosyumei Wow this is really great work. I love the thoroughness of the PIL / torchvision test.

I made one small fix the return type which had an accidental "," comma and then changed the remote url to a local .png file.

I think is is good to merge! ❤️

**Comment by Koukyosyumei** [comment]
@madhavajay 
Thank you for your review and fix! Please merge it.

**Comment by Param-29** [comment]
@Koukyosyumei  I believe there is one small change that we can do 
```
torchvision.transforms.functional.pil_to_tensor(pic)
```

I don't think we support this yet, but we can add support for this, and in `tests/syft/lib/torchvision` there is a file I had added, `imageTensor.pt`, this can then be deleted and in the following function, **you could convert PySyft's logo to tensor and use that tensor for tests** 
```
@pytest.fixture(scope="function")
def tens() -> torch.Tensor:
    if path.isfile("imageTensor.pt"):
        return torch.load("imageTensor.pt")
    else:
        cwd = os.getcwd()
        path_file = cwd + "/tests/syft/lib/torchvision/" + fileName
        return torch.load(path_file)
```
Not a big change but would go a long way in maintaining the library 

Reviews could take a pool if this should be done, either in this PR or a new issue!

I hope my expectations were clear enough, if not we could talk over slack. 

Cheers!

**Comment by madhavajay** [comment]
@Param-29 Great suggestion, lets address that as a separate PR:
https://github.com/OpenMined/PySyft/issues/5368

**Pull request merged**
