### PR TITLE
Updated /lib/python tests to Python 3.9

### LINKED ISSUE #5327: Add updated CPython integration tests for 3.9
## Description
We need to update our CPython integration tests to also support python 3.9.

## Definition of Done
The following files are updated to include changes for Python 3.9: https://github.com/python/cpython/tree/3.9/Lib/test
```
tests/syft/lib/python/collections/ordered_dict/ordered_dict_sanity_test.py
tests/syft/lib/python/complex/complex_test.py
tests/syft/lib/python/dict/dict_test.py
tests/syft/lib/python/float/float_test.py
tests/syft/lib/python/list/list_test.py
tests/syft/lib/python/string/string_utils_test.py
```

### PR DESCRIPTION
**Pull request by ArtistBanda**
## Description
Updated CPython integration tests from the official tests at https://github.com/python/cpython/tree/3.9/Lib/test
Fixes #5327 

## Affected Dependencies
None

## How has this been tested?
All the tests passing. Tested on python 3.8 and python 3.9

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@ArtistBanda nice! I can highly recommend testing the tests on each version of Python in a virtualenv locally first, because the new tests will likely break on older versions of python. If you see in side the tests we have a few places where we handle this already.

```python
#complex_test.py
self.assertEqual(Complex(complex0(1j)), 42j)
if sys.version_info >= (3, 7):
    # Only deprecated from python 3.7
    with self.assertWarns(DeprecationWarning):
        self.assertEqual(Complex(complex1(1j)), 2j)
self.assertRaises(TypeError, Complex, complex2(1j))
```

**Comment by ArtistBanda** [comment]
Will do @madhavajay . 
I should check these python versions : 3.6, 3.7, 3.8 and 3.9, right?

**Comment by ArtistBanda** [comment]
Tested on these python versions:
- [x] Python 3.6
- [x] Python 3.7
- [x] Python 3.8
- [x] Python 3.9

Fixed version dependency issues.

**Review by tudorcebere — APPROVED** [review]
Really nice work! Looks good to me!

**Review by tudorcebere — APPROVED** [review]

**Pull request merged**
