### PR TITLE
Helper function to try websocket connection

### PR DESCRIPTION
**Pull request by Jasopaum**
Sometimes, a ConnectionRefusedError was raised when trying to instantiate a WebsocketClientWorker in the tests for websocket workers.
The introduced helper function waits if the websocket client could not be instantiated before trying once more (5 tries max)

### CODE REVIEW

**Comment by mccorby** [comment]
Hi Jason,
I think we keep falling into the same issue with regard to the sockets or any other network connection. This is a problem we have not yet solved with in our tests.
I think the solution should be based on mocking the `websocket` instead of trying to use an actual one.

By mocking the responses of the methods of the socket, we can stop relying on it being connected, not falling, etc... We don't want to test the `websocket` class, we want to test our classes

This will require more work though as we have to figure out the responses (part of the issue to describe the serde process).

```

**Comment by midokura-silvia** [comment]
@mccorby 
I discussed this helper function with Jason, and IMHO it is the easiest thing to get around the websocket connection problem that he experienced in #2373.
You are right, we should split unit tests from integration tests (websocket tests are definitely integration tests). But this will be a separate bigger task.

**Comment by midokura-silvia** [comment]
Just noted that I was a bit too quick to merge the pull request. I will open a new one that will remove all the redundant time.sleep() commands.

**Comment by Jasopaum** [comment]
Oops, I thought I had removed them! Thanks

**Pull request merged**
