### PR TITLE
Added Hindi Translated Notebook 7 example

### PR DESCRIPTION
**Pull request by kaustubh-seachange**
* feat: Added Hindi Translated Notebook 7 example

Signed-off-by: Kaustubh Patil <kaustubh.pnj@gmail.com>

* feat: Maintained existing directory structure used by Arkadip <in2arkadipb13@gmail.com>

Signed-off-by: Kaustubh Patil <kaustubh.pnj@gmail.com>

### CODE REVIEW

**Comment by Yugandhartripathi** [comment]
@kaustubh-seachange add your name as translator in the first cell below the author's

**Comment by raheja** [comment]
@kaustubh-seachange @Yugandhartripathi  can this translation be merged into the tutorials? 
I have started translating the other notebooks since we are on a deadline. We plan to release the translations by mid Feb, so all translations and reviews must be completed by next weekend. @kaustubh-seachange can you please ensure Notebook 7 and 8 are reviewed and updated?

**Comment by kaustubh-seachange** [comment]
@raheja @Yugandhartripathi Would you review this PR and merge them I have already pushed the changes for hindi tutorial 8 into the forked branch. Letme put that in my schedule to complete next tutorial 9 and 10.

**Comment by raheja** [comment]
@kaustubh-seachange hey! :)
So i finished 9 and 10 a few days back and have asked to them to merged into the master.  If you have time, you can review them (instead of translating again) --  on pull request 2909. That way we can push for changes asap :)

**Comment by raheja** [comment]
@Yugandhartripathi @kaustubh-seachange all notebooks apart from 7 have been uploaded onto the hindi tutorials. Can you please follow up on Notebook 7? @kaustubh-seachange you need to add your name to the translations like yugandhar mentioned before. Please add that so that your translations can be merged.

**Comment by karlhigley** [comment]
Looks like this has a conflict on Part 08?

**Comment by Yugandhartripathi** [comment]
Yeah plans notebook was revised recently so merge conflicts need to be resolved too

**Comment by Yugandhartripathi** [comment]
Sorry @kaustubh-seachange for all the work you put in. 
But due to lack of response we have merged #3055 and now have to close this. 
Looking forward to your future contributions :+1:

**Comment by Yugandhartripathi** [comment]
@karlhigley I think we can close this one now.

**Comment by karlhigley** [comment]
Superseded by #3055.

**Pull request closed without merging**
