### PR TITLE
Adding an example for Paillier Homographic Encrypted Linear Classification

### PR DESCRIPTION
**Pull request by gautam1858**
Have added Paillier Homographic Encrypted Linear Classification with an example using diabetes example from sklearn and updated the requirement.txt by adding sklearn so that docker installs sklearn works well

### CODE REVIEW

**Comment by iamtrask** [comment]
Let's remove that .DS_Store

**Comment by iamtrask** [comment]
Quick Question... what makes all the gradients decrypted? When I read it from top to bottom it looks like the model is encrypted. Is it not?

**Comment by gautam1858** [comment]
hmmm I think its decrypted right ?

**Comment by gautam1858** [comment]
ran the script again but now its showing "e" for the encrypted values don't know what happens but after some cycles giving error like this 

`Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
Grads:PaillierTensor: [[e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]
 [e]]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-d64b7c6443aa> in <module>()
      1 for iter in range(9):
      2     for i in range(len(input)):
----> 3         print("Grads:" + str((model.learn(input=input[i],target=target[i],alpha=0.5))))

/usr/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/nn/linear.py in learn(self, input, target, alpha)
     75         """
     76 
---> 77         weight_update = self.generate_gradient(input, target)
     78         self.weights -= weight_update * alpha
     79 

/usr/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/nn/linear.py in generate_gradient(self, input, target)
    124         for i in range(len(input)):
    125             if(input[i] != 1 and input[i] != 0):
--> 126                 weight_grad[i] += (output_grad[0] * input[i])
    127             elif(input[i] == 1):
    128                 weight_grad[i] += output_grad[0]

/usr/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/he/paillier/basic.py in __add__(self, tensor)
     34             tensor = PaillierTensor(self.public_key, tensor.data)
     35 
---> 36         return PaillierTensor(self.public_key, self.data + tensor.data, False)
     37 
     38     def __sub__(self, tensor):

/usr/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/syft/he/paillier/basic.py in __add__(self, y)
    125 
    126         out = Float(self.public_key, None)
--> 127         out.data = self.data + y.data
    128         return out
    129 

/usr/lib/python3.6/site-packages/phe/paillier.py in __add__(self, other)
    732         """Add an int, float, `EncryptedNumber` or `EncodedNumber`."""
    733         if isinstance(other, EncryptedNumber):
--> 734             return self._add_encrypted(other)
    735         elif isinstance(other, EncodedNumber):
    736             return self._add_encoded(other)

/usr/lib/python3.6/site-packages/phe/paillier.py in _add_encrypted(self, other)
    937         a, b = self, other
    938         if a.exponent > b.exponent:
--> 939             a = self.decrease_exponent_to(b.exponent)
    940         elif a.exponent < b.exponent:
    941             b = b.decrease_exponent_to(a.exponent)

/usr/lib/python3.6/site-packages/phe/paillier.py in decrease_exponent_to(self, new_exp)
    838             raise ValueError('New exponent %i should be more negative than '
    839                              'old exponent %i' % (new_exp, self.exponent))
--> 840         multiplied = self * pow(EncodedNumber.BASE, self.exponent - new_exp)
    841         multiplied.exponent = new_exp
    842         return multiplied

/usr/lib/python3.6/site-packages/phe/paillier.py in __mul__(self, other)
    752             encoding = other
    753         else:
--> 754             encoding = EncodedNumber.encode(self.public_key, other)
    755         product = self._raw_mul(encoding.encoding)
    756         exponent = self.exponent + encoding.exponent

/usr/lib/python3.6/site-packages/phe/paillier.py in encode(cls, public_key, scalar, precision, max_exponent)
    619         if abs(int_rep) > public_key.max_int:
    620             raise ValueError('Integer needs to be within +/- %d but got %d'
--> 621                              % (public_key.max_int, int_rep))
    622 
    623         # Wrap negative numbers by adding n

ValueError: Integer needs to be within +/- 8536137787279217423399174435297537650982591404457008653156180651396073443713727707181722108113862071626332359327651077297167454191115248645595526858287668184186694459302011522789272172510061333536253312827068391996620168441280630549539463810335165016971525789291105337923121778269673047487076147408121044682541397733282352809497390412481648540576832781240978132940657828502357540418538940928197003612758324369776408726276495041747901961808821255150463842488895656895412921733730721068655495532036514946079935073031769149986701923179687123585545340532482608630693038353195346381107612772504725483049597176270976354979 but got 655466754302027714322819661568689458302857062813893029916810214032172464849991899428175362385124675671632003007392555317026101508464223851208913347457083249601766362030654880800282710668498531995907778757840049628217604377510433021835557203224514313665848349095370601982962298359506641352238071613054087474623714918561820888154293410637373426976653520488468705883155492711028085203492237042880640868734734404488445364849019662004572435975403272187135117187688869565578024111081791013364671988124090593819068611936862086379573149845116951662689306102910232920843992125347141732675898573395939496099143140718300114593292735560409641097394602163306496

In [ ]:
 `

**Comment by iamtrask** [comment]
So the temporary fix for this is to use Capsule to clean out the tensors in the interim https://github.com/OpenMined/Capsule/blob/master/notebooks/Capsule%20with%20Django.ipynb . Integrate it with this demo and then we can merge this PR?

**Comment by iamtrask** [comment]
I also showed a demo of using the Capsule in the latest video. https://www.youtube.com/watch?v=tQ5v3OzSGck

**Comment by iamtrask** [comment]
If you'll modify this to use Capsule, I'd love to merge it!

**Comment by gautam1858** [comment]
@iamtrask have updated the code, please check

**Comment by iamtrask** [comment]
Gorgeous!

**Comment by MtDersvan** [comment]
Does this notebook requires `capsule` to be installed? Should requirements be updated?

**Comment by gautam1858** [comment]
Yes needs to updated  :)

**Pull request merged**
