### PR TITLE
Improve benchmarking

### PR DESCRIPTION
**Pull request by teo-milea**
## Description
This PR is for parameterizing and extending the benchmark.

## Affected Dependencies
-
## How has this been tested?
-

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

@tudorcebere

### CODE REVIEW

**Comment by madhavajay** [comment]
@teo-milea can you rebase this on the latest dev if its still needed?

**Comment by madhavajay** [comment]
@teo-milea and @bitsofsteve can I get a sanity check on this, I am a bit out of the loop on the benchmarking code, but I got it running locally on my machine so I assume that means its working. Also I think the readme needs updating but I don't know if there are any replacement args for all the changes to removing REPT and SEPT?

**Comment by bitsofsteve** [comment]
> 

@madhavajay this PR is @teo-milea 's effort to improve benchmarking, mostly the code structure e.g parametrization, it was totally separate from the original benchmarking work which is already merged, so this doesn't impact the way we do benchmarking now, they're progressive improvements. @teo-milea ???

**Comment by teo-milea** [comment]
Yes its' only about parametrization and usage of tests. I will check it once more and push a final version so we can close.

**Comment by teo-milea** [comment]
It seems it works and the linting passed so we can merge, After the AdAstra demos, I will expand on this to use Kibana for visualization.

**Comment by madhavajay** [comment]
👍

**Review by bitsofsteve — APPROVED** [review]
@madhavajay this looks good to me now, I intend to have a `p2p` with @teo-milea sometime tomorrow to see if there's anything hanging to make this merge. Once all is well, I'll just merge this.

**Comment by madhavajay** [comment]
@teo-milea and @bitsofsteve is this ready for merge?

**Comment by teo-milea** [comment]
@madhavajay yep good to go, we will discuss at a later day how to improve it further

**Pull request merged**
