### PR TITLE
add make targets for redis and capsule

### PR DESCRIPTION
**Pull request by nishanthprakash**

### CODE REVIEW

**Comment by iamtrask** [comment]
@bharathgs could i get your thoughts on this guy post-update?

**Comment by bharathgs** [comment]
The Makefile has `FLASK_APP=/usr/bin/Capsule/capsule/local_server.py flask run &` but should it not be `../capsule_zmq/local_server.py` ?

**Comment by nishanthprakash** [comment]
I think the django and flask capsule servers have been removed. I'll update this accordingly soon; sorry about the delay.

**Comment by bharathgs** [comment]
@nishanthprakash could you also change [this](https://github.com/OpenMined/PySyft/blob/9bdf747c5b037c527743cae728ce562bc6eb64a8/Makefile#L19) to `pytest && flake8 --ignore=E501`

**Comment by nishanthprakash** [comment]
Done. I notice that in the test target, some scripts still use Django (so do some of the demo notebooks).

**Pull request merged**
