### PR TITLE
Add federated learning optimizer to tutorials

### PR DESCRIPTION
**Pull request by dcato98**
This pull request addresses 2 out of 3 notebooks mentioned in #3293. Note: In MNIST tutorial 6, I used the AdamW optimizer instead of SGD. This means +99% accuracy is achieved in 1 epoch - I find this very satisfying and it gives beginners more time to really play with PySyft instead of waiting on slow training results. If you prefer not to use AdamW optimizer, I'll change back to SGD+momentum.

### CODE REVIEW

**Comment by gmuraru** [comment]
LGTM!

**Comment by karlhigley** [comment]
It looks like would also imply changes to translated tutorials, so requesting a review from the Writing Team to figure out how to make that happen.

**Comment by LaRiffle** [comment]
This PR is empty of changes 🤔 
Should we close it?

**Comment by dcato98** [comment]
I'd forgotten about this PR but it looks like these changes must have been merged in from somewhere else. Closing.

**Pull request closed without merging**
