### PR TITLE
Bumped to torch 2.2 and python 3.12

### PR DESCRIPTION
**Pull request by madhavajay**
- fixed some raw string regex issues
- deprecated python 3.9
- added python 3.12

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by kiendang** [comment]
@shubham3121 most changes here are from ruff. Files need reviewing are `numpy_function_test.py`, `setup.cfg`, `recursive_primitives.py` (where I added serde for `types.UnionType` i.e. `X | Y`).

**Comment by shubham3121** [comment]
@kiendang I see conflicts with recent dev, I will work on resolving it, first thing tomorrow.

**Comment by kiendang** [comment]
I resolved the conflicts. Protocol version's messed up again though due to the type annotation syntax change.

**Comment by kiendang** [comment]
Oh `AZURE_BLOB_STORAGE_KEY` not being set is due to this PR being created in Madhava's fork. Let's switch to #8559.

**Pull request closed without merging**
