### PR TITLE
Fix uploading to s3 error handling

### PR DESCRIPTION
**Pull request by kiendang**
## Description
Related to #6940. In `upload_to_s3_using_presigned`, the `upload_response` variable inside the `except` block

https://github.com/OpenMined/PySyft/blob/e0437171109d9f580c0445cf659191e4c773694b/packages/syft/src/syft/core/node/common/util.py#L270-L274

refers to the `upload_response` on line 193

https://github.com/OpenMined/PySyft/blob/e0437171109d9f580c0445cf659191e4c773694b/packages/syft/src/syft/core/node/common/util.py#L193

However it's wrongly overwritten inside the `try` block on line 234

https://github.com/OpenMined/PySyft/blob/e0437171109d9f580c0445cf659191e4c773694b/packages/syft/src/syft/core/node/common/util.py#L234

resulting in `AttributeError: 'Reply' object has no attribute 'upload_id'` if there's any exception raised after line 234, *e.g.* #6940.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Review by IonesioJunior — COMMENTED** [review]
@kiendang Do you think we could add a small test in PySyft integration tests for this?

**Review by IonesioJunior — APPROVED** [review]
Great work @kiendang! Amazing debugging skills!

**Comment by kiendang** [comment]
@IonesioJunior I'd prefer we merge this now to unblock other related issues. For the integration test I created #6998.
@rasswanth-s This does not actually fix the underlying issue in #6940, only the exception handling part so I just removed the link.

**Review by rasswanth-s — APPROVED** [review]
Amazing Work, kudos for extensive description 🚀

**Pull request merged**
