### PR TITLE
added openmined slack badge to README 💯

### PR DESCRIPTION
**Pull request by cypherai**

### CODE REVIEW

**Comment by anoff** [comment]
I'd rather put this on in the docs repository. Or should we add it to each repo?

**Comment by cypherai** [comment]
I agree with you that having this badge in the docs first make sense. However the good side of having it on each repo is that it would facilitate access to our slack for people arriving from Github.

**Comment by swaroopch** [comment]
But ideally, we should be pointing people to the quickstart guide so that they know what slack channels to join ( see https://github.com/OpenMined/Docs/pull/35 ) instead of landing them directly to slack without guidance.

Also don't new folks need to get an invite before visiting the slack site?

**Comment by iamtrask** [comment]
Yeah @anoff I think you both are quite right. It should be in both.

**Pull request merged**
