### PR TITLE
Move send_tensor.py form mnist examples to tests/benchmarks

### PR DESCRIPTION
**Pull request by karynaur**
## Description
Move send_tensor.py form mnist examples to tests/benchmarks [this issue](https://github.com/OpenMined/PySyft/issues/5308).

## Affected Dependencies
None

## How has this been tested?
None

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by Param-29** [comment]
@karynaur I believe what is required is to write benchmark tests similar to `send_tensor.py`. So you could create a test named `benchmark_send_tensor.py ` to get the expected functionality. 

Also to make sure that python-linting tests pass, you could install `pre-commit`.  
You can read more about it [here](https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md#pre-commit)

**Comment by madhavajay** [comment]
@karynaur are you still able to fix this properly?

**Comment by karynaur** [comment]
Thank you for the review Param! Ill read about pre-commit. @madhavajay Could you advice me on what to put into the benchmark_send_tensor.py test. A link to a documentation explaining the same would be fine too!

**Comment by tudorcebere** [comment]
Hi @karynaur!

Please take a look at the other benchmarks in that folder. We don't have docs yet on how to make a benchmark, but after you get it (it's not hard), you could write a tutorial on it! :) 

Thank you!

**Comment by tudorcebere** [comment]
Due to inactivity, I'll close this PR. If you are interested in working on this, please open a fresh PR @karynaur.

Thank you!

**Pull request closed without merging**
