### PR TITLE
Feature/tensor  lerp

### PR DESCRIPTION
**Pull request by chadlohrli**

### CODE REVIEW

**Comment by iamtrask** [comment]
also some style errors :)

**Comment by iamtrask** [comment]
@bharathgs does it not do the lerp similarly to pytorch? it looks quite similar.

**Comment by bharathgs** [comment]
@iamtrask  `start` & `end` -> tensors, `weight` -> scalar, the current code does not operate on tensors and also check the inputs that this is taking in.

**Comment by alberduris** [comment]
Now there's another PR with these features implemented.

https://github.com/OpenMined/PySyft/pull/308

**Pull request closed without merging**
