### PR TITLE
Bengali Tutorial Part Two

### PR DESCRIPTION
**Pull request by ucalyptus**
A Part two version in Bengali . Bengali is the 5th largest language in the world.

### CODE REVIEW

**Comment by karlhigley** [comment]
@ucalyptus Don't forget to list yourself as the translator!

**Comment by ucalyptus** [comment]
@karlhigley made changes, awating build finish.

**Comment by ucalyptus** [comment]
fixed it

**Comment by ucalyptus** [comment]
@karlhigley for some AutoCancellation being on reason the build checks are failing, any way to solve this from my side?

**Comment by karlhigley** [comment]
@ucalyptus Looks like the builds on these commits passed. What you're probably seeing is that when you push a new commit, it will cancel any previous queued builds that haven't started running yet.

**Pull request merged**
