### PR TITLE
Bringing back 0.9 api and projects notebooks 

### PR DESCRIPTION
**Pull request by khoaguin**
## Description
According to [this ticket](https://github.com/orgs/OpenMined/projects/81/views/1?pane=issue&itemId=31383033)

### CODE REVIEW

**Comment by rasswanth-s** [comment]
@khoaguin great start on the PR, Could we also add back projects folder back in 0.9

Initial removal PR:
https://github.com/OpenMined/PySyft/pull/7807/files

**Comment by khoaguin** [comment]
Sure @rasswanth-s I will do that

**Comment by khoaguin** [comment]
Somehow I added `api/0.9` in `TEST_NOTEBOOK_PATHS = {env:TEST_NOTEBOOK_PATHS:api/0.8,api/0.9,tutorials}` in `tox.ini` for `testenv:stack.test.notebook` and expect the checks to fail but they are still succeeding

**Comment by rasswanth-s** [comment]
@khoaguin  we need to add it in `pr-tests-syft.yml`
you could add them to `pr-tests-syft-notebook-python`, we could eventually move them to containers.

We set the TEST_NOTEBOOK_PATHS in that yaml file.

**Comment by khoaguin** [comment]
Thanks @rasswanth-s I will look into this

**Comment by rasswanth-s** [comment]
@khoaguin , I pushed a  small fix to this branch
https://github.com/OpenMined/PySyft/pull/7874
which prevented the notebooks tests from running and merged dev into yours

Now hopefully the tests would run, after including in TEST_NOTEBOOOK_PATHS

**Comment by khoaguin** [comment]
Thank you very much @rasswanth-s

**Comment by khoaguin** [comment]
Hi @koenvanderveen I am working on the `06-eager-execution.ipynb` notebook for the current api and saw something a bit weird like in the picture. The value should be 28, right, but somehow it returns 29?

temp

**Comment by khoaguin** [comment]
Hi @shubham3121 @kiendang I am running the notebook `07-queue.ipynb` but got the below error. I found out that this is because the `queue_item.syft_client_verify_key = None`, hence `api = APIRegistry.api_for` in `QueueItem.fetch` returns `None`. 
image

If I assign the `queue_item` a `verify_key` with `queue_item.syft_client_verify_key = client.credentials.verify_key`, the problem disappears

**Comment by shubham3121** [comment]
Closing this for now. We have most notebooks already in 0.8 and project notebooks we will added later during a refactor.

**Pull request closed without merging**
