### PR TITLE
Minor improvements related to package manager caches in Dockerfile

### PR DESCRIPTION
**Pull request by kiendang**
## Description
Couple of improvements related to `--mount=type=cache`.
Most importantly is adding `id=pip-$UID` to pip cache to use different caches for different users. Since we now support both root and rootless, not separating the caches could lead to a permission error.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by khoaguin** [comment]
Thanks @kiendang. I am working on the test for the `syft_base_cpu.dockerfile` image. Let me integrate these changes into it

**Comment by kiendang** [comment]
@khoaguin you can create a WIP PR. I'll push these commits there.

**Comment by khoaguin** [comment]
@kiendang here it is https://github.com/OpenMined/PySyft/pull/8274

**Comment by kiendang** [comment]
integrated into #8274

**Comment by kiendang** [comment]
https://github.com/OpenMined/PySyft/actions/runs/6968364753/job/18962116916?pr=8273

Sometimes the `apk add` command fails with

```
#13 [backend backend 2/6] RUN --mount=type=cache,target=/var/cache/apk     apk update &&     apk add tzdata bash python-3.11 py3.11-pip &&     ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime && echo Etc/UTC > /etc/timezone &&     mkdir -p /var/log/pygrid /root/data/creds /root/data/db /root/.cache /root/.local
#13 0.398 fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
#13 0.722 WARNING: updating https://packages.wolfi.dev/os: No such file or directory
#13 0.742  [https://packages.wolfi.dev/os]
#13 0.742 0 unavailable, 1 stale; 28537 distinct packages available
#13 ERROR: process "/bin/sh -c apk update &&     apk add tzdata bash python-$PYTHON_VERSION py$PYTHON_VERSION-pip &&     ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&     mkdir -p /var/log/pygrid $HOME/data/creds $HOME/data/db $HOME/.cache $HOME/.local" did not complete successfully: exit code: 1
```

but passes when rerun.

**Pull request closed without merging**
