### PR TITLE
Fix read permission for manual approve

### LINKED ISSUE #6899: DS can not retrieve the results of their computations even after being approved.
## Description
Data Scientists can not retrieve the result of their computations even after having their data access request approved by the Data Owner.

## How to Reproduce
```
import syft as sy

do_client = sy.login(
    email="info@openmined.org",
    password="changethis",
    port=8081
)

# Create a new Data Scientist User
do_client.users.create(name='DataScientist', 
    email='DataScientist@gmail.com', 
    password = 'DataScientist',
    budget=0,
    role = "Data Scientist"
)

# login as a Data Scientist User
ds_client = sy.login(
    email="DataScientist1@gmail.com",
    password="DataScientist",
    port=8081
)


# Send a tensor using the Data Owner Session
x_s = x.send(do_client, tags=["#X", "#diabetes"], description="My diabetes y label")

# Get a pointer to the data using the Data Scientist Session
ds_x_pointer = ds_client.store[0]

# Perform Arbitrary computation
result = ds_x_pointer + ds_x_pointer

# Submit Data Access request as a Data Scientist
result.request(reason="I'd like to see my result ...")

# Approve Data Access Request as a Data Owner
do_client.requests[0].approve()


# Try to retrieve your result as a Data Scientist
result.get_copy()
```

## Expected Behavior
We should be able to retrieve the values of our result if the data access request was approved.

## Additional Comments
- This workflow is important for the not fully automated use cases where we don't use Differential Privacy and the Data Owner still needs to inspect data access requests.
- It's important to add some tests to keep tracking this workflow in future changes as well.
- Special thanks to @mikaelapisani  for discovering and reporting it.

### PR DESCRIPTION
**Pull request by teo-milea**
## Description
This PR fixes  #6899.

## How has this been tested?
I need to add some tests for this, but we have to decide if a new suite for requests is needed or maybe we could just modify an existing test.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by teo-milea** [comment]
Thank you, @IonesioJunior!! Should I add here some new tests for requests or should we merge this and do it in a new PR?

**Review by iamtrask — APPROVED** [review]
woah! +1 to @IonesioJunior 's comments on excellent debugging skills! Well done Teo!

**Comment by rasswanth-s** [comment]
@teo-milea  , I tested it locally on my machine, I am still getting the request error.

**Comment by IonesioJunior** [comment]
Yup  ❤️, please add it here if it's possible.

**Comment by teo-milea** [comment]
Great catch from @rasswanth-s and even better debugging skills with that nasty SQLAlchemy bug!!

**Comment by rasswanth-s** [comment]
@teo-milea , It is due to a great P2p with you, Teamwork makes the Dreamwork, Go TEAM 🚀

**Comment by rasswanth-s** [comment]
Screenshot:
Screenshot 2022-10-27 at 10 59 54 PM

**Comment by shubham3121** [comment]
Great work guys !! 🙌🏾

**Pull request merged**
