### PR TITLE
[FIX] Frontend: Partial Functionality Delete Function 

### PR DESCRIPTION
**Pull request by IonesioJunior**
## Description
Fix the Frontend User Delete feature and optimize backend response performance.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by tcp** [comment]
Great @IonesioJunior!

**Comment by rasswanth-s** [comment]
We get this error after deleting a domain and submitting the response
Screenshot 2022-11-22 at 12 16 48 PM

**Comment by tcp** [comment]
@rasswanth-s it's ok -- I'll add the frontend fix shortly.

**Comment by tcp** [comment]
> Maybe we should prevent that scenario.
I suggest we open a new issue for that

> I think that even after the we delete the root domain user,we are able to do operations with the already created syft client

I suggest we open a new issue for handling that bug, so we keep this small :)

**Comment by madhavajay** [comment]
Great find that deleted users can still do things issue.

Please file a seperate issue and keep this PR in scope for this issue: https://github.com/OpenMined/PySyft/issues/6990

**Pull request merged**
