### PR TITLE
[WIP] Removing xfail annotations 

### LINKED ISSUE #4974: Fix @pytest.mark.xfail tests
## Description
We have several @pytest.mark.xfail tests which we should fix.

## Definition of Done
@pytest.mark.xfail annotations are removed and tests are fixed and pass.

### PR DESCRIPTION
**Pull request by rajatrc1705**
## Description
I have found 4 tests with "xfail" markers. One of them is test_free_after_iterating().

The test_free_after_iterating function, as I understand is checking whether the iterator is empty(deallocated) after getting exhausted. The support.check_free_after_iterating function seems to be failing the tests. So I implemented a for loop to check for the same. Tell me if I understood the function wrongly.
Fixes #4974 
## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?

`pytest tests/syft/lib/python/dict/dict_test.py -k test_free_after_iterating`

This gives xpassed verdict.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by tudorcebere** [comment]
Hi! One mention for this PR before I start reviewing is that it should have a base from 0.4. Do you mind cherry picking those commits and rebasing with 0.4? I can help you with that if you are not so familiar with git. Drop me a message on slack and we can have call to fix that.

**Comment by rajatrc1705** [comment]
I have rebased as you asked to. Now maybe you could review it and tell me if I am going in the right direction with the PR...

**Comment by madhavajay** [comment]
@rajatrc1705 The goal is to change our code so that it passes these tests not changing the tests so that our code passes.
These tests are from the official CPython repository:
https://github.com/python/cpython/blob/3.8/Lib/test/test_dict.py

So if our code doesn't pass these checks there could be issues. 

As you can see even though the original test references `dict` if you substitute `UserDict` into the test it passes:
```python
@pytest.mark.slow
def test_free_after_iterating(self):
    from collections import UserDict

    # this seems like a bit of a puzzle
    support.check_free_after_iterating(self, iter, UserDict)
    support.check_free_after_iterating(self, lambda d: iter(d.keys()), UserDict)
    support.check_free_after_iterating(self, lambda d: iter(d.values()), UserDict)
    support.check_free_after_iterating(self, lambda d: iter(d.items()), UserDict)
```

```
tests/syft/lib/python/dict/dict_test.py::DictTest::test_free_after_iterating PASSED [100%]
```

Since we subclass from UserDict we should be able to pass this test too.

**Comment by rajatrc1705** [comment]
Ohh. My bad, I got it wrong, closing this PR. Will submit another one with correct code. Thanks for guiding 👍

**Pull request closed without merging**
