### PR TITLE
[WIP]  Testing #5033

### LINKED ISSUE #5033: TODOs fix - Torchvision - Compose.transforms
In `src/syft/lib/torchvision/allowlist.py` we have a TODO: `Compose.transforms property only exists on the object not on the class?`. 

## Additional Context
The fix has to be made and a test has to be written.

## Note
This issue will not be assigned to anybody until a PR is opened.

### PR DESCRIPTION
**Pull request by rahul-art**
## Description
try to closes #5033  
This PR hopes to solve Issue #5033  .

## How has this been tested?
-below is  the tests that you ran to verify the changes.
- and instructions so we can reproduce.
- we can see that Compose.transforms property only exists on the object(cn) not on the class(Compose).
pysyft_dev #5033
in above screenshot we can see that Compose takes list of transforms(i give two transforms above) so `allowlist["torchvision.transforms.Compose.transforms"] = "syft.lib.python.List"` must be true but I don't knowwhy test are failigs after removing comment before this command in allowlist.py

also need some help to create a test case from this one and  in which file we have to create a test for these

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by rahul-art** [comment]
did we have to add this above type of test into some file??

**Comment by gmuraru** [comment]
> did we have to add this above type of test into some file??

There is a folder with tests (named ```tests``` :D). You should be able to find there also a folder for ```torchvision```

**Comment by rahul-art** [comment]
thanks @gmuraru  i got allowlist_test.py inside tests/syft/lib  for src/syft/lib/torchvision/allowlist.py

**Comment by madhavajay** [comment]
@rahul-art Is this PR still active? The existing commits don't currently add anything.

**Comment by madhavajay** [comment]
I will close this until further notice.

**Pull request closed without merging**
