### PR TITLE
Implemented transpose functionality

### PR DESCRIPTION
**Pull request by axelsly**
✨ Implemented:

1. Transpose function in math.py
2. Tranpose functions for TensorBase
3. T Functions for TensorBase
4. Respective unit tests

### CODE REVIEW

**Comment by iamtrask** [comment]
@axelsly great work sir! Looks like there are a few CircleCl things to take care of though

**Comment by axelsly** [comment]
@iamtrask ready

**Comment by iamtrask** [comment]
@kevinahuber we're getting a really strange dependency error in CircleCI. Any chance you could take a look?

**Comment by kevinahuber** [comment]
@iamtrask I refired both this and develop and the results were the same. While it doesn't seem like anything in the diff would cause that error, bringing this branch up to date is a good start. @axelsly can you resolve those conflicts?

**Comment by kevinahuber** [comment]
@axelsly looks good to merge from me! Thanks. 

Bonus points if you rebase to compress some of those one line commits.

**Pull request merged**
