### PR TITLE
[syft] syft client + jupyter image

### PR DESCRIPTION
**Pull request by yashgorana**
## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by yashgorana** [comment]
Successful build & push to ACR - https://github.com/OpenMined/PySyft/actions/runs/8652828464/job/23726611374

**Review by madhavajay — APPROVED** [review]
Works awesome, but... I do wonder should we call it something else because people might confuse it for the syft "whole thing".

Maybe `syft-jupyter` or `syft-client` or something?

**Review by rasswanth-s — APPROVED** [review]
+1 Maybe we could keep it syft-jupyter ? , as it would be easy to understand.

**Comment by yashgorana** [comment]
Successful build & push to ACR - https://github.com/OpenMined/PySyft/actions/runs/8684032712

**Pull request merged**
