### PR TITLE
[WIP] serde: added a registry class to track classes that needs to be seria…

### PR DESCRIPTION
**Pull request by shubham3121**
# Pull Request

## Description
Added a registry class to track classes that needs to be serialised.
issue: #3626 

## Affected Dependencies
List any dependencies that are required for this change.

## Type of Change
Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation (non-breaking change which adds documentation)
- [ ] Improvement (non-breaking change that improves the performance or reliability of existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I did follow the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md)
- [x] I did follow the [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have added tests for my changes

## Additional Context
Please also include relevant motivation and context.

### CODE REVIEW

**Comment by karlhigley** [comment]
This overlaps a little bit with some of the existing work on `SyftSerializable`. Might want to confer with @tudorcebere on this one.

**Comment by tudorcebere** [comment]
@shubham3121 We might be able to achieve this with existing work, could you describe what is the end goal of this class? (Where/why is it needed?)

**Comment by shubham3121** [comment]
@tudorcebere this class can be used by libraries like Syfer text to register classes that needs to be serailized. Refer to this issue #3626

**Comment by shubham3121** [comment]
Closing this PR as @tudorcebere is already working on the improvement.

**Pull request closed without merging**
