### PR TITLE
Remove `TrainConfig` and everything that depends on it

### PR DESCRIPTION
**Pull request by karlhigley**
## Description

We've been meaning to remove `TrainConfig` for a while now, and there's no way I'm writing a Protobuf schema for something that is slated to be removed.

## Checklist:
* [X] My changes are covered by tests.
* [X] I have run [the pre-commit hooks](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md#setting-up-pre-commit-hook) to format and check my code for style issues.
* [X] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

(See the [the contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md) for additional tips.)

### CODE REVIEW

**Comment by gmuraru** [comment]
Should we start the tests?

**Comment by karlhigley** [comment]
Current state is that everything that depends on `WebsocketWorker` is broken, for reasons I haven't been able to determine. They're pretty hard to debug. 🙁

**Comment by pentium3** [comment]
Why does "websockets_mnist_parallel" be removed? 
Does pysyft support Asynchronous federated learning now?

**Comment by HongdaWu1226** [comment]
> Why does "websockets_mnist_parallel" be removed?
> Does pysyft support Asynchronous federated learning now?
> 
> When I am trying to run run_websocket_server.py with _--notebook mnist-parallel_ option, it reported an error says _" AttributeError: 'WebsocketServerWorker' object has no attribute 'add_dataset' "_.

They updated the PySyft version, where the attribute 'add_dataset' is remove for 'WebsocketServerWorker'. Down your PySyft version to 0.2.5, it will work.

**Pull request merged**
