### PR TITLE
introduce and use TFECluster

### LINKED ISSUE #2242: Test coverage for syft/workers/tfe.py is at 51%
**Describe the bug**
As the title states almost half of the code in tfe.py is not being run
The following lines need coverage
26-37, 53-60, 63-76, 79-80, 83, 86, 91, 106-110

### PR DESCRIPTION
**Pull request by mortendahl**
This PR solves a concurrency issue in the notebooks where sharing of a model happens before the servers are ready, resulting in an error. The solution here is to introduce the notion of a cluster that binds a set of workers together and is started before a model can be served.

Closes #2242.

### CODE REVIEW

**Comment by mortendahl** [comment]
Thanks @LaRiffle! 🙏 

Wanted to get @iamtrask's opinion on the change to the notebooks as well..

**Comment by mortendahl** [comment]
@iamtrask PR for Udacity: https://github.com/udacity/private-ai/pull/9

**Comment by robert-wagner** [comment]
Hey @mortendahl Thanks for the ping. The issues regarding the failing udacity notebook are covered in #2327 cc @LaRiffle as well

**Comment by robert-wagner** [comment]
conflict is resolved by #2329

**Comment by mortendahl** [comment]
@iamtrask should be good to go

**Pull request merged**
