### PR TITLE
Removal of PassthroughTensor from DP TensorPointer

### LINKED ISSUE #6922: Some operations are still implemented in PassthroughTensor and are in the Syft Tensor AST, even though they're not supported
From the list of supported ops, you can see that some ops are not supported: argpartition, partition, cumprod, conj, etc

Some of these are still implemented in PassthroughTensor and still are included in the Syft Tensor API located in `syft/core/tensor/__init__.py` and thus show up when calling `dir(TensorPointer)`

Image

### PR DESCRIPTION
**Pull request by rasswanth-s**
## Description
The PR aims to remove passthrough from DP tensor Pointers, 
Subclassing pointers from PassthroughTensor makes unimplemented methods available on the client side.
Fixes #6922 

## How has this been tested?
Local Testing

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented on my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by kiendang** [comment]
Looks like recently the bump version thing just has been adding trailing white spaces. Do you know where this is configured?

**Review by kiendang — APPROVED** [review]
Other than that LGTM👌

**Comment by rasswanth-s** [comment]
@kiendang  it happens during Continous delivery workflow (`continuous_delivery.yml`)
Code Path:
https://github.com/OpenMined/PySyft/blob/449cbe4862b006317d783e4d3597a901a478d0ad/.github/workflows/continuous-delivery.yml#L65

**Comment by kiendang** [comment]
Looks like it's a known issue with bump2version c4urself/bump2version#201 c4urself/bump2version#185

**Comment by rasswanth-s** [comment]
I think we could run black on continuous-delivery.yml after we bump2version in the CI.

**Pull request merged**
