### PR TITLE
PyGrid client Minor Fixes / Enhancement

### PR DESCRIPTION
**Pull request by IonesioJunior**
## Description
Adjust the `syft.grid.client.get_instances` method to show available cloud instances in a DataFrame in a proper structure.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@IonesioJunior this one is weird, somehow the code is already in there but now it doesnt like it!?
I can't find any reference to this DomainClient type with its `.conn` attribute though so for now iv just disabled the warning by setting the type to `Any` but it would be nice to fix this properly. Do you know where that type with `.conn` exists?

**Comment by IonesioJunior** [comment]
@madhavajay  Yup! It's [this one](). We set it [here](https://github.com/OpenMined/PySyft/blob/d358e191874c4f5e331ebaa1150b4c9c6e3d64b8/src/syft/grid/client/client.py#L60). It's expected by the user to set the proper connection type _(choosing the proper communication protocol they want to use to connect with PyGrid. eg: HTTP, Websocket, WebRTC, etc.)_

The problem is: when it was developed we still had that concept of the node types in mind, so it was designed to be created dynamically, extending the proper node client (Network, Domain, Device, and VirtualMachine) and using the proper Connection (HTTP, Websocket, WebRTC ... ) in order to give support to all client types and node connections using a single function: `connect`. _( PS : But since we'll be removing the node types architecture from the next version, we'll probably refactor this client as well in the next versions )._

**Comment by madhavajay** [comment]
@IonesioJunior okay no problem, do you need me to merge?

**Comment by IonesioJunior** [comment]
Yup, please!

**Pull request merged**
