### PR TITLE
duet examples (closes #4798 and #4796)

### LINKED ISSUE #4796: Add Super Resolution Example Duet Notebooks
## Description
Add two notebook's which reflect the Super Resolution example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/blob/master/super_resolution/

## Definition of Done
The partially runnable Super Resolution example notebooks should be in the examples/duet/super_resolution folder and a README.md should be added in the parent examples/duet directory with a link to the original example and our notebook.

### LINKED ISSUE #4798: Add DCGAN example Duet Notebooks
## Description
Add two notebook's which reflect the DCGAN example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/blob/master/dcgan/

## Definition of Done
The partially runnable DCGAN example notebooks should be in the examples/duet/dcgan folder and a README.md should be added in the parent examples/duet directory with a link to the original example and our notebook.

### PR DESCRIPTION
**Pull request by Koukyosyumei**
## Description
Closes #4798 
Closes #4796 

I add notebooks that work on both on local jupyter lab and google colab.
## Affected Dependencies
No
## How has this been tested?
jupyter lab and google colab

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@syumeikoukyo this is awesome work! ❤️
I am running both notebooks and will be discussing how we can fix the issue of securely fetching the result data of some operations without using the old `handler` `name` param now that we have removed it. As soon as this works I think we will also look at turning this into an Integration Test possibly with only a few batches in dry run.

**Comment by Koukyosyumei** [comment]
@madhavajay 
Hi,
I replaced "name" with "tag", and all of my notebooks worked. I also implemented "dry_run", so every notebook runs only one batch!

**Comment by madhavajay** [comment]
@Koukyosyumei thank you, I was mid-review on these and got interrupted by some other tasks. Both notebooks worked and I was able to see output:
fake_samples_0_936
output2

Let me get these merged first and then we can discuss how to turn them into an integration test.
Sorry for the wait, I really appreciate your patience.

**Comment by madhavajay** [comment]
@Koukyosyumei Also if you DM me on Slack I can help explain the Integration Test stuff.

**Comment by Koukyosyumei** [comment]
@madhavajay 
Thank you for your support! Please merge first. I'll survey the integration test and dm you later!

**Review by madhavajay — APPROVED** [review]
@Koukyosyumei this was excellent work and is one of the best public contributor PRs iv seen in a while. Thank you very much! 🎉

**Pull request merged**
