### PR TITLE
fix: spdz_mul fails when values are shared between more than 2 workers

### PR DESCRIPTION
**Pull request by meandmymind**
To reproduce:
```python
import torch
import syft as sy
hook = sy.TorchHook(torch)

# Create > 2 workers
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
bill = sy.VirtualWorker(hook, id="bill")

# And share between them all
x = torch.tensor([25]).share(alice, bob, bill)
y = torch.tensor([5]).share(alice, bob, bill)

# Multiply tensors
(x * y).get()
```
Get TypeError
image

### CODE REVIEW

**Comment by meandmymind** [comment]
@iamtrask Yeah, of course. I'm a bit confused about which test cases should I update: `test_mul`, `test_public_mul`, `test_matmul`, `test_torch_dot` or all of them?

**Comment by iamtrask** [comment]
Probably best to just copy those test cases and add additional workers.

**Comment by iamtrask** [comment]
(meaning don't edit them - create new test cases based on them)

**Comment by meandmymind** [comment]
Actually, this is not the practice I see, as 3-worker case is usually added to the test function. Example
```python
def test_add(workers):
    bob, alice, james = (workers["bob"], workers["alice"], workers["james"])

    # 2 workers
    t = torch.tensor([1, 2, 3])
    x = torch.tensor([1, 2, 3]).share(bob, alice)

    y = (x + x).get()

    # 3 workers
    assert (y == (t + t)).all()

    t = torch.tensor([1, 2, 3])
    x = torch.tensor([1, 2, 3]).share(bob, alice, james)

    y = (x + x).get()
```

**Comment by robert-wagner** [comment]
Hey @meandmymind are you still working on this pull request? It looks like it is almost done

**Comment by meandmymind** [comment]
Hi @robert-wagner! Yeah I've completed tests.

I guess what @iamtrask have suggested is a good idea for another big PR — refactor all tests to check operations on 3+ worker shared tensors. I think it's beyond this PR.

**Pull request merged**
