### PR TITLE
Fix test_websocket_worker_multiple_output_response unit test

### PR DESCRIPTION
**Pull request by vvmnnnkv**
Added worker arg to exceptions' `simplify`

### CODE REVIEW

**Comment by gmuraru** [comment]
Could you please describe what is the problem?

**Comment by vvmnnnkv** [comment]
Note this is PR for branch https://github.com/OpenMined/PySyft/pull/2723 not master branch. In #2723, unit test test_websocket_worker_multiple_output_response doesn't pass. This PR fixes it.

**Comment by gmuraru** [comment]
Thank you!

**Comment by cereallarceny** [comment]
Merged @vvmnnnkv

**Pull request merged**
