### PR TITLE
Grid module architecture refactoring

### LINKED ISSUE #3153: [EPIC] Create PyGrid Client
### Context

Based on the [Federated Learning Roadmap](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md) (specifically in [Section 3 - Host](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md#3-host)), *"[...] The developer needs to connect to an existing PyGrid gateway and send the model, various worker plans and protocols, averaging plan, and various configurations to be stored in PyGrid properly."*

### Description

Having a PyGrid instance running, as specified, the developer needs to send all that data to the PyGrid using the grid library. The grid library no longer exists in PyGrid repository, it is now a PySyft module. So the interface used in the [example](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md#3-host) is no longer available.

So we need to create a grid client in this PySyft module. We would have the necessary methods, and these would use the endpoints that we implemented on the PyGrid side.

Something like:
```python
import syft.grid as gr

pygrid = gr.GridClient(
  hook,
  id="my-name",
  address="https://localhost:5000"
)

pygrid.connect()

pygrid.host_federated_training(
  model=model,
  client_plans={ "training_plan": training_plan },
  client_protocols={ "secure_agg_protocol": secure_aggregation_protocol },
  client_config=client_config,
  server_averaging_plan=averaging_plan,
  server_config=server_config
)
```

See the discussion at https://github.com/OpenMined/PyGrid/issues/435

### Functions
The client needs to implement the following functions

- `host_federated_training` - https://github.com/OpenMined/PyGrid/issues/435
- `get_model` - https://github.com/OpenMined/PyGrid/issues/436
- `get_plan`, `get_protocol` - https://github.com/OpenMined/PyGrid/issues/445

For additional information, see the [Federated Learning Roadmap](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/federated_learning.md).

#### Related Issues
https://github.com/OpenMined/PySyft/issues/2995
https://github.com/OpenMined/PyGrid/issues/435
https://github.com/OpenMined/PyGrid/issues/436
https://github.com/OpenMined/PyGrid/issues/445

### PR DESCRIPTION
**Pull request by hericlesme**
## Description

This pull request introduces changes to the `syft.grid` module architecture. 

In summary, this Pull Request includes:

- Separation of the old grid client into static_fl_worker and static_fl_client
- The addition of the missing methods and the proper semantic separation to close #3153
- Changes in the architecture of the grid module
- Deletion of `grid/authentication` folder

With these changes, the architecture of the module will be:

```
/grid
├── abstract_grid.py
├── /admin
│   └── __init__.py
├── /clients
│   ├── dynamic_fl_client.py
│   └── static_fl_client.py
├── exceptions.py
├── __init__.py
├── private_grid.py
├── public_grid.py
├── /rtc
│   ├── network.py
│   ├── nodes_manager.py
│   ├── peer_events.py
│   └── webrtc_connection.py
└── /utils
    ├── /autoscale
    │   ├── gcloud.py
    │   ├── README.md
    │   ├── test.ipynb
    │   ├── test.py
    │   └── /utils
    │       ├── gcloud_configurations.py
    │       ├── /notebook
    │       │   └── terraform_notebook.py
    │       └── /script
    │           └── terraform_script.py
    └── __init__.py

```

As described in [this section of the dynamic federated learning roadmap](https://github.com/OpenMined/Roadmap/blob/master/web_and_mobile_team/projects/dynamic_federated_learning.md#reorganization-2), as part of this refactoring has been included:
- Move node_client (dynamic FL) to grid folder and rename as `dynamic_fl_client` (DynamicFLClient)
- Rename grid_client (static FL) as `static_fl_client` (StaticFLClient)
- Move the static FL worker in PySyft out of the grid folder, put it in the `workers` folder, and rename it static_fl_worker (StaticFLWorker)

**_Note: a small modification has been made to the points above. Clients are now in the `syft/grid/clients` folder_**

### :warning: Warning
As it is about changes and renames in sub-modules and classes, this PR requires changes in the documentation and tutorials and existing notebooks that make use of this sub-module.

## How has this been tested?
- Existing tests

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by hericlesme** [comment]
**Question:** Should documentation updates be mandatory for this pull request to be merged? That way we avoid conflicts or confusion for those who try to use the grid module or node client from the master branch.

**Comment by cereallarceny** [comment]
Good point @hericlesme. Yes, I should think we need to merge docs changes with this PR. Go ahead and do that first and submit any of those PR’s to me for merging.

**Comment by jmaunon** [comment]
looks very nice, much clearer

**Comment by hericlesme** [comment]
@cereallarceny ready!

**Pull request merged**
