### PR TITLE
Notebook 7 hindi translation

### PR DESCRIPTION
**Pull request by raheja**
@Yugandhartripathi can you please review, and if it passes reviewal @karlhigley could you please merge it ?

Thanks!

### CODE REVIEW

**Comment by karlhigley** [comment]
Happy to merge once reviewed. We're having some trouble with the notebook tests for the translations though, so merging might be blocked for a little bit while we sort that out.

**Comment by ucalyptus** [comment]
@Yugandhartripathi  in the same boat for #3052 and #3053

**Comment by Yugandhartripathi** [comment]
@ucalyptus sorry I don't know Bengali. I did skim through it and requested some markdown changes.

**Comment by ucalyptus** [comment]
Sure. I requested review only from Karl and sourav.

**Comment by karlhigley** [comment]
Sorry for the delays, working on resolving notebook test issue.

**Comment by raheja** [comment]
> Sorry for the delays, working on resolving notebook test issue.

thank you so much @karlhigley

**Pull request merged**
