### PR TITLE
added dict support

### LINKED ISSUE #4515: Full primitive support in syft 0.3.0
## Description
We need extensive support and documentation on how to wrap and use the primitive types properly in a remote context in 0.3.0. I'll describe down below the process of doing this. To be sure that our types are working properly, we will use the interpreter tests on our syft types.

## Breakdown

- [x]  `syft.lib.python.int.Int`
  - [x]  subclass: subclass the `int` primitive and add an id to them.
  - [x]  `int` API available - make all methods that are available for `int` available for `Int` as well
  - [x]  immutable operators that preserve the ID (eg. __iadd__)
  - [x]  get the interpreter [tests](https://github.com/python/cpython/tree/3.8/Lib/test) for `int` and run them for `Int`
  - [x]  id tests added
  - [x]  test unary operators
  - [x]  test binary operators against all other types. be sure that they behave like their wrapped type

- [x]  `syft.lib.python.float.Float`
  - [x]  subclass the `float` primitive and add an uid to the object.
  - [x]  `float` API available - make all methods that are available for `float` available for `Float` as well
  - [x]  immutable operators that preserve the ID (eg. __iadd__)
  - [x]  get the interpreter [tests](https://github.com/python/cpython/tree/3.8/Lib/test) for `float` and run them for `Float`
  - [x]  id tests added
  - [x]  test unary operators
  - [x]  test binary operators against all other types. be sure that they behave like their wrapped type

- [x]  `syft.lib.python.none.None`
  - [x]  brainstorming still needed

- [x]  `syft.lib.python.string.String`
  - [x]  subclass the `UserStr` class and add an uid to the object.
  - [x] `str` API available - make all methods that are available for `str` available for `String` as well
  - [x]  immutable operators that preserve the ID (not sure if needed here)
  - [x]  get the interpreter [tests](https://github.com/python/cpython/tree/3.8/Lib/test) for `str` and run them for `String`
  - [x]  test unary operators
  - [x]  test binary operators against all our types

- [x]  `syft.lib.python.list.List`
  - [x]  subclass the `UserList` class and add an uid to the object.
  - [x]  `list` API available - make all methods that are available for `list` available for `List` as well
  - [x]  immutable operators that preserve the ID (not sure if needed here)
  - [x]  get the interpreter [tests](https://github.com/python/cpython/tree/3.8/Lib/test) for `list` and run them for `List`
  - [x]  test unary operators
  - [x]  test binary operators against all our types

- [x]  `syft.lib.pyton.dict.Dict`
  - [x]  subclass the `UserDict` class and add an uid to the object.
  - [x]  `dict` API available - make all methods that are available for `dict` available for `Dict` as well
  - [x]  immutable operators that preserve the ID (not sure if needed here)
  - [x]  get the interpreter [tests](https://github.com/python/cpython/tree/3.8/Lib/test) for `dict` and run them for `Dict`
  - [x]  test unary operators
  - [x]  test binary operators against all our types

- [x]  Pointers:
  - [x]  generate pointers (and proper serde) for all the classes defined above.
  - [x]  test them in a remote context.

- [ ]  Test our types against torch and numpy as well. Except of `None` and `bool` there should be no difference.

- [x]  Profit.

### PR DESCRIPTION
**Pull request by aanurraj**
## Description

- added dict 
this PR partially closes #4515 

## Affected Dependencies
none

## How has this been tested?
no tests added yet

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
Wow, awesome work. ❤️ I pulled down the PR to see why its failing and ran the pre_commit script we use to locally check everything that also runs in CI. The main difference with CI is there are some slow tests we don't run in pre_commit.sh so that its easy to get quick feedback that your code lint checks and the basic tests pass. This definitely needs to be documented better so sorry about that.
```sh
$ scripts/pre_commit.sh
```

> src/syft/lib/python/dict.py:93: error: Argument 4 of "construct_new_object" is incompatible with supertype "StorableObject"; supertype defines the argument type as "Optional[List[str]]"
src/syft/lib/python/dict.py:93: note: This violates the Liskov substitution principle

Fixing this and the required imports, seemed to get the checks to pass locally.
```diff
# dict.py
-        tags: Optional[TypeDict[str, str]],
+        tags: Optional[List[str]],
```

For these Primitive Wrapping types we have been copying the official python tests for the parent type and using that to ensure our subclass works as expected.

You can see an example for List in `/tests/syft/lib/python/list/list_test.py`.

My guess is this is the correct one for Mapping / Dicts:
https://github.com/python/cpython/blob/3.8/Lib/test/mapping_tests.py

If the tests fail on one of the earlier versions of Python, such as python 3.7 or python 3.6 which are in our Test Matrix, it could be that there was a change added to the tests to prevent regression, so you can check the history and figure out which test was added for which version.
https://github.com/python/cpython/commits/3.8/Lib/test/mapping_tests.py

You can see an example of that in our copy of `float_test.py`:
```python
# using __index__ in init was added in python 3.8
# https://github.com/python/cpython/commit/bdbad71b9def0b86433de12cecca022eee91bd9f
if sys.version_info >= (3, 8):

    class MyIndex:
        def __init__(self, value):
            self.value = value

        def __index__(self):
            return self.value

    assert Float(MyIndex(42)) == 42.0
    with pytest.raises(OverflowError):
        Float(MyIndex(2 ** 2000))
```

**Comment by aanurraj** [comment]
> Wow, awesome work. ❤️ I pulled down the PR to see why its failing and ran the pre_commit script we use to locally check everything that also runs in CI. The main difference with CI is there are some slow tests we don't run in pre_commit.sh so that its easy to get quick feedback that your code lint checks and the basic tests pass. This definitely needs to be documented better so sorry about that.
> 
> ```shell
> $ scripts/pre_commit.sh
> ```
> 
> > src/syft/lib/python/dict.py:93: error: Argument 4 of "construct_new_object" is incompatible with supertype "StorableObject"; supertype defines the argument type as "Optional[List[str]]"
> > src/syft/lib/python/dict.py:93: note: This violates the Liskov substitution principle
> 
> Fixing this and the required imports, seemed to get the checks to pass locally.
> 
> ```diff
> # dict.py
> -        tags: Optional[TypeDict[str, str]],
> +        tags: Optional[List[str]],
> ```
> 
> For these Primitive Wrapping types we have been copying the official python tests for the parent type and using that to ensure our subclass works as expected.
> 
> You can see an example for List in `/tests/syft/lib/python/list/list_test.py`.
> 
> My guess is this is the correct one for Mapping / Dicts:
> https://github.com/python/cpython/blob/3.8/Lib/test/mapping_tests.py
> 
> If the tests fail on one of the earlier versions of Python, such as python 3.7 or python 3.6 which are in our Test Matrix, it could be that there was a change added to the tests to prevent regression, so you can check the history and figure out which test was added for which version.
> https://github.com/python/cpython/commits/3.8/Lib/test/mapping_tests.py
> 
> You can see an example of that in our copy of `float_test.py`:
> 
> ```python
> # using __index__ in init was added in python 3.8
> # https://github.com/python/cpython/commit/bdbad71b9def0b86433de12cecca022eee91bd9f
> if sys.version_info >= (3, 8):
> 
>     class MyIndex:
>         def __init__(self, value):
>             self.value = value
> 
>         def __index__(self):
>             return self.value
> 
>     assert Float(MyIndex(42)) == 42.0
>     with pytest.raises(OverflowError):
>         Float(MyIndex(2 ** 2000))
> ```

done thanks :)

**Comment by madhavajay** [comment]
@aanurraj Thanks for starting this, I have added a PR here: https://github.com/OpenMined/PySyft/pull/4589 to this PR. You can merge this into your branch or merge my PR and close this, either way.

**Comment by aanurraj** [comment]
> @aanurraj Thanks for starting this, I have added a PR here: #4589 to this PR. You can merge this into your branch or merge my PR and close this, either way.

thankyou :) closing this PR

**Pull request closed without merging**
