### PR TITLE
Added scripts, graphs for benchmarking AST operations

### LINKED ISSUE #4000: Benchmark AST operations
## What?
Benchmark the ```AST``` operations using the already existing implemented protocols (```fss``` and ```snn```) - some of them might be ```relu```, ```conv2d```, ```batchnorm```.

A good idea for a more real-life scenario would be to use ```GridNodes``` from [PyGrid](https://github.com/OpenMined/PyGrid)
But, we can start with ```VirtualWorkers``` and then move to the Grid.

The final output should be a graph or graphs (png images) where:
* X-axis - the used precision for the ```FPT```
* Y-axis - the time to compute the operation

We can have multiple lines, each one representing an approximation method.

Some more possibilities:
* Y-axis (or Y2-Axis) - delta (difference) between the values - our method vs the one implemented in ```torch```
* X-axis - number of iterations used for the Chebyshev or the number of terms

See the [Epic](https://github.com/OpenMined/PySyft/issues/3997) to check more details regarding where to place the graphs.

### PR DESCRIPTION
**Pull request by aanurraj**
## Description
Scripts and Graphs are added for benchmarking AST operation based on two currently available protocols (fss, snn).
currently added scripts and graphs are added for:-

- [x] share_get

- [x] max_pool2d

- [x] avg_pool2d

- [x] batch_norm

Improvement suggestions are welcomed :) 

This PR Partially fixes #4000 

## Affected Dependencies
None

## How has this been tested?
- This addition doest requires an additional test but an average of 10 timestamps have been computed to get an accurate result.
- Benchmark graphs may be different for different system specifications on which the scripts are run though they should show a similar trend. 
## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by marload** [comment]
Could you resolve conflict?

**Comment by aanurraj** [comment]
> Could you resolve conflict?

done :)

**Comment by iamtrask** [comment]
This is a very nice contribution!

**Comment by aanurraj** [comment]
> This is a very nice contribution!

Thanks, it really feels amazing to get this from you!

**Review by marload — APPROVED** [review]
LGTM 🔥

**Pull request merged**
