### PR TITLE
Improve secrets loading and tox, CI support for Bigquery Scenario

### PR DESCRIPTION
**Pull request by snwagh**
Adding 
- Tox to test the BigQuery scenario notebooks
  - Added schema endpoint testing in notebook
- Improve existing mechanism to load secrets to importing from env variables
  -  Using dotenv framework to save and load variables
  - Service account env variables are json encoded in base64 and automatically decoded
  
Works on part of https://github.com/OpenMined/Heartbeat/issues/1763

Thanks @madhavajay @IonesioJunior @shubham3121 and @bitsofsteve ! 

Screenshot 2024-08-23 at 11 22 02 AM

### CODE REVIEW

**Review by IonesioJunior — APPROVED** [review]
LGTM! Amazing work @snwagh !

**Review by BrendanSchell — COMMENTED** [review]
Are we missing the config file for the tests? Trying to run and get this error `FAILED scenarios/bigquery/02-configure-api.ipynb:: - AttributeError: 'Settings' object has no attribute 'GCE_SERVICE_ACCOUNT'`.

**Comment by IonesioJunior** [comment]
> Are we missing the config file for the tests? Trying to run and get this error `FAILED scenarios/bigquery/02-configure-api.ipynb:: - AttributeError: 'Settings' object has no attribute 'GCE_SERVICE_ACCOUNT'`.

From what I could understand, the config file contains secrets, such as BQ credentials, so it's expected to be shared in a different channel.

**Comment by madhavajay** [comment]
Closes: https://github.com/OpenMined/Heartbeat/issues/1763

**Comment by madhavajay** [comment]
> Are we missing the config file for the tests? Trying to run and get this error `FAILED scenarios/bigquery/02-configure-api.ipynb:: - AttributeError: 'Settings' object has no attribute 'GCE_SERVICE_ACCOUNT'`.

@BrendanSchell yup its in slack, we should move this to something like 1password or another tool when we get some time

**Review by madhavajay — APPROVED** [review]
So good. ❤️

Great work @snwagh!! 👏👏👏

**Pull request merged**
