### PR TITLE
support torch 1.8.0

### PR DESCRIPTION
**Pull request by xutongye**
## Description
This PR is based on #5265 .

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by gmuraru** [comment]
Hello @xutongye !
Great job!

Could you also add in the ```requirements.torch.txt``` and ```setup.cfg``` to take ```torch 1.8``` into consideration now.
Also, could you add the latest version of ```opacus``` (in the ```supported_libs.txt``` file) -- because it was needing ```torch 1.8```

**Comment by madhavajay** [comment]
> Hello @xutongye !
> Great job!
> 
> Could you also add in the `requirements.torch.txt` and `setup.cfg` to take `torch 1.8` into consideration now.
> Also, could you add the latest version of `opacus` (in the `supported_libs.txt` file) -- because it was needing `torch 1.8`

I think all of the torch==1.8.0 and python 3.9 requirements were taken care of in the linked PR which was merged, so this is just adding new functionality that 1.8.0 provides.

**Review by gmuraru — APPROVED** [review]
LGTM!

**Comment by madhavajay** [comment]
I have added the commented out op `torch.broadcast_shapes` here: https://github.com/OpenMined/PySyft/issues/5184

**Pull request merged**
