### PR TITLE
Implemented default numpy functionality for BaseTensor Object#79

### PR DESCRIPTION
**Pull request by sajalsubodh22**
1. added function numpy() in tensor.py that casts BaseTensor type to np.ndarray()
2. added unittest for numpy with class name numpyTests in test_tensor.py

### CODE REVIEW

**Comment by bartimaeus12** [comment]
@sajalsubodh22  your identation in tensor.py is wrong.(line 433)

**Comment by sajalsubodh22** [comment]
whats the issue now? i am not able to understand
@bartimaeus12

**Comment by sajalsubodh22** [comment]
@iamtrask @bartimaeus12 Please review. I'll make the changes as you suggest.

**Comment by erfannoury** [comment]
I'm against the `numpy` for the function. I can see situations that this will cause conflicts with the main numpy package. I think `to_numpy` would be a better name.

**Comment by sajalsubodh22** [comment]
There were already many implementations of already existing functions like abs() etc. Still i'll correct it.

**Comment by sajalsubodh22** [comment]
@iamtrask what issues are coming up on merging numpy_func to develop??

**Pull request closed without merging**
