### PR TITLE
Use `DictTuple(tuple)` for `Dataset.assets` and `SyftClient.datasets` instead of `TupleDict(OrderedDict)`

### PR DESCRIPTION
**Pull request by kiendang**
## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@kiendang interesting. Lets discuss in the Eng channel in slack.

**Comment by madhavajay** [comment]
@kiendang great work, I had a play and found a possible bug.

It seems if the keys are ints and non 0 sequential it freaks out on casting to a dict.
Screenshot 2023-10-23 at 3 46 33 pm

**Review by madhavajay — CHANGES_REQUESTED** [review]
Great work. The feel of using this is nice when indexing with both string or int keys.

Its a little complex to understand at first read and this kind of code often can hide bugs because its so complicated but the tests definitely help. Can you fix the non zero sequential int keys issue I found and then I think we can merge it. 🙌

**Comment by kiendang** [comment]
@madhavajay Yah keys should not be `int`. If you have a `d: DictTuple` with `int` keys, now `d[2]` is ambiguous since it means both "getting the 3rd element" and "getting the element with key 2". I'll just put in a check, raising an error on attempting to create a `DictTuple` with `int` key.

You would encounter similar error with the current `TupleDict` too.

```python
p = TupleDict({1: "z", 2: "b"})
p[2]

File "/Users/kien/pysyft/packages/syft/src/syft/types/tupledict.py", line 14, in __getitem__
    return list(self.values())[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
```

> the tests definitely help

I have a more comprehensive test suite for this but is currently blocked by #8188 (without #8188 it is very slow). Will push that once it is resolved.

**Pull request merged**
