### PR TITLE
Deprecate load_lib() and rename to load()

### LINKED ISSUE #5273: Rename load_lib to load
## Description
- [x] Rename `sy.load_lib` to `sy.load`.
Leave old method but pass through to new method and add DeprecationWarning like here:
https://github.com/OpenMined/PySyft/blob/fb4f99028338d4e59fb702f1f6ec60f1e16bc660/src/syft/ast/klass.py#L322

- [x] Add test to `api/deprecated_test.py`
- [x] Look into auto loading libraries using a post import hook:
https://stackoverflow.com/questions/40623889/post-import-hooks-in-python-3
https://github.com/GrahamDumpleton/wrapt
https://www.youtube.com/watch?v=u7oj-ghfhUk
- [x] Update notebooks

## Definition of Done
`sy.load_lib` is deprecated but still functional and replaced with `sy.load`

### PR DESCRIPTION
**Pull request by avinsit123**
## Description

Closes #5273 

## Affected Dependencies
List any dependencies that are required for this change.

- [x] Rename `sy.load_lib()` to `sy.load()`
       Leave old method but pass through to new method and add DeprecationWarning 
- [x] Add test to `api/deprecated_test.py`
- [ ] Look into auto loading libraries using a post import hook:
- [x] Update notebooks

## How has this been tested?
- Using `pytest.deprecated_call()` in `api/deprecated_test.py`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by tudorcebere** [comment]
Hi @avinsit123 !

We introduced a few new CI tests and one of them is to document all new code. Do you think you could provide documentation for the written code in a Google style format?

Thank you!

**Comment by avinsit123** [comment]
@tudorcebere are you referring to darglint tests? If so, I will write the documentation in google format np

**Comment by avinsit123** [comment]
@tudorcebere @madhavajay Could u give an idea of where to use pre-import hooks here? I have read the tutorials mentioned in #5273

**Comment by gmuraru** [comment]
Don't forget to also make a PR in [SyMPC](https://github.com/OpenMined/SyMPC) with ```load_lib``` -> ```load```

**Comment by tudorcebere** [comment]
LGTM!

I think we should merge this as it is so we won't keep a PR open for too long and then you can work on autoloading?

Autoloading requires 2 steps:
* when importing a targeted library, we have an internal hook that knows about this and automatically calls load(library) so we install our stuff.
* when a party does some remote execution on another party and uses a library, auto load it if it's present, if not, return an error.

Autoloading is basically integrating somewhere the sy.load call so we don't need to call it by hand, but it's an open question on how to do that.

**Comment by avinsit123** [comment]
Ok fine pls review this PR and I will try to open a seperate one to solve the autoloading issue. Thanks

**Comment by avinsit123** [comment]
@tudorcebere @madhavajay could u review this work PR so that I can continue with autoloading and making appropriate changes in SyMPC.

**Review by gmuraru — APPROVED** [review]
LGTM!

**Comment by madhavajay** [comment]
@avinsit123 thanks for the PR. Are you interested in investigating the post import hook?

**Comment by avinsit123** [comment]
Yes @madhavajay I am willing to look into it. Tudor's comment above has given me a small idea on what we are aiming for

**Comment by madhavajay** [comment]
@avinsit123 Its okay, there are other issues to, but if you are interested then it would be a great addition.

**Pull request merged**
