### PR TITLE
Updated Hagrid to pull template from tags

### PR DESCRIPTION
**Pull request by rasswanth-s**
## Description
Currently, when we try to deploy beta versions in hagrid, it always deploys the latest version of hagrid.

This is due to the fact , that we try to point all our beta a releases , to our dev branch.

Since,we create tags for each beta releases, the PR aims to points each beta version to be deployed onto the specific tag/releases.

Depended on: https://github.com/OpenMined/PySyft/pull/8139

Resolves: https://github.com/OpenMined/Heartbeat/issues/756

This works from beta versions `>= 0.8.2-beta.34`

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Added screenshots

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by rasswanth-s** [comment]
Template downloading for each beta version.

Screenshot 2023-10-09 at 6 34 24 PM

**Comment by madhavajay** [comment]
@rasswanth-s works well for the beta tags I tried but it fails to deploy if a user chooses `latest`.

**Comment by rasswanth-s** [comment]
Tested with version 0.8.0
Screenshot 2023-10-10 at 11 31 35 AM
Syft Version
Screenshot 2023-10-10 at 11 32 22 AM

**Comment by rasswanth-s** [comment]
Tested with latest
Screenshot 2023-10-10 at 11 33 31 AM
Version:
Screenshot 2023-10-10 at 11 33 55 AM

**Comment by rasswanth-s** [comment]
Currently the stable beta is beta.35, the below screenshot deploys beta.34
Screenshot 2023-10-10 at 11 35 13 AM

Syft Version

Screenshot 2023-10-10 at 11 36 19 AM

**Review by madhavajay — APPROVED** [review]
@rasswanth-s great work! I tested this in both dev mode and built a wheel and installed it and it works for no tag, tag=latest, tag=beta, tag=0.8.2bX as expected.

🙏

**Pull request merged**
