### PR TITLE
Add quick note on how to run tests

### PR DESCRIPTION
**Pull request by swaroopch**

### CODE REVIEW

**Comment by samsontmr** [comment]
Perhaps add a note about which directory to run the command in?

**Comment by swaroopch** [comment]
It can be run from the top-level directory, so I wasn't sure how to word that. 

Should I say "cd PySyft; pytest"?

**Comment by iamtrask** [comment]
that works for me

**Comment by swaroopch** [comment]
@iamtrask Added a commit to add `cd PySyft`

**Pull request merged**
