### PR TITLE
feat(mv functionality)

### PR DESCRIPTION
**Pull request by aradhyamathur**
- mv implementation
- test for mv

### CODE REVIEW

**Comment by aradhyamathur** [comment]
with reference to https://github.com/OpenMined/PySyft/issues/69

**Comment by siarez** [comment]
@aradhyamathur Did you mean to change the .gitignore file as well? Or is it a mistake?

**Comment by aradhyamathur** [comment]
@siarez yes i changed it since i switched to pycharm

**Comment by siarez** [comment]
For local files that are specific to your development env. (e.g. files generated by your editor), the best practice is to use the git exclude file. check this out: [Git Exclude](https://help.github.com/articles/ignoring-files/#explicit-repository-excludes)

**Comment by aradhyamathur** [comment]
@siarez corrected it. Removed the .gitignore

**Comment by siarez** [comment]
The way you have implemented `mv`, it is not a method of the TensorBase class. In this case, should it can be implemented in math.py instead? 
@iamtrask what do you think?

**Comment by aradhyamathur** [comment]
I checked Pytorch's documentation, they have implemented it as a part of torch and not Tensor class. So I thought it will be better to follow similar convention. @siarez @iamtrask

**Comment by iamtrask** [comment]
When in doubt, follow PyTorch's conventions :)

**Comment by siarez** [comment]
In PyTorch most function are present in both `torch` and `torch.Tensors` (like `mv` here). We haven't followed that convention here. 
Are we in for a major change? How should things look like, if we were to make that change?

**Comment by aradhyamathur** [comment]
@siarez thanks for bringing that up. I have added the implementation to TensorBase as well I guess we are up to date with it now.

**Comment by siarez** [comment]
@aradhyamathur oh yes! that looks good to me. Now I'm wondering, should we do that for all other methods in TensorBase? @iamtrask what do you think?

**Comment by iamtrask** [comment]
@siarez I think the main question there is based on whether we need to do that to support PyTorch's autograd.

**Comment by iamtrask** [comment]
Example: http://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_autograd.html

**Comment by aradhyamathur** [comment]
The main role is played by the autograd functions and variable only it seems. Here they have actually explained how custom autograd functions can be created http://pytorch.org/tutorials/beginner/pytorch_with_examples.html#pytorch-defining-new-autograd-functions
The rest of tensor operations don't seem to be affected.

**Comment by siarez** [comment]
I spend sometime this morning looking at PyTorch's autograd trying to figure out how it relates to this. I couldn't figure it out :) Many of their functions leads to their C library and I didn't dig deep enough.
I guess we can leave everything else as is. We'll cross that bridge when we get there.

**Pull request merged**
