### PR TITLE
added hello-syft tutorial

### PR DESCRIPTION
**Pull request by znreza**
## Description
Added the hello-syft tutorial for Ziwi Peak project, covering Syft basics, and a complete workflow on a small dataset.

## Affected Dependencies
None

## How has this been tested?
- The tutorial is tested and validated by running the executable codes
- Added `assert` at important places

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by koenvanderveen** [comment]
I think the main purpose of this notebook is that people can run syft as quickly as possible. I really like the notebook and the explanations, but for this purpose it is a bit long. My proposal would be a to add a shorter version of this, kind of a TLDR. We could keep this longer version with explanations if people want to read more. We could split those up into 2 separate notebooks or have a tldr as first chapter.

**Comment by koenvanderveen** [comment]
Thinking about this again I think we can repurpose this PR as a high side low side tutorial for level 0, and have a much shorter version as hello syft tutorial

**Comment by znreza** [comment]
@koenvanderveen I see some changes were made by @akalliokoski in PR #7775 based on your feedback. Is there anything else that I can work on for this issue? Thanks!

**Comment by madhavajay** [comment]
Im going to close this now in favour of the existing one here: https://github.com/OpenMined/PySyft/pull/7775

**Pull request closed without merging**
