### PR TITLE
fix-pep8-tests

### LINKED ISSUE #119: Set up CI for automated testing and style checks
Now that our codebase is growing (hooray!), we should set up CI for automated testing and style checks (PEP8, PEP257). 

Choices include [CircleCI](https://circleci.com) and [TravisCI](https://travis-ci.org). These can be integrated into our repo such that every pull request will be checked before review.

### PR DESCRIPTION
**Pull request by cypherai**
Fixes #119

We got automatic pep8 style checks now 👍

### CODE REVIEW

**Comment by anoff** [comment]
> We got automatic pep8 style checks now 
and broken builds 🤣

jk, love the push towards enforcing tests & stylechecks

**Comment by bartimaeus12** [comment]
Is it possible to ignore E501 errors(either increase length limit or ignore it completely) as quite a few errors are of that type?

**Comment by anoff** [comment]
I guess something [like pycodestlye.py](https://stackoverflow.com/a/44049586) could work. Not an expert in python. However I also find rules enforcing line length limits pretty 90s. Every decent editor has auto-wrap functionality.

But it's up to @OpenMined/team-pysyft to decide on that :)

**Comment by cypherai** [comment]
@bartimaeus12 @anoff It is definitly possible.

The only thing to do is tune the `setup.cfg` file by adding:

```python
[pytest]
flake8-ignore = E501
```

We can even limit line length

```python
[pytest]
flake8-max-line-length = 99
```

If it's ok for everyone I can push another commit for this PR.

**Comment by iamtrask** [comment]
@cypherai good by me :)

**Comment by TheOriginalAlex** [comment]
@cypherai: This looks good to me, but I think it'd be cleaner to run different tests in separate containers like so:
```
docker run --rm pysyft pytest
docker run --rm  pysyft py.test --flake8
```

**Comment by TheOriginalAlex** [comment]
Also, I think we can get rid of the `Install dependencies` section since none of the dependencies are actually being used on the host.  The tests are gonna be run in the container.

**Comment by cypherai** [comment]
That ✅ looks just great

Thanks for the improvements @TheOriginalAlex and @iamtrask for the style corrections!

**Pull request merged**
