### PR TITLE
Flask server runs on IPV6

### PR DESCRIPTION
**Pull request by rajatrc1705**
## Description
Now the user has an option to run the flask server on IPV6 or IPV4 using an additional environment variable IP_MODE.
#4527 

## Affected Dependencies
None

## How has this been tested?

For IPV4, user simply has to launch the Flask server like following:
`syft-network`
image

For IPV6, user has to give an additional parameter:
`syft-network IPV6`
image

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by rajatrc1705** [comment]
pre_commit.sh keeps throwing an error everytime I try to use it, so there might be some linting problems.
Also, I would like to know how I can edit the 'syft-network' binary file, this is how my 'syft-network' binary file looks after editing in my local machine:
image
Once these changes are implemented, then the PR is complete.

**Comment by madhavajay** [comment]
@rajatrc1705 what is the issue with `pre_commit.sh`? It would be great to know so we can fix it.

**Comment by rajatrc1705** [comment]
image
Am I running it wrong?

**Comment by rajatrc1705** [comment]
image

**Comment by madhavajay** [comment]
Hi @rajatrc1705 you need to run it from the main dir:
```
$ scripts/pre_commit.sh
```

It also looks like you don't have some of the dependencies like bandit so you will need to run:
```
$ pip install -r requirements.txt
```

To build the protos you will also need an up to date version of `protoc`.
There are some instructions in the CONTRIBUTING guide: https://github.com/OpenMined/PySyft/blob/dev/CONTRIBUTING.md 

However updated instructions for other platforms are needed so if you want to add Ubuntu or Linux that would be greatly appreciated.

**Comment by rajatrc1705** [comment]
Now the PR seems complete, the code is working all right on my machine.
image

**Review by madhavajay — APPROVED** [review]
Looks good. I made a few small improvements and added the instructions to the README.md. Great work! ❤️

**Pull request merged**
