### PR TITLE
add spinner animation to hagrid launch

### LINKED ISSUE #6942: UX: Spinner Animation to Hagrid Launch
## Feature Description
Currently when silent flag is provided during launching of node through hagrid, progress bars are displayed to show 

- `Pull`
- `Build`
- `Launch`
 
of docker containers.When we initially try to launch in a new system without any cached packages these steps take a `lot of time.`
Since we cannot provide time estimation in the progress bars, we could replace the ⌛ emoji by a spinner animation of rich library.

Current loading part:
Screenshot 2022-11-03 at 9 45 39 AM

Spinner animation example:
https://www.npmjs.com/package/cli-spinners

Reference to solve the issue.
https://rich.readthedocs.io/en/stable/progress.html

We could a spinner column to the rich progress in folder
`packages/hagrid/hagrid/cli.py` in `execute_commands` functions
https://github.com/OpenMined/PySyft/blob/5de360b9fc4cff81dda76bd0a35af7c0167554c4/packages/hagrid/hagrid/cli.py#L597

This is mainly to show new users that the thread is not frozen and it is still working as it takes time.

### PR DESCRIPTION
**Pull request by bipinKrishnan**
## Description
Adds [SpinnerColumn](https://rich.readthedocs.io/en/stable/reference/progress.html#rich.progress.SpinnerColumn) animation to progress bars shown while launching hagrid(resolves #6942).
## Affected Dependencies
None

## How has this been tested?
None

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by rasswanth-s** [comment]
I tried the running the updated code, the progress bar is not visible, maybe it would good to also have the progress bar visible also with spinner animation.
Screenshot 2022-11-07 at 10 56 15 AM

**Comment by bipinKrishnan** [comment]
Made the appropriate changes and as of now this is how it looks:
Screenshot from 2022-11-07 20-39-23

**Review by IonesioJunior — APPROVED** [review]
Clean modifications in a very nested piece of our codebase. Awesome work @bipinKrishnan! Looking forward to merging it. 😃

**Comment by rasswanth-s** [comment]
Wonderful, Great Work @bipinKrishnan

**Comment by bipinKrishnan** [comment]
Cool, thanks for the quick review and feedback everyone :heart:.

**Pull request merged**
