### PR TITLE
In-place ceiling, and associated test

### PR DESCRIPTION
**Pull request by EdwardDixon**
I think ceil_ used to be there, but vanished somehow? Anyway, it is back with the associated test.  I took the chance to slighting enhance the test for ceil.

### CODE REVIEW

**Comment by iamtrask** [comment]
@EdwardDixon same as the other ticket :)

**Comment by EdwardDixon** [comment]
Sorry about that.  I've learned how to check locally with Flake8 before I push, and figured out enough of the Circle ui to read errors for myself.  Perhaps there is a way to get it to send me notifications when a build fails, though?

**Comment by EdwardDixon** [comment]
Phew!  Merge issues fixed at last, and got an extra fix in there also.  Hope we can get this in soon, or I'll likely have a fresh bunch of merge issues.

**Comment by kevinahuber** [comment]
@EdwardDixon merge away! Bonus points if you rebase and get rid of some of those one liners.

**Comment by EdwardDixon** [comment]
@kevinahuber Would love to, but I don't have write access for the repo (my first pull request that got approved).

**Pull request merged**
