### PR TITLE
Support Python <3.8 #3826

### PR DESCRIPTION
**Pull request by madhavajay**
## Description
This PR fixes some minor flake8 issues re-introduced allowing CI to pass, and adds support for both Python 3.7 and Python 3.6 with minimal changes.

The issue was discussed here:
https://github.com/OpenMined/PySyft/issues/3826

Changes required for each version are separated into their own commits.

## Affected Dependencies
None

## How has this been tested?
This has been tested on MacOS with Python 3.8.5, Python 3.7.8 and Python 3.6.11, and additionally GitHub Actions CI.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
I am a little confused why I needed to add this:
```
- name: Run tests with coverage
      run: |
+            pip install typing-extensions dataclasses
            python setup.py test

```

I would have thought that listing these packages in both the testing and install_requires inside setup.cfg would be sufficient?
On my local machine these needed to be installed with pip before the tests would work.

Here it kind of suggests that you have to still install them manually?
https://pyscaffold.org/en/latest/dependencies.html

*If run py.test runner, you will have to install those dependencies manually, or do a editable install of your package with pip install -e .[testing].*

Would be great if someone can clarify whats going on here.

**Comment by gmuraru** [comment]
Why do we need those changes in the new PySyft Version?

**Comment by madhavajay** [comment]
The reasoning for this change is that operating systems like Ubuntu LTS come with quite old python versions, so supporting 3.6 means Ubuntu 18.04+ should be covered out of the box.

I looked at going to python 3.5, but as Black is not supported (although its not actually needed for the library) and f"" strings are not supported either this seems like too much of a disruption at this stage, however its possible this may work without significant changes and provide support for Ubuntu 16.04 LTS and many other platforms stuck on python 3.5.

To achieve this the following changes were made:

## Python 3.7
- Imports referring to final and Final were changed to:
```
from typing_extensions import final, Final
```
See more here:
https://github.com/python/typing/tree/master/typing_extensions

## Python 3.6
- The dataclasses backport library was added without any changes to the code.
- `from __future__ import annotations` were removed:

From what I can see they are not being used as removal has not caused any issues.
The "annotations" future is only to delay parsing of types until after load, to prevent issues with referencing custom types in their own definitions. The workaround is to simply define them as strings "CustomType" when referring with in a type definition, however if this becomes cumbersome to support, python 3.6 could be dropped.

See more here:
https://www.python.org/dev/peps/pep-0563/#dropping-annotations-with-o

I would say both of these changes are extremely minor at this stage, but we could choose to only support Python 3.7.

I am happy to incorporate any feedback in this PR, or close without merging if these changes are unacceptable.

**Comment by madhavajay** [comment]
> Why do we need those changes in the new PySyft Version?

It was an open 0.3.0 issue:
https://github.com/OpenMined/PySyft/issues/3826

It seems that perhaps support for 3.6 and 3.7 isn't actually incompatible with the usage of new Python typing constructs.

**Comment by iamtrask** [comment]
> I am a little confused why I needed to add this:
> 
> ```
> - name: Run tests with coverage
>       run: |
> +            pip install typing-extensions dataclasses
>             python setup.py test
> ```
> 
> I would have thought that listing these packages in both the testing and install_requires inside setup.cfg would be sufficient?
> On my local machine these needed to be installed with pip before the tests would work.
> 
> Here it kind of suggests that you have to still install them manually?
> https://pyscaffold.org/en/latest/dependencies.html
> 
> _If run py.test runner, you will have to install those dependencies manually, or do a editable install of your package with pip install -e .[testing]._
> 
> Would be great if someone can clarify whats going on here.

I can't explain why it works this way but I have come to this understanding as well.

**Pull request merged**
