### PR TITLE
feat(view and view_as functions)

### PR DESCRIPTION
**Pull request by aradhyamathur**
- view function added to tensor
- view_as function added
- tests for view functions added

### CODE REVIEW

**Comment by kevinahuber** [comment]
@anoff or @swaroopch, can you take a look at this?

**Comment by radicalrafi** [comment]
The. Implementation is clean and simple using np. copy was smart

**Comment by aradhyamathur** [comment]
@radicalrafi  can you please look into this what might have caused this error ? :(

**Comment by aradhyamathur** [comment]
@radicalrafi  it seems permission for rebuild are not available. I have setup the ssh and cloned again though

**Comment by radicalrafi** [comment]
I didn't receive Notifications about this thread... Sorry

**Pull request merged**
