### PR TITLE
Function div implementation for autograd

### LINKED ISSUE #2336: Add div support of autograd Tensor
We have add sub mul but not div yet implemented for autogradtensor

### PR DESCRIPTION
**Pull request by wagnernegrao**
add div closes #2336

### CODE REVIEW

**Comment by wagnernegrao** [comment]
I'll do it.

**Comment by mari-linhares** [comment]
@wagnernegrao what is the status of this PR?

**Comment by murarugeorgec** [comment]
@wagnernegrao are you still working at this? I can try to pick this up and add the pytest.

**Comment by iamtrask** [comment]
I'm going to close this due to inactivity. This is, however, an extremely important PR and I do hope you or @gmuraru will pick it up!

**Comment by gmuraru** [comment]
This was already done [here] (https://github.com/OpenMined/PySyft/commit/81c17b7198af3ec90991d6feeb6482d2f2d220fa) (I think)

**Pull request closed without merging**
