### PR TITLE
fix: fix playwright installation in tox.ini

### PR DESCRIPTION
**Pull request by tcp**
## Description
Fix issue with Playwright not installing browsers on every workflow run.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)

### CODE REVIEW

**Review by rasswanth-s — APPROVED** [review]
🚀

**Comment by rasswanth-s** [comment]
@tcp  I have re-enabled the playwright tests and pushed a commit, I am not fully sure, why it is failing again

**Comment by tcp** [comment]
> @tcp I have re-enabled the playwright tests and pushed a commit, I am not fully sure, why it is failing again

**Review by rasswanth-s — APPROVED** [review]
Well Done @tcp 🎸

**Pull request merged**
