### PR TITLE
Docker + CI/CD support foundations

### PR DESCRIPTION
**Pull request by cypherai**
I propose a way to support Docker + CI/CD for PySyft, by creating a dedicated `/docker` directory.

I also created the basic config file for CI/CD, based on the [circleci](https://circleci.com) and [dockerhub](https://hub.docker.com) services. We'll need further setup to make it work, feel free to chat about it on Slack.

I also move the demo notebooks directory within an `/example` directory and created a `/tests` directory to store all our tests. Does it sound reasonable as a good practice structure?

### CODE REVIEW

**Comment by TheOriginalAlex** [comment]
@cypherai: Please extend your Dockerfile off of openmined/syft, the Dockerfile in the root of the repo.  The image already has a prebuild syft in it.  All you'd have to do is install jupyter and then set CMD jupyter notebooks.

**Comment by TheOriginalAlex** [comment]
@iamtrask: Can we posibly publish the pysyft base image to Dockerhub?

**Comment by TheOriginalAlex** [comment]
@kevinahuber, @anoff: Can we possibly publish a pysyft base image to Dockerhub?

**Comment by anoff** [comment]
Yea sure, I suggest automated builds via dockerhub? Or do you prefer manual builds?

**Comment by TheOriginalAlex** [comment]
Automated builds works!  :)

**Comment by cypherai** [comment]
@TheOriginalAlex Done, I only kept the config file for circle CI 🙂

**Comment by iamtrask** [comment]
Given that automated build works and there seems to be concensus on functionality, i'm going to go ahead and merge.

**Pull request merged**
