### PR TITLE
Exclude soft-deleted datasets from get_all results

### PR DESCRIPTION
**Pull request by jcardonnet**
image

### CODE REVIEW

**Comment by khoaguin** [comment]
Hi @jcardonnet I am working on this feature in [this PR](https://github.com/OpenMined/PySyft/pull/9072) where the `get_all` end point of dataset service has the `include_deleted` flag which default to `False` but can be set to `True` to list the deleted datasets, and also improved repr html for deleted datasets so the DS can see some metadata of the deleted datasets. I think this way we make use of the soft delete feature better in my opinion. Please check out the PR for screenshots

**Review by IonesioJunior — APPROVED** [review]
LGTM

**Comment by IonesioJunior** [comment]
Hi @khoaguin ,

Seems like your PR  is more robust and covers other issues too, which I think is near to the ideal solution for the whole dataset deletion problem. For now, I'll merge this specific fix to resolve a small but critical issue that needs to be addressed before our next release.

Please feel free to continue developing in this direction. If you need any assistance with reviews or development, don't hesitate to reach out. =)

**Comment by khoaguin** [comment]
Thanks @IonesioJunior. This sounds good

**Pull request merged**
