### PR TITLE
Introducing hagrid quickstart

### LINKED ISSUE #6604: Hagrid command
## Feature Description
`hagrid quickstart` or similar command that does all setup and works as a beautiful quickstart command for first-timer and beginners as suggested by @madhavajay.

## Is your feature request related to a problem?
This would work perfectly for first-timers as well as the planned "Quickstart" section in the readme.

## Additional Context
I would love to co-work on this with you and would be incorporating a GIF out of this for our README

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## Description
Closes #6604 and #6624 
Introduces a new CLI command that does 
- downloads the dependencies, 
- sets up the virtual env, 
- installs syft in editable mode
- downloads a jupyter notebook from our GitHub repo (kept as the RemoteDataScienceCourse for now)
- installs and boots up jupyter labs
- opens the notebook with everything set up above

All of this using a simple, `hagrid quickstart`

Additionally, pass a URL and fetch a new notebook like:
```
hagrid quickstart https://raw.githubusercontent.com/OpenMined/PySyft/dev/notebooks/mock-notebooks/login/User%20Registration.ipynb`
```

This will install the notebook and open the jupyter lab for the same.

PS: Will replace the "spaces" with an "_" in the file names.

Another feather in the hat is that if the command has already been run once, it will not fetch and overwrite the new notebook but will open the pre-existing one. Meaning, saving the user's work.

There are a ton of features that I have ideas for which I shall be implementing in various smaller separate issues and PRs.

## Affected Dependencies
from virtualenvapi.manage import VirtualEnvironment

## Way to test
- cd into `packages/hagrid/hagrid`
- Run `pip install -e .`
- Boom, you're gtg! run `hagrid quickstart` and you should see the magic underway
- Another Boom, run `hagrid quickstart <url>` and you should see your custom notebook downloaded and loaded

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
@madhavajay Have added the url functionality too! PTAL

**Comment by ShubhamPalriwala** [comment]
Updated `hagrid quickstart`:

## Command:
```
hagrid quickstart
```
### What it does:
- Downloads deps and sample notebook and opens it in a jupyter notebook
- If the `quickstart/` dir already exists, will skip downloading deps and open up the dir
- If a notebook already exists in the directory, will directly open the same up 

## Command:
```
hagrid quickstart <url-to-notebook>
```
### What it does:
- Downloads and opens the notebook if it doesn't exist
- If it already exists, prompt the user if they are sure they want to overwrite it with a y/N

## Command:
```
hagrid quickstart --reset
```
### What it does:
- Prompts the user for confirmation of what they are about to do
- Deletes the existing virtual envs and notebooks in the same dir and create an entirely new setup, ie fresh deps and a sample notebook, unless URL is provided


PS: The code has also been modularised now with the main division into two parts ie setup and run, and further micro functions to perform checks and independent commands.

**Comment by madhavajay** [comment]
@ShubhamPalriwala legendary! 🙌🏽

**Comment by Kiaka007** [comment]
@ShubhamPalriwala amazing!!!!!!

**Pull request merged**
