### PR TITLE
Refactor primitive pointer tests

### LINKED ISSUE #5399: Primitive Pointer tests refactor
## Description
In `tests/syft/lib/python/*/pointer_test.py` we are testing that pointers behave like they should when working with primitive types. That's a lot of duplicate code, less code means fewer bugs, we would like to move these tests in `tests/syft/core/pointer` without any duplicate code. Bonus points if you add new types to these tests like torch data types, slices, etc.

### PR DESCRIPTION
**Pull request by stoic-signs**
## Description
Refactoring pointer tests in `tests/syft/lib/python/*/pointer_test.py` when working with primitive types. Removing duplicate code to be able to move these tests in `tests/syft/core/pointer`. This PR closes #5399 .

## Affected Dependencies
No dependencies affected.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by arpitvaghela** [comment]
Hey @stoic-signs, can u add me as a collaborator ? I have certain ideas to merge the test together

**Comment by stoic-signs** [comment]
Hey @arpitvaghela, I think you should be able to send a PR to the repo. I can create a new branch and merge the two once the maintainers have had a chance to look at it.

**Comment by stoic-signs** [comment]
@tudorcebere Please have a look at the completed PR.

**Review by tudorcebere — APPROVED** [review]
Awesome work! Nice job!

**Pull request merged**
