### PR TITLE
Add Bengali Translated Notebooks #Part 9

### PR DESCRIPTION
**Pull request by adventuroussrv**
Translated Notebook:

Part 09 - Intro to Encrypted Programs.ipynb

### CODE REVIEW

**Comment by ucalyptus** [comment]
@adventuroussrv @karlhigley any insights on why the tutorials CI is failing for all PRs related to translations?
Close look at the CI trace suggests pytest errors.

**Comment by karlhigley** [comment]
The translation test suite is now taking too long again after so many translations have been added. It probably needs to be split apart into separate actions per language.

**Comment by karlhigley** [comment]
@ucalyptus Translation test issues seem to be resolved. Could you give this a review?

**Comment by ucalyptus** [comment]
@adventuroussrv request a review from me and karl . same for #3049

**Comment by adventuroussrv** [comment]
Hi @ucalyptus! You are already requested to review the PR #3049 by Karl!

**Comment by adventuroussrv** [comment]
Thanks for the review @ucalyptus :)

**Comment by adventuroussrv** [comment]
Yaaaaaaay! Thanks a lot @karlhigley :tada:

**Pull request merged**
