### PR TITLE
[WIP] Add Federated Learning and Differential Privacy demos

### LINKED ISSUE #1556: Combine Differential Privacy Demos with Federated Learning with Secure Aggregation Demo
We currently have two demos for differential privacy and one with secure aggregation. In a real world setting, we would want to be able to train these at the same time. In this issue, we would like to create TWO new demos.

1) by combining [this Differential Privacy demo](https://colab.research.google.com/drive/1k2TtOJSKSfuvcVLPILAtnh34lFhuUs45) with [this Federated Learning with Secure Aggregation demo](https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training%20with%20Secure%20Aggregation.ipynb)

2) by combining [this Differential Privacy demo](https://github.com/OpenMined/PySyft/blob/master/syft/differential_privacy/PATE_example_with_pytorch.ipynb) with [this Federated Learning with Secure Aggregation demo](https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training%20with%20Secure%20Aggregation.ipynb)

### PR DESCRIPTION
**Pull request by mukul-rathi**
# Description

Adding demos combining Differential Privacy and Federated Learning 

Fixes #1556 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Not yet **(WIP)**

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* CPU:
* GPU:
* PySyft Version:
* Unity Version:
* OpenMined Unity App Version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mukul-rathi** [comment]
This is the WIP PR - so far I've taken the code from the Boston Housing Dataset Federated learning and Differential Privacy demos and put them into a single IPython Notebook.  There is still some code that needs to be combined in the train method.

**Comment by iamtrask** [comment]
SUPER excited to see this coming together!!!

**Comment by mukul-rathi** [comment]
I think there may be a bug in model.send(worker)? Since there is a key error in workers._objects() when I run the forward prop step pred=model(data).
However, when I send the parameters of the model individually using param.send(worker) their ids are stored in workers._objects().keys() correctly so there is no key error in workers._objects() when I run the forward prop.

There is a key error in workers._objects() when the program then calls optimizer.zero_grad() on the same worker when the next lot is iterated through. Is there a corresponding optimizer.send() operation that I should be sending the worker?

**Comment by iamtrask** [comment]
Hey @mukul-rathi - try master now. i think there might have been a bug in model.send() for a minute.

**Comment by mukul-rathi** [comment]
@iamtrask thanks a lot! The notebook works now - can you look over it? 
I'll get on with the second notebook now!

**Comment by iamtrask** [comment]
Excellent work! Merging your first notebook now! (we can merged the second later) :)

**Pull request merged**
