### PR TITLE
Modifying UI of hagrid check command.

### LINKED ISSUE #6887: hagrid.check(silent=True, wait=True) is too silent
## Description
In the quickstart guide, when I run "hagrid.check(['localhost:8081'],silent=True,wait=True)" with a domain node not deployed, the user experience is an infinite hang. Nothing is technically broken, but we need to have at least some feedback.

At a minimum... it should print a single "." every 5 seconds or so just so the user knows that the thread isn't frozen. Additionally, "wait=True" should be changed to "timeout=5" where "timeout=-1" will wait forever but by default timeout=60 or something. This is a better ux.

## How to Reproduce
1. Run step 6 from hagrid quickstart without a domain running.

## Screenshots
Screenshot 2022-10-24 at 17 58 59

### PR DESCRIPTION
**Pull request by rasswanth-s**
## Description
Fixes #6887
The PR aims to modify the hagrid check to show progress during its execution.
The wait command is removed, instead of that, we have added the timeout command.
Currently also the silent is defaulted to True to show the rich Console UI.
Screenshots of execution attached in the PR.
 
## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by rasswanth-s** [comment]
During Checking:
Screenshot 2022-10-27 at 3 27 33 PM

**Comment by rasswanth-s** [comment]
Step 2 : Syft
Screenshot 2022-10-27 at 3 27 52 PM

**Comment by rasswanth-s** [comment]
final output
Screenshot 2022-10-27 at 3 28 40 PM

**Comment by rasswanth-s** [comment]
Timeout error:
Screenshot 2022-10-27 at 3 28 58 PM

**Comment by shubham3121** [comment]
Great work @rasswanth-s !!! Looks amazing 🤩

**Pull request merged**
