### PR TITLE
Remove extraneous numpy serde logic

### PR DESCRIPTION
**Pull request by jvmancuso**
There was a simplifier and detailer for numpy arrays leftover in `torch_serde.py`. When numpy hooking lands on the roadmap, this might be useful, but best to remove this dangling code for now.

### CODE REVIEW

**Comment by jvmancuso** [comment]
the tests that failed were all related to this functionality, going to check that coverage doesn't change if I remove those tests

**Comment by iamtrask** [comment]
Travis no likey

**Comment by iamtrask** [comment]
Closing becasue @mccorby needs the numpy serialization :)

**Comment by jvmancuso** [comment]
was just thinking about this -- if @mccorby needs this for some code, but that code doesn't live in this repository, then shouldn't this functionality live with his code? cc @robert-wagner @yanndupis re: packaging discussion

**Comment by robert-wagner** [comment]
@jvmancuso It is not possible for that code to live with his code since all of his code is in kotlin for android support (similar to the planned syft.js work) This is in relation to the interoperability points

**Pull request closed without merging**
