### PR TITLE
Refactor UpdateSetUpMessage and add missing classes

### PR DESCRIPTION
**Pull request by victorperezc**
## Description
Added missing stuff related to #5538 

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
Hi @victorperezc any reason why you renamed Setup to SetUp. The first version `Setup` is correct.

**Comment by victorperezc** [comment]
Hi @madhavajay I was trying to follow the same schema as other messages do like [CreateInitialSetUp](https://github.com/OpenMined/PySyft/blob/c3528907b1af156d2e84cc3dd6d0fbdb7f4c0f3a/proto/grid/messages/setup_messages.proto#L8)

**Comment by tudorcebere** [comment]
Hi @victorperezc !

Nice to meet you. Could you refactor everything  to setup then this is ready to merge?

**Comment by victorperezc** [comment]
Hi @tudorcebere! You mean refactoring all messages having `SetUp` to `setup`?

**Comment by tudorcebere** [comment]
Only the ones that you've modified, we will refactor others as well.

**Review by tudorcebere — APPROVED** [review]

**Pull request merged**
