### PR TITLE
Zero_: new method for TensorBase

### PR DESCRIPTION
**Pull request by EdwardDixon**
This is supposed to address [https://github.com/OpenMined/PySyft/issues/109](https://github.com/OpenMined/PySyft/issues/109)

### CODE REVIEW

**Comment by iamtrask** [comment]
Hi @EdwardDixon !!! It's great to see you here! Thanks for building in some new functionality. It looks like some of your CircleCI tests aren't passing. All the functionality looks good but there are some style issues:

_________________________ FLAKE8-check(ignoring E501) __________________________
/PySyft/syft/tensor.py:249:5: E303 too many blank lines (2)

_________________________ FLAKE8-check(ignoring E501) __________________________
/PySyft/tests/test_tensor.py:41:1: E302 expected 2 blank lines, found 1
/PySyft/tests/test_tensor.py:44:57: E202 whitespace before ')'
/PySyft/tests/test_tensor.py:47:63: E202 whitespace before ')'
/PySyft/tests/test_tensor.py:348:1: E305 expected 2 blank lines after class or function definition, found 1

If you can remedy these, then I'll be happy to merge your first Pull Request you'll become an official member of the community!  (including invite to the Github Organization, your github logo on our homepage, and vise versa)

**Comment by EdwardDixon** [comment]
All clear now!

**Comment by iamtrask** [comment]
Looks like there are some failing unit tests.

**Comment by EdwardDixon** [comment]
Looks like the merge went badly.  Fingers crossed this did the trick.

**Comment by kevinahuber** [comment]
@EdwardDixon 
```
=================================== FAILURES ===================================
_____________________________ CeilTests.testCeil_ ______________________________

self = <PySyft.tests.test_tensor.CeilTests testMethod=testCeil_>

    def testCeil_(self):
        t = TensorBase(np.array([1.4, 2.7, 6.2]))
        t.ceil_()
        self.assertTrue(syft.equal(t.data, TensorBase([2, 3, 7])))
    
        # Original t unmodified?
>       self.assertTrue(syft.equal(t.data, [1.4, 2.7, 6.2]))
E       AssertionError: False is not true

tests/test_tensor.py:37: AssertionError
===================== 1 failed, 96 passed in 0.96 seconds ======================
Exited with code 1
```

**Comment by EdwardDixon** [comment]
@kevinahuber @iamtrask Another pull request merge-ready.  Hoping to avoid getting back into the merge spin-cycle...

**Comment by EdwardDixon** [comment]
Thanks @kevinahuber!

**Pull request merged**
