### PR TITLE
Duet example - DCGAN Draft - review request #4798

### LINKED ISSUE #4798: Add DCGAN example Duet Notebooks
## Description
Add two notebook's which reflect the DCGAN example split into DO (Data Owner) and DS (Data Scientist):
https://github.com/pytorch/examples/blob/master/dcgan/

## Definition of Done
The partially runnable DCGAN example notebooks should be in the examples/duet/dcgan folder and a README.md should be added in the parent examples/duet directory with a link to the original example and our notebook.

### PR DESCRIPTION
**Pull request by Koukyosyumei**
## Description
I'm currently working to fix #4798 . 
I almost finished the implementation for MNIST. I tested my notebook on my local laptop and Google Colab, and both of them worked.
Could I ask someone to review this PR?

fake_samples_0_910
(iteration = 1 on google colaboratory)

## Affected Dependencies
no

## How has this been tested?
jupyter lab and google colaboratory

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by Koukyosyumei** [comment]
Hi, @madhavajay ! Could I ask you to review this PR ?

**Comment by tudorcebere** [comment]
Hello @Koukyosyumei !

Your work looks really nice! A few things before starting to review it:
* can you solve conflicts to have 0.4 as a base branch? We have a ton of new functionality/ideas there that might be worth having.

Ping me on Slack if you require help on changing anything or if you need help with the rebase/conflict solving on 0.4.

Thanks for your interest in syft!

**Comment by Koukyosyumei** [comment]
@tudorcebere 
Hi, I guess I solved the conflicts !

**Comment by Koukyosyumei** [comment]
I created a new PR #5121

**Pull request closed without merging**
