### PR TITLE
Feature/renorm  add method and tests

### PR DESCRIPTION
**Pull request by AdamJChen**
issue #86

### CODE REVIEW

**Comment by AdamJChen** [comment]
Sure, no problem!

**Comment by CT83** [comment]
@bharathgs won't merging #273  and these tensor and math.py changes at once lead to conflicts?

**Comment by AdamJChen** [comment]
@bharathgs please re-review my changes.

**Comment by AdamJChen** [comment]
@bharathgs it's been added. Thanks for your patience. New to this :).

**Pull request merged**
