### PR TITLE
Rework `PlanTranslatorTorchscript` so it doesn't strip `Parameters`

### PR DESCRIPTION
**Pull request by karlhigley**
## Description

It turns out `jit.trace()` strips `Parameters` out of the tensor chain,
which causes issues with `fix_precision`. Don't fully understand why
`jit.trace()` does that, but operating on a copy of the original `Plan`
avoid mutating the original `State` tensors, which fixes the issue.

## Type of change

Please mark options that are relevant.

- [ ] Added/Modified tutorials
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

* [ ] I have added tests for my changes
* [ ] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
* [ ] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

### CODE REVIEW

**Comment by vvmnnnkv** [comment]
Hmm, why changes from #3361 are not there

**Comment by karlhigley** [comment]
Because I went back to #3360 to find the source of the issue. 😓

**Comment by karlhigley** [comment]
@Syzygianinfern0 is working on resolving the conflicts, so we'll close this PR when that one gets pushed.

**Comment by karlhigley** [comment]
Superseded by #3376.

**Pull request closed without merging**
