### PR TITLE
feat: Added Hindi Translated Notebook 2 example

### PR DESCRIPTION
**Pull request by darkmatter18**
Ref: #2774 

- Translated Part 01 - The Basic Tools of Private Deep Learning in Hindi

fix: #2774 
See also: #2787 

Signed-off-by: Arkadip <in2arkadipb13@gmail.com>

### CODE REVIEW

**Comment by darkmatter18** [comment]
@Yugandhartripathi Review needed!

**Comment by fdroessler** [comment]
Hi, I have been working on the test suit for all notebooks. I have just updated it but the PR is not merged yet. However, I have now moved all the translations into a subfolder so maybe you could do the same?

As in move the `hindi` folder into a subfolder of tutorials:
`examples/tutorials/translations/hindi/`

That way once both of our PRs are merged, yours should be automatically included in the test suit.

**Comment by darkmatter18** [comment]
> Looks good! The only issue that I found is in the last section(Join the Community) which are same as last time(#2787) which is expected since you must have used the same translator so I suggest you copy the corrected version of that from your previous PR #2787 also refer to the comment I just dropped there and @fdroessler's request for changing the directory structure.

@Yugandhartripathi Hey, not able to find the issue here. Please mention the line, you can

**Comment by darkmatter18** [comment]
Fixed the Requested Change. @Yugandhartripathi Check it. @iamtrask Bugless, you can merge.

**Comment by Yugandhartripathi** [comment]
@darkmatter18 The notebook LGTM. If you can just move the hindi folder in `examples/tutorials/translations/hindi/` as suggested by @fdroessler it will be ready to merge.

**Comment by darkmatter18** [comment]
@fdroessler @Yugandhartripathi Andrew merged the 1st Hindi notebook in `examples/tutorials/hindi/` folder. So should I change the path to `examples/tutorials/translations/hindi/` cause, it will change the previous dir structure,

**Comment by iamtrask** [comment]
> @fdroessler @Yugandhartripathi Andrew merged the 1st Hindi notebook in `examples/tutorials/hindi/` folder. So should I change the path to `examples/tutorials/translations/hindi/` cause, it will change the previous dir structure,

Yes please.

**Comment by darkmatter18** [comment]
@iamtrask Done!

**Pull request merged**
