### PR TITLE
adding docstrings for ast/klass.py

### PR DESCRIPTION
**Pull request by dnabanita7**
## Description
This is a pull request for improving docstrings in [PySyft/src/syft/ast/klass.py](https://docs.google.com/spreadsheets/d/1ExD1EQIQtLx03a_h7lBPlvasVsmb38S02Bfw5a7Q62Y/edit#gid=0) as mentioned by the issue #5279. I am a beginner to PySyft. 

## How has this been tested?
- using python ``doctest``

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

This is a sample code added. I want to get others opinions to be sure what I did is correct and I should proceed in that direction.

### CODE REVIEW

**Comment by tudorcebere** [comment]
@dnabanita7, this PR does not properly document the `klass.py` section of the codebase. You might want to understand the full `syft/ast` section and afterwards try to document it or to start writing about smaller sections of the codebase.

Thank you for your interest in Syft! If you need help on this, write to me, @jmaunon or @IrinaMBejan and you'll be guided.

**Comment by jmaunon** [comment]
@dnabanita7 , the idea is to include docstring to make the code understable for new developers. Docstring of `klass.py`  may be complex (I do not understand the full logic of this module but the new docstring should help to this) so could be useful start with smaller sections/modules or ask to `syft team` via slack

**Comment by dnabanita7** [comment]
> Hi @dnabanita7, this PR does not properly document the `klass.py` section of the codebase. You might want to understand the full `syft/ast` section and afterwards try to document it or to start writing about smaller sections of the codebase.
> 
> Thank you for your interest in Syft! If you need help on this, write on Slack to me, @jmaunon or @IrinaMBejan and you'll be guided.

Yes, I would want to learn codebase of ``ast/klass.py``. I will say to keep this pr open for now and i will make changes to it later.

**Comment by dnabanita7** [comment]
> @dnabanita7 , the idea is to include docstring to make the code understable for new developers. Docstring of `klass.py` may be complex (I do not understand the full logic of this module but the new docstring should help to this) so could be useful start with smaller sections/modules or ask to `syft team` via slack

Sure thing! Thank you. I have asked on slack.

**Pull request closed without merging**
