### PR TITLE
Implementation of uniform, fill, topk, tolist, trace functions for TensorBase #44, #106, #104

### PR DESCRIPTION
**Pull request by aqibsaeed**
Added uniform, uniform_ , fill_ , tolist, topk and trace functions for TensorBase along with tests.

### CODE REVIEW

**Comment by kevinahuber** [comment]
@aqibsaeed 
```
=================================== FAILURES ===================================
_________________________ FLAKE8-check(ignoring E501) __________________________
/home/travis/build/OpenMined/PySyft/syft/tensor.py:621:5: E303 too many blank lines (2)
/home/travis/build/OpenMined/PySyft/syft/tensor.py:621:8: E271 multiple spaces after keyword
/home/travis/build/OpenMined/PySyft/syft/tensor.py:622:60: W291 trailing whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:626:42: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:626:44: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:626:54: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:626:56: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:626:67: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:626:69: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:630:5: E303 too many blank lines (2)
/home/travis/build/OpenMined/PySyft/syft/tensor.py:631:62: W291 trailing whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:635:36: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:635:38: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:635:48: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:635:50: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:635:61: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:635:63: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:637:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:644:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:651:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:652:30: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:652:32: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/syft/tensor.py:656:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:660:24: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/syft/tensor.py:660:51: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/syft/tensor.py:663:43: E271 multiple spaces after keyword
/home/travis/build/OpenMined/PySyft/syft/tensor.py:665:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:666:19: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/syft/tensor.py:666:30: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/syft/tensor.py:667:69: W291 trailing whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:668:79: W291 trailing whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:672:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/syft/tensor.py:673:18: E711 comparison to None should be 'if cond is not None:'
/home/travis/build/OpenMined/PySyft/syft/tensor.py:678:1: W391 blank line at end of file
_________________________ FLAKE8-check(ignoring E501) __________________________
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:465:29: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:465:31: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:465:39: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:465:41: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:470:24: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:470:26: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:470:34: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:470:36: E251 unexpected spaces around keyword / parameter equals
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:472:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:473:1: E302 expected 2 blank lines, found 1
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:475:36: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:475:38: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:475:40: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:478:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:479:1: E302 expected 2 blank lines, found 1
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:39: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:43: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:48: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:53: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:55: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:58: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:61: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:64: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:68: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:72: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:75: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:78: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:81: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:83: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:85: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:87: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:89: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:92: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:96: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:99: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:102: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:105: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:107: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:109: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:111: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:481:113: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:482:23: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:47: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:62: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:67: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:73: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:77: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:80: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:84: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:88: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:483:91: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:484:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:485:1: E302 expected 2 blank lines, found 1
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:487:38: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:487:42: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:487:45: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:487:49: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:489:43: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:490:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:491:1: E302 expected 2 blank lines, found 1
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:493:51: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:493:55: W291 trailing whitespace
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:494:44: E231 missing whitespace after ','
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:495:1: W293 blank line contains whitespace
/home/travis/build/OpenMined/PySyft/tests/test_tensor.py:496:1: E305 expected 2 blank lines after class or function definition, found 1
===================== 2 failed, 131 passed in 3.84 seconds =====================
```

**Comment by aqibsaeed** [comment]
@kevinahuber , is there a way I can test it locally? to avoid it in future?

**Comment by anoff** [comment]
@aqibsaeed did you run the tests as as described in the [readme](https://github.com/OpenMined/PySyft#tests)?

**Comment by bartimaeus12** [comment]
@aqibsaeed your IDE should have an option to check pep8 compliance. Enable it.

**Comment by aqibsaeed** [comment]
@anoff Nope, I was unable to run tests via make command. I tested implementation of each function independently. I think, there should be a bit more clear guide to run tests or alternative to make command for Window users.

**Pull request merged**
