### PR TITLE
Add support for Pytorch 1.1

### LINKED ISSUE #2126: Torch 1.1 Integration
So PyTorch just released torch 1.1 and it causes a lot of failing Unit Tests because of some breaking API updates. We need to address them.

### PR DESCRIPTION
**Pull request by LaRiffle**
Fix #2126 related to the new version 1.1 of Pytorch

### CODE REVIEW

**Comment by robert-wagner** [comment]
Does it work for versions greater than 1.0.1 or only 1.1

**Comment by LaRiffle** [comment]
It was passing before change the requirements.txt so I assume it works :)

**Comment by robert-wagner** [comment]
In that case could we change the requirements to be >=1.0.1

**Comment by LaRiffle** [comment]
You made me change it! haha

**Comment by LaRiffle** [comment]
I would suggest upgrade everyone to 1.1 so that we avoid cases where we have different behaviours depending of the version

**Pull request merged**
