### PR TITLE
Exorcise a Python `eval` and transmute into the lesser demon `getattr`

### PR DESCRIPTION
**Pull request by karlhigley**

### CODE REVIEW

**Comment by iamtrask** [comment]
Exorcisms!

**Comment by karlhigley** [comment]
@LaRiffle Ah, good catch. What a difference [a year makes](https://github.com/OpenMined/PySyft/pull/1814), huh? 😄

**Comment by karlhigley** [comment]
I'm going to leave further optimization of this code for a later issue, since this PR is about fixing a security hole.

**Comment by LaRiffle** [comment]
Ok good, maybe just `cmd = cmd.split(".")`  because this is a one line change, and we'll do the rest later

**Pull request merged**
