### PR TITLE
Continue adding gradual types over the project code-base

### PR DESCRIPTION
**Pull request by abdulrahmanmazhar**
This is another attempt for adding gradual type annotations for our code-base :)

### CODE REVIEW

**Comment by abdulrahmanmazhar** [comment]
Here is another attempt for adding type annotations, it will get better gradually since I'm forced to add 'Any' type in some places because of it's polymorphic nature in the codebase, maybe later we can make a base type class for our codebase and use it all over the places :smile:

**Comment by iamtrask** [comment]
syft (unittest.loader._FailedTest) ... ERROR
test (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: syft (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: syft
Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/atrask/PycharmProjects/PySyft/syft/__init__.py", line 2, in <module>
    from . import core
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/__init__.py", line 3, in <module>
    from . import workers
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/__init__.py", line 3, in <module>
    from .base import BaseWorker
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/base.py", line 9, in <module>
    from ..frameworks.torch import utils as torch_utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/__init__.py", line 1, in <module>
    from . import torch
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/torch/__init__.py", line 1, in <module>
    from .hook import TorchHook
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/torch/hook.py", line 10, in <module>
    from . import utils as torch_utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/torch/utils.py", line 13, in <module>
    from .. import encode
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/encode.py", line 136, in <module>
    def decode(message: Optional[{__contains__, items}], worker: Any, acquire: bool = None, message_is_dict: bool = False):
NameError: name '__contains__' is not defined


======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/atrask/anaconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/atrask/PycharmProjects/PySyft/test/__init__.py", line 2, in <module>
    from .core import workers_test
  File "/Users/atrask/PycharmProjects/PySyft/test/core/workers_test.py", line 2, in <module>
    import syft as sy
  File "/Users/atrask/PycharmProjects/PySyft/syft/__init__.py", line 2, in <module>
    from . import core
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/__init__.py", line 3, in <module>
    from . import workers
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/__init__.py", line 3, in <module>
    from .base import BaseWorker
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/workers/base.py", line 9, in <module>
    from ..frameworks.torch import utils as torch_utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/__init__.py", line 1, in <module>
    from . import torch
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/torch/__init__.py", line 1, in <module>
    from .hook import TorchHook
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/torch/hook.py", line 10, in <module>
    from . import utils as torch_utils
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/torch/utils.py", line 13, in <module>
    from .. import encode
  File "/Users/atrask/PycharmProjects/PySyft/syft/core/frameworks/encode.py", line 136, in <module>
    def decode(message: Optional[{__contains__, items}], worker: Any, acquire: bool = None, message_is_dict: bool = False):
NameError: name '__contains__' is not defined


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
atrask-macbookpro:PySyft atrask$

**Comment by iamtrask** [comment]
Looks like something keeps the unit tests from running.

**Comment by abdulrahmanmazhar** [comment]
I guess we both have different environments of python, you are using anaconda right? will check that, but I see that some parts of the code are using "__future__" which is python 2.x compatible so do we use really python 2.x in anything?

**Comment by iamtrask** [comment]
So we only officially support Python 3 - I don't think we have any plans to support Python 2.

**Comment by abdulrahmanmazhar** [comment]
but for example "test_interaction.py" file it seems to be a "python 2.x" not a "python 3.x" one? :)

**Comment by iamtrask** [comment]
forgive me - where is test_interaction.py?

**Comment by abdulrahmanmazhar** [comment]
My bad it's in the "ipywidgets" package, it's a python2.x compatible package i believe but it's fine i guess :)

**Comment by abdulrahmanmazhar** [comment]
Still, tests are not running on my environment and i didn't figure out why yet

**Comment by alok** [comment]
You may find [MonkeyType](https://github.com/Instagram/MonkeyType) handy for doing a comprehensive sweep, and then going over the output of `git diff` to fix the types that were too specific. Usually beats going over every function.

You can also add mypy checks to travis once it succeeds with `mypy --check-untyped-defs`. This makes it easy to ensure PRs have the correct types.

**Comment by iamtrask** [comment]
Is this still active?

**Comment by iamtrask** [comment]
closing because it seems inactive - we can reopen if this is false

**Pull request closed without merging**
