### PR TITLE
Quick Fix CrypTen Demo Jails

### PR DESCRIPTION
**Pull request by gmuraru**
## Description
Small fix needed because of this [PR](https://github.com/facebookresearch/CrypTen/pull/121)

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by gmuraru** [comment]
The tests are failing because the branch needs rebasing using the new CrypTen changes from the branch

**Comment by youben11** [comment]
So this has been tested on the last commit of CrypTen? wasn't it working before and the update made it work?

**Comment by gmuraru** [comment]
> So this has been tested on the last commit of CrypTen? wasn't it working before and the update made it work?

Currently, on the CrypTen branch we target their master.

**Comment by gmuraru** [comment]
@youben11 the problem is that it needs a rebase - after the rebase it should work

**Pull request merged**
