### PR TITLE
Falcon: Private Compare

### PR DESCRIPTION
**Pull request by abogaziah**
## Description
this PR implements the private compare algorithm including the preprocessing material
it should close issue #3967 

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by PlamenHristov** [comment]
Hey @abogaziah ,
I can see you started implementing the private compare, but haven't made much progress, since September.
Would it be ok if I can continue what you've done so far and open a PR ?

**Comment by gmuraru** [comment]
Only a headsup that there is also a PR that adds the bit injection - from ABY3, but for the malicious settings here: https://github.com/OpenMined/PySyft/pull/4644 - I should finish the PR and make it ready for review this week

Falcon has two scenarios for semi-honest and malicious - I think, for the moment, we might be able to use the malicious setup (and use the implementation from the above PR for Private Compare).

For the semi-honest setting, there is needed an Oblivious Transfer-like component - but we can do that in another PR.

**Comment by abogaziah** [comment]
@PlamenHristov yes, go-ahead!

**Comment by PlamenHristov** [comment]
Thanks for the update @gmuraru, I'll use what's in this PR and then switch to your bit inject once merged. Otherwise, yeah I can add the OT stuff later.

Thanks @abogaziah.

**Comment by gmuraru** [comment]
@abogaziah could we close this since @PlamenHristov is taking up the private compare?

**Pull request closed without merging**
