### PR TITLE
Implement Default numel Functionality for Base Tensor Type #78

### PR DESCRIPTION
**Pull request by alberduris**
Added numel method, modified nelement and size.

### CODE REVIEW

**Comment by joewie** [comment]
Disclaimer: I'm not a reviewer.

Why keep the `if...else` statements for `numel`, `nelement`, and `size`?

Also, there are unit tests for `size` and `nelement` in `class DimTests` that you might want to remove since you wrote more comprehensive ones.

**Comment by alberduris** [comment]
@joewie 

> Why keep the if...else statements for numel, nelement, and size?

I kept the `if...else` statements because I'm not sure if it's possible that in the future, the distinction between encrypted and not encrypted will be necessary (I suppose no but not sure), so to maintain the structure that I found.

> Also, there are unit tests for size and nelement in class DimTests that you might want to remove since you wrote more comprehensive ones.

Okay, I'll take a look then. Thanks!

Anyway, the Travis CI build failed and I don't know exactly what to do to solve it.

**Comment by alberduris** [comment]
I know that this PR is marked with the red cross but I think it should be reviewed, because the red cross is just because of the CodeCoverage and as @ibrahimsharaf pointed out in Slack:
> a coverage report is generated now and any new pull request shouldn't give codecov errors
So if it's an old PR you can ignore the codecov failure (edited)
but it won't fail in future PRs

ping @iamtrask, reviewers

**Comment by ibrahimsharaf** [comment]
More details regarding codecov failure: https://docs.codecov.io/docs/error-reference#section-missing-base-commit

**Pull request merged**
