### PR TITLE
One worker bug

### PR DESCRIPTION
**Pull request by Ankit-Dhankhar**
In reference to issue #2392, Single iterator does need to shift worker IMHO.  Thus, for case of 1 worker we can have 1 iterator insetead of general (worker - 1) iterators.

### CODE REVIEW

**Comment by DanyEle** [comment]
I also experienced this bug personally when running some tutorials. Would be very nice to have a fix for it when using one single worker!

**Comment by robert-wagner** [comment]
@Ankit-Dhankhar Could you add a test to ensure we don't get this bug in the future

**Comment by Ankit-Dhankhar** [comment]
Sure I will add a test case for same :)

**Comment by Ankit-Dhankhar** [comment]
Test case added, please have a look

**Pull request merged**
