### PR TITLE
Create pointer #1696

### PR DESCRIPTION
**Pull request by LaRiffle**
Add a hook to overload Tensor
Add a PointerTensor
Add a create_pointer method

TODO:
- [ ] Work tensor repr/str
- [ ] Add tests
- [ ] Add proper docstrings to all Classes, Methods, and Functions
- [ ] Add static types to methods and function parameters

Please tell me what points are not ok with torch1 approach, otherwise I'll be tempted to copy paste most of the 0.3.1 work.

### CODE REVIEW

**Comment by Nivek92** [comment]
Hey @LaRiffle  from my understanding the "Fix type confusion in serde.py" is incorrect. The returns are tuple (exactly 3 elements each) but are returned as python lists instead of python tuple because of the serialization which can't handle python tuple.

The type annotations describe the "collection" type not the actual python return type I think. I may be wrong though

**Comment by LaRiffle** [comment]
Hum yes I get your point. I can revert sure, although my PyCharm is a bit bothered by this typing issue. But I'm no python typing expert, so :)

**Comment by Nivek92** [comment]
"I'm no python typing expert" - me neither so I would suggest we stick with the approach that doesn't cause PyCharm problems because I just assume PyCharm knows better :D 

If in the future we find out that the other way is correct we can still change it

**Comment by iamtrask** [comment]
Note: I just added the last two bullets to the list at the top (referring to docstrings and static typing we'd want to have before merging)

**Comment by LaRiffle** [comment]
In response to #1707, here is a version of what could be moving attributes out of torch. This is not final at all, but I would like to have our opinion on that solution.

**Comment by Nivek92** [comment]
Nice work @LaRiffle I like it much better this way. So much cleaner.

**Comment by iamtrask** [comment]
I noticed you removed the work-in-progress label. Are you ready to merge?

**Comment by LaRiffle** [comment]
Merge create pointer - solve Issue #1696 - pass tests

**Pull request merged**
