### PR TITLE
BMM functionality - issue #28

### PR DESCRIPTION
**Pull request by AkashGutha**
issue #28 

Features looking at:
1. if any of the tensors is encrypted return NotImplemented error.
2. Unit tests to check shape returned tensor shape.
3. Unit tests to check the tensor value returned.
4. Inline documentation should take inspiration from pytorch but not copy it (which currently i did).

### CODE REVIEW

**Comment by AkashGutha** [comment]
this is ready to go. 👯‍♂️

**Comment by AkashGutha** [comment]
@bharathgs that fixed them all.

**Comment by AkashGutha** [comment]
@bharathgs the way we are merging seems a bit odd. 

ideally, you would want all the commits to be there. so that you can go through each change in the future to get a better understanding of what's really going on.

**Comment by bharathgs** [comment]
We follow the standard git workflow, which you can refer [here](https://github.com/OpenMined/Docs/blob/master/tutorials/github_contribution_workflow_tutorial.md#squashing-commits)

**Comment by AkashGutha** [comment]
That makes sense. 👍

**Pull request merged**
