### PR TITLE
Added additive and multiplicative depth tracking #11

### PR DESCRIPTION
**Pull request by dipanshunagar**
This can be used to predict to predict when a number is about to become undecryptable. (#11)
@MtDersvan @iamtrask

### CODE REVIEW

**Comment by iamtrask** [comment]
@dipanshunagar epic!!!

**Comment by iamtrask** [comment]
(if you'll forgive the mild scope creep ;) )

**Comment by dipanshunagar** [comment]
Should I call it just depth then? Could it be more descriptive?

**Comment by MtDersvan** [comment]
Awesome! 
What about other operations like `-` and `/`? I think these need to be tracked, too. (e.g. simple 'y = y/5' is overflowing already after `_div_depth` >≈ 16)
Also, `-` doesn't work (https://github.com/OpenMined/PySyft/pull/271) as of right now.

**Pull request merged**
