### PR TITLE
[WIP] Notebook test during CI

### PR DESCRIPTION
**Pull request by fdroessler**
This is the PR for #2693 as a reference here.

### CODE REVIEW

**Comment by fdroessler** [comment]
@kamathhrishi Great points thanks so much for looking at this. Yes, ultimately I think something like a `glob.glob(*.ipynb)` or similar would be good. However, some handcrafting will be necessary as some notebooks need a certain environment (workers, Websocketserver etc.) I have just included here those that are running straightforward atm to provide a minimal example.

Yes you are totally right in that it is hard to know that notebooks are part of the test, it should probably be included in the Contributer guide, I will make a note of that.

Not sure I understand your last point about the checkout the changes. For the notebooks I included I have cleared the kernel and outputs before including them in the tests. Do you mean that or something else?

**Comment by LaRiffle** [comment]
> Not sure I understand your last point about the checkout the changes. For the notebooks I included I have cleared the kernel and outputs before including them in the tests. Do you mean that or something else?

I think @kamathhrishi is asking to checkout the files from the git commit, so that your PR doesn't have 18 files changed with most of them just being changed because you re-run the notebooks :)

**Comment by fdroessler** [comment]
Yeah, that is a good point. However, a lot of the notebooks have weird metadata still included which makes it hard to run them automated so most of the changes that I did is to restart the kernels so the notebooks are clean.

**Comment by iamtrask** [comment]
How's this coming?

**Comment by fdroessler** [comment]
Thanks for following up, I'll have some time today and tomorrow to work on this.

**Comment by fdroessler** [comment]
@iamtrask What is your view on all the data files that are necessary for the notebooks to run? I have the ones that don't need the data files running but not sure how to proceed with the others. A separate git lfs or downloading them when the fixture is set-up? What are your thoughts on this?

**Comment by fdroessler** [comment]
I had some problems with my repo so I needed to set it up new. Will start a new PR. Sorry for any inconveniences

**Pull request closed without merging**
