### PR TITLE
Modify Bengali translated notebooks

### PR DESCRIPTION
**Pull request by jabertuhin**
## Description
I worked on the modification of Bengali translated notebooks[From Part 01 to Part 10(except 3,4 and 5)] 

Fixes # (issue)
The issue was closed.
- issue [#3042](https://github.com/OpenMined/PySyft/issues/3042). 

## Type of change

Please mark options that are relevant.

- [x] Added/Modified tutorials
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

* [ ] I have added tests for my changes
* [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
* [ ] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

### CODE REVIEW

**Comment by srishilesh** [comment]
@karlhigley Please help fix the error in checks

**Comment by karlhigley** [comment]
It looks like an error in the format of the notebook. The test is having trouble parsing the JSON. Not sure where exactly the issue is in the big diff, but I'd check to make sure the notebook is valid JSON.

**Comment by iamtrask** [comment]
> @karlhigley Please help fix the error in checks

As a matter of Github etiquette - it is generally not an accepted practice to publicly request another developer to "fix" a PR they did not directly help build. Asking to consult is great - asking to comment or approve/disapprove is essential. However, unless @jabertuhin and Karl helped construct this PR together, it is @jabertuhin 's job to "fix" the PR, not Karl's.

**Comment by iamtrask** [comment]
> It looks like an error in the format of the notebook. The test is having trouble parsing the JSON. Not sure where exactly the issue is in the big diff, but I'd check to make sure the notebook is valid JSON.

Karl - you're such a nice guy

**Comment by srishilesh** [comment]
> > @karlhigley Please help fix the error in checks
> 
> For the group - as a matter of Github etiquette - it is generally not an accepted practice to publicly request another developer to "fix" a PR they did not directly help build. Asking to consult is great - asking to comment or approve/disapprove is essential. However, unless @jabertuhin and Karl helped construct this PR together, it is @jabertuhin 's job to "fix" the PR, not Karl's.

I am sorry @karlhigley . Thank you @iamtrask  for pointing out my mistake, I will not repeat this mistake further.

**Comment by jabertuhin** [comment]
HI @karlhigley,
Can you suggest any change from my side that will help to solve the issue?

**Pull request merged**
