### PR TITLE
Removed jupyter from requirements.txt

### PR DESCRIPTION
**Pull request by TheOriginalAlex**
@anoff

### CODE REVIEW

**Comment by anoff** [comment]
I can't approve because I have no clue how this repo works, haha but LGTM 😜

**Comment by cypherai** [comment]
Not sure but this could potentially impact the `make run` command https://github.com/OpenMined/PySyft/blob/develop/Makefile#L7 ?

We could add `apk add jupyter` to the docker command before launching the notebook?

**Comment by iamtrask** [comment]
Can someone explain why this is a good idea?

**Comment by swaroopch** [comment]
I think the issue is https://github.com/OpenMined/PySyft/issues/174 but it's still unclear to me, @anoff can you please chime in?

**Comment by anoff** [comment]
@swaroopch @iamtrask yes it is based on that issue. The problem is that `mine.js` needs the `pySyft` command line version to run actual training on the model. However jupyter notebooks need a lot of dependencies that need to be baked into the `mine.js` image only to support the jupyter dependency of pySyft. But pySyft (the library) has no ties to jupyter.

This should be split imho following KISS/separation of concerns principle. Unless pySyft is not considered the library but rather the notebook, then we need a name for the lib :)

**Comment by cypherai** [comment]
@anoff is right, we definitely want to remove jupyter from PySyft depencies. The user who want to run PySyft's notebooks with docker just have to do `make run` (we'll need to to update the command accordingly).

**Pull request merged**
