### PR TITLE
Add Bengali Translated Notebooks #Part 4 and #Part 5

### PR DESCRIPTION
**Pull request by jabertuhin**
Translated Notebooks: 

- Part 04 - Federated Learning via Trusted Aggregator.ipynb

- Part 05 - Welcome to the Sandbox.ipynb

### CODE REVIEW

**Comment by jabertuhin** [comment]
Hi, @adventuroussrv 
Is there anything that I can fix to pass the tests?

**Comment by karlhigley** [comment]
@jabertuhin I think this just needs to merge in the latest commits from the `master` branch.

**Comment by jabertuhin** [comment]
@karlhigley  my branch is up-to-date with the upstream/master branch.
`git merge upstream/master`
Already up to date.
Can there be any other thing or I am missing something?

**Comment by karlhigley** [comment]
Maybe you hadn't pushed the update yet? It was behind master a bit. Anyway, merged in master and we'll see if that fixes the tests.

**Comment by jabertuhin** [comment]
@karlhigley It's fine now.

**Comment by adventuroussrv** [comment]
Congrats! @jabertuhin  :tada:

**Pull request merged**
