### PR TITLE
__add__ method for IntTensor

### PR DESCRIPTION
**Pull request by gavinuhma**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* CPU:
* GPU:
* PySyft Version:
* Unity Version:
* OpenMined Unity App Version:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gavinuhma** [comment]
Working on #755

**Comment by Floev** [comment]
Should we create a BaseTensor class and move whatever makes sense from FloatTensor there?
2 items in your code that need to be handled:
-  "if (type(x) == IntTensor)" replace with "if(type(x) == type(self))"
- IntTensor in documentation. We might be able to populate using self.__class__.__name__?

**Comment by gavinuhma** [comment]
A BaseTensor class would be great!

We would also need to change the return line: `return IntTensor(data=int(response), data_is_pointer=True)`.

Not sure we can change the doc value dynamically... A quick google seems to suggest it's not a great idea. Is there a good way to do that?

Docs aside, the code is so similar I think we can create a BaseTensor class with minimal effort.

**Comment by gavinuhma** [comment]
@Floev I created an issue for this #760 and started testing some code #759

**Pull request merged**
