### PR TITLE
Re-enable flake8-bugbear checks in Ruff

### PR DESCRIPTION
**Pull request by kiendang**
## Description
Re-enable flake8-bugbear checks in Ruff to catch potential buggy code.

One of those is B006 `Do not use mutable data structures for argument defaults.`

for functions, instead of

```python
def f(ls=[]):
   ...
```

do

```python
def f(ls=None):
    if ls is None:
        ls = []
    ...
```

This is an [anti-pattern](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html) and might lead to subtle bugs.
## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by kiendang** [comment]
Ah looks like pydantic handles this differently so things like
```python
class CreateAsset(SyftObject): 
    ...
    contributors: List[Contributor] = []
```

is valid.

**Comment by kiendang** [comment]
Reopen to fix some stuff that is not pydantic.

**Comment by madhavajay** [comment]
@kiendang yes, great catch. We used to use bugbear which had a check for this but we switched to `ruff`: https://github.com/charliermarsh/ruff Can you see if we can add back the right bugbear check to ruff for this.

https://github.com/PyCQA/flake8-bugbear
```
B006: Do not use mutable data structures for argument defaults. They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them.
```

**Comment by kiendang** [comment]
@madhavajay I've re-added the flake8-bugbear checks and attempted to fix the failed checks. There are only a couple of places where fixing the checks makes the code doesn't work anymore. Those will be followed up separately.

**Review by madhavajay — APPROVED** [review]
Dude, stellar work! ❤️💫

I am keen to also get the mypy checks back in but im worried about the 500+ errors we need to fix first.

```
- repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        name: mypy-syft
        always_run: true
        # files: "^packages/syft/src/syft/serde|^packages/syft/src/syft/util"
        files: "^packages/syft/src/syft/serde"
```

I think we just need to progressively open this up as we go.

**Comment by kiendang** [comment]
Yup I actually also tried reenabling mypy but it's close to 1000 errors now. I think we can gradually resolve them by reenabling individual parts of the code base

**Pull request merged**
