### PR TITLE
Joining a network to itself uses join self message

### PR DESCRIPTION
**Pull request by jabelman**
## Description
Joining a network to itself resulted in a failure to connect to the VPN. VPNJoinMessageWithReply logged an error to use VPNJoinSelfMessageWithReply but the VPNAPI was not using it. This adds a conditional check to see if a network client is trying to join the VPN and uses VPNJoinSelfMessageWithReply if true.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- I tested by running a local network and joining to itself through the client side api. Then I connected a local domain to the network.
- previously, joining a local network to itself resulted in failure to connect to vpn

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
Hi @jabelman is the goal of this to allow Networks to connect to other Network VPNs?

**Comment by jabelman** [comment]
@madhavajay no, the goal was just to make it possible for a network to join itself and defer to whatever logic already existed in the VPNJoinSelfMessageWithReply, but I didn't fully read through it. I was thinking the join self message would handle the error checking for a network trying to join another network instead of itself. I was following this notebook as a guide for setting up a network with multiple domains, but could not get it to work without this change to the code: 

https://github.com/OpenMined/PySyft/blob/2e58833bcfb5e7d9b697633383ca42995899d1c5/notebooks/Experimental/Shubham/Joining%20a%20Network%20Node.ipynb

**Comment by madhavajay** [comment]
Hi @jabelman the Network already joins itself automatically on startup. I would highly recommend not treating anything in `Experimental` as up to date, those notebooks can live for years with old experimental and out of date code.

**Comment by jabelman** [comment]
Gotcha, thanks for your help

**Pull request closed without merging**
