### PR TITLE
Implemented Sign functionality on BaseTensor Object#95

### PR DESCRIPTION
**Pull request by sajalsubodh22**
1. added sign() and sign_() functionalities in syft/tensor.py
2. added class signTests() in tests/test_tensor.py

### CODE REVIEW

**Comment by iamtrask** [comment]
@sajalsubodh22 looks like there are a few merge conflicts. Would you mind?

**Comment by sajalsubodh22** [comment]
@iamtrask i'll look into it

**Comment by sajalsubodh22** [comment]
@iamtrask check again. I have resolved the merge conflicts.

**Comment by sajalsubodh22** [comment]
@iamtrask ya that have been a merge conflict i suppose. I'll look into it

**Comment by sajalsubodh22** [comment]
@iamtrask look into this again.

**Comment by iamtrask** [comment]
Thank you so much @sajalsubodh22 !!!

**Pull request merged**
