### PR TITLE
Revert "Fix get permissions"

### PR DESCRIPTION
**Pull request by gmuraru**
Reverts OpenMined/PySyft#4598

### CODE REVIEW

**Comment by madhavajay** [comment]
@gmuraru Do you remember what this PR was about? I'm just getting my brain back online after the break.

**Comment by gmuraru** [comment]
I have added some default permissions in a previous PR (I forgot about request) and this PR removes them.

python_remote.random() <-- I had access to this - but the proper way (I think) is to use ```request```

**Comment by gmuraru** [comment]
@madhavajay could we merge this? (this might impose security issues because it bypasses the "request" --> "approve" formula)

**Review by madhavajay — APPROVED** [review]
LGTM!

**Review by tudorcebere — APPROVED** [review]

**Pull request merged**
