### PR TITLE
Added Serialized/Deserialized Protocol

### PR DESCRIPTION
**Pull request by cgoxo**
## Description
#5276 
- Added the field `protocol` for session serialization and deserialization in `session_util.py`.
- Introduce `protocol` in `session.proto`.
- Files got reformatted but I have only included `session_pb2.py` since major changes are reflected in it.

## Affected Dependencies
- Files got reformatted under `src/syft/proto/` by running the script `./scripts/build_proto.sh` but I have not included them 

## How has this been tested?
- Building the code with `python3 setup.py install` after making changes 
- Runnung the tests for SyMPC module with `pytest tests/syft/lib/sympc`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by gmuraru** [comment]
@cgoxo the changes look good.

Could you run black to make sure the code is formatted correctly

**Comment by cgoxo** [comment]
black is wroking fine but I have not included the files except `session_pb2.py` because minor changes occured which does not hinder the codebase. In `session_pb2.py` protocol has been introduced with the help of `session.proto`.

**Comment by gmuraru** [comment]
There is a flake8 error. If you look at the python linting job you can see the errors

**Comment by gmuraru** [comment]
Hmm...I think you changed more files than required (you could add only the protocol file for session and not the other files)

**Comment by cgoxo** [comment]
Those changed files are generated due to `build_proto.sh`.

**Comment by gmuraru** [comment]
I think you need to rebase to have the latest ```dev``` changes. If you look in the modified files (the tab from the PR) there is a large number of modified files - which should not be touched by the ```build_proto.sh```.
Also, after running ```build_proto.sh```, add only the one specific for the session - not all the files.

**Comment by madhavajay** [comment]
@cgoxo Can I suggest you update your `protoc`. If you have a recent version you won't get the generated output diff because they stabilised the output back around 3.14 i think. Also 3.15 introduced optionals. We currently install and compile the protobufs in CI with the latest build and since we are in control of compiling and shipping them we will likely be doing that with our PyPI releases.

https://github.com/protocolbuffers/protobuf/releases

**Pull request closed without merging**
