### PR TITLE
Readme update to install helm via DockerHub

### PR DESCRIPTION
**Pull request by Param-29**
## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

Logs from my PC: 

```
(base)$ helm install syftv0.82.b21 oci://registry-1.docker.io/openmined/syft --version 0.8.2-beta.21
Pulled: registry-1.docker.io/openmined/syft:0.8.2-beta.21
Digest: sha256:72ea5a3106f2c9f7b0e3128fdbf086b73279d76d923de097469e96712b6e8548
NAME: syftv0.82.b21
LAST DEPLOYED: Thu Aug 24 13:42:05 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

### CODE REVIEW

**Review by madhavajay — CHANGES_REQUESTED** [review]
It looks like the helm commands are different for oci urls which is annoying.

For now we can do this:
```
SYFT_VERSION="0.8.2-beta.21"
helm pull oci://registry-1.docker.io/openmined/syft --version $SYFT_VERSION
helm install my-domain "./syft-$SYFT_VERSION.tgz" --namespace syft --create-namespace
```

You can test this by creating a k3d cluster and then running the above commands. Check the tox.ini file.

Also, it looks like it currently fails because the helm chart was released as 0.8.2-beta.21 but the latest docker images are 0.8.2-beta.20.

I think we need to re-release both the helm chart and docker containers at the same time so they have matching versions.
```

**Comment by madhavajay** [comment]
I think this means we might need to go back to using our own repo on gh-pages, but for now we can do the above for 0.8.2 release and then do the custom repo gh-pages action later.

**Comment by Param-29** [comment]
Screenshot from 2023-08-31 08-58-58
Screenshot from 2023-08-31 09-00-12

Tested it offline with @rasswanth-s

**Review by madhavajay — APPROVED** [review]
Great work!

**Comment by madhavajay** [comment]
I can confirm I was able to deploy to k3ds on my machine without issue!

**Pull request merged**
