### PR TITLE
Fixed Intergration Tests SMPC

### PR DESCRIPTION
**Pull request by rasswanth-s**
## Description
Modified to use `get_copy` in reconstruct.

## How has this been tested?
Locally

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Review by iamtrask — APPROVED** [review]

**Comment by madhavajay** [comment]
Is it okay to do this? Will the objects be stuck in the store forever?

**Comment by rasswanth-s** [comment]
> Is it okay to do this? Will the objects be stuck in the store forever?
Yes @madhavajay ,that's a caveat, @iamtrask  and @gmuraru  suggested ideas like using blocking `get` until object appears, If we incorporate it , I think it would solve.

**Comment by iamtrask** [comment]
Yeah it strikes me these would get stuck in the store forever. We need to do .get() instead but handle when subsets fail.

**Comment by gmuraru** [comment]
What is the issue with doing `get`, @rasswanth-s ?
The idea from using `get` here was to fetch the shares locally and then to add them.
If the process of `fetching` the shares would  fail (because maybe one of the parties did not approve the request for `get`) - then we will `resend` the shares we fetch until that point.

**Comment by rasswanth-s** [comment]
Yes @gmuraru , I am not sure completely , why it is not working , I will take a additional look into it.

**Pull request closed without merging**
