### PR TITLE
Translation to Spanish of Parts 09, 13 (a, b and c)

### PR DESCRIPTION
**Pull request by arturomf94**
Credits to: @thefirebanks

This comes as a response to the initiative to translate all the
PySyft tutorials, as it is desirable to learn PySyft in our native
language.

As requested, every part of the tutorial is done via pull request
separately to:

 - Track better the changes in every document.

 - Avoid double work.

Resolves: #2775
See also: #2782

### CODE REVIEW

**Comment by arturomf94** [comment]
There is a problem with Parts 13b and 13c since these notebooks are excluded from the tests. This can be seen in [`test_notebooks.py`](https://github.com/OpenMined/PySyft/blob/master/test/notebooks/test_notebooks.py)

Either the notebooks are fixed or these translations are also ignored.

**Comment by ricardopretelt** [comment]
Hi, thanks for the effort doing the parts and uploading them again for the merge. I just have one request. The translation of encription is _**encriptación**_ no _encripción_ . It appears in part 9 and 13b.

**Comment by arturomf94** [comment]
@ricardopretelt thanks. Typos have been fixed.

**Comment by karlhigley** [comment]
@arturomf94 It looks like `git diff` with the branch reference doesn't work as expected in the translation tests. Maybe it only checks out one branch?

```

Run git diff --name-only master examples/tutorials/translations/ examples/tutorials/translations/ > ./test/notebooks/git-diff.txt
  git diff --name-only master examples/tutorials/translations/ examples/tutorials/translations/ > ./test/notebooks/git-diff.txt
  pytest test/notebooks/test_notebooks.py::test_notebooks_basic_translations_diff
  [ -e ./test/notebooks/git-diff.txt ] && rm ./test/notebooks/git-diff.txt
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.10/x64
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
##[error]Process completed with exit code 128.
```

**Pull request merged**
