### PR TITLE
fix: reduce fe to metadata info

### PR DESCRIPTION
**Pull request by tcp**
## Description
Fallback that shows the metadata in the fe.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Review by madhavajay — CHANGES_REQUESTED** [review]
Can we add the `/login` route back to redirect to `/` because we use it on a lot of health checks.

**Comment by madhavajay** [comment]
@tcp great work.
I tested it and got this:
Screenshot 2023-10-18 at 12 11 45 pm

Maybe we can remove the `Text` part?

**Comment by tcp** [comment]
The `Text` part is the domain description. Should we erase it regardless or change the default to be empty?

**Comment by tcp** [comment]
Removed the description, we can handle the defaults in another PR :)

**Review by madhavajay — APPROVED** [review]

**Comment by madhavajay** [comment]
@tcp, tested, works perfectly. 🤌

**Pull request merged**
