### PR TITLE
Draft for socket IO server side and Android worker

### PR DESCRIPTION
**Pull request by mccorby**
This PR contains a new socket server worker using `socket.io`
It includes a demo for such server and a notebook to use it in conjunction with clients, in particular, the Android worker being implemented in https://github.com/OpenMined/AndroidWorker

### CODE REVIEW

**Comment by iamtrask** [comment]
This is awesome! I was just reading socket.io documentation last night. Very good chance we'll re-use this code for other connectors as well.

**Comment by iamtrask** [comment]
Related (but not Androidy): https://github.com/OpenMined/PySyft/pull/2028

**Comment by mccorby** [comment]
I've been taking a look. Very promising. I'll try to find time to adapt it to what we need for Android

**Comment by robert-wagner** [comment]
Hey @mccorby why was this closed?

**Comment by mccorby** [comment]
Ah! I changed the remote branch name. I forgot this was opened

This is the new PR

https://github.com/OpenMined/PySyft/pull/2056

**Pull request closed without merging**
