### PR TITLE
used get_copy

### PR DESCRIPTION
**Pull request by Bhuvan-21**
## Description
Changed .copy().get() into .get(get_copy = True) in all the files, including tutorials.
Issue #4634 

## Affected Dependencies
None

## How has this been tested?
No tests added

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Review by aanurraj — COMMENTED** [review]
looks good, lets wait till all test are passed

**Comment by Bhuvan-21** [comment]
Yeah, I saw the details of the failed test.
It's because I used spaces in get_copy = True which should have been get_copy=True.
I will fix them and make a new PR once the Tutorials test is done.

**Comment by LaRiffle** [comment]
Hey, you should run `black` and `flake8` to fix the lint issues

Here is what the test suite does:
https://github.com/OpenMined/PySyft/blob/master/.github/workflows/tests.yml#L56

**Comment by Bhuvan-21** [comment]
Hey, can any reviewer check the test results and let me know what is wrong now?
I fixed the lint issues using black

**Comment by Nilanshrajput** [comment]
yeah I am taking a look will get back to you @Bhuvan-21

**Comment by Bhuvan-21** [comment]
Yeah, waiting for the feedback.

**Comment by Bhuvan-21** [comment]
Any feedback??

**Comment by Nilanshrajput** [comment]
@gmuraru 
`tensor = self.child.get(*args, **kwargs)
E           TypeError: get() got an unexpected keyword argument 'get_copy'

`
is child here not a pysyft tensor? seems like this get function is different!

**Comment by Bhuvan-21** [comment]
What changes am I supposed to make now, if any?

**Comment by gmuraru** [comment]
One of the errors is this:
```
File "/home/runner/work/PySyft/PySyft/syft/workers/message_handler.py", line 212, in handle_force_delete_object_msg
    for object_id in msg.object_ids:
TypeError: 'int' object is not iterable
```

You should check why the ```msg.object_ids``` becomes and integer, it should be a list or set probably

**Comment by gmuraru** [comment]
> @gmuraru
> 
> ```
> self = (Wrapper)>AutogradTensor>[PointerTensor | me:61309067411 -> alice:45981611550]
> inplace = False, user = None, reason = '', args = ()
> kwargs = {'get_copy': True}
> 
>     def get(self, *args, inplace: bool = False, user=None, reason: str = "", **kwargs):
>         """Requests the tensor/chain being pointed to, be serialized and return
>         Args:
>             args: args to forward to worker
>             inplace: if true, return the same object instance, else a new wrapper
>             kwargs: kwargs to forward to worker
>         Raises:
>             GetNotPermittedError: Raised if get is not permitted on this tensor
>         """
>     
>         # If it is a local tensor/chain, we don't need to verify permissions
>         if not isinstance(self.child, syft.PointerTensor):
> >           tensor = self.child.get(*args, **kwargs)
> E           TypeError: get() got an unexpected keyword argument 'get_copy'
> ```
> 
> `tensor = self.child.get(*args, **kwargs)
> E TypeError: get() got an unexpected keyword argument 'get_copy'
> 
> `
> is child here not a pysyft tensor? seems like this get function is different!

You should add an ```import pdb; pdb.set_trace()``` and check what that tensor is.
What I think is happening is that we did not update all the "get" methods

**Comment by gmuraru** [comment]
Hey @Bhuvan-21 .

Are you still working on this?

**Comment by Bhuvan-21** [comment]
Yeah, I haven't been able to work on it, I got really busy.
I will sure have another go at this.

**Comment by gmuraru** [comment]
Did you had any time @Bhuvan-21

**Pull request closed without merging**
