### PR TITLE
Making changes to avoid errors on avgpool layer

### PR DESCRIPTION
**Pull request by marcusvlc**
The error arises when a network with AvgPooling layer is used. I realized that the command created for this layer used the path _C_nn and not nn.functional as well as other similar layers, such as MaxPooling.

The problem was reported in this issue:

https://github.com/OpenMined/PySyft/issues/2562

My initial solution was to switch all commands that are using the _C_nn path to nn.functional.

### CODE REVIEW

**Comment by marcusvlc** [comment]
@robert-wagner I created a solution using try catch to avoid changing the string with each iteration. If it is not good, could you suggest another approach?

**Comment by iamtrask** [comment]
Hey @marcusvlc - would absolutely love to merge this. Any chance you can add a test per @robert-wagner 's request?

**Comment by marcusvlc** [comment]
@iamtrask Done! 

I had to put some extra checks as the command variable was being used with the wrong path (_C._nn) in several calls. I also added a test that performs a foward on a network with several different layers, including AvgPooling.

While I was designing the tests, I noticed that a pointtensor's .size () function is returning unexpected values, is this normal? I am saying this because most pre-imported models from the torchvision library use this function to access the positions of a tensor.

**Comment by iamtrask** [comment]
thank you for this PR - it's a really strong contribution which lots of folks will use!

**Pull request merged**
