### PR TITLE
Adding Hagrid Launch Command for Worker Container

### PR DESCRIPTION
**Pull request by rasswanth-s**
## How has this been tested?
Added CI tests

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by rasswanth-s** [comment]
Health Checks added for the Worker Container
Screenshot 2023-03-10 at 6 34 26 PM

**Comment by rasswanth-s** [comment]
Includes a convienient land for killing launching docker containers
Screenshot 2023-03-10 at 6 35 20 PM

**Comment by rasswanth-s** [comment]
Contains reset command on python API for deleting existing volumes
Screenshot 2023-03-10 at 6 36 30 PM

**Comment by rasswanth-s** [comment]
Hagrid land command for worker container
Screenshot 2023-03-11 at 5 25 11 PM

**Review by madhavajay — APPROVED** [review]
This is an excellent PR with so much great forward thinking! Great work. ❤️

**Pull request merged**
