### PR TITLE
Tox task for starting high low together

### PR DESCRIPTION
**Pull request by shubham3121**
## Description

We can start both high and low side using the following:

```bash
tox -e dev.k8s.launch.datasite.highlow
```
image

More verbose:

```bash
CLUSTER_NAME_LOW=test-dasite-low-1 CLUSTER_NAME_HIGH=test-datasite-high-1 \ 
CLUSTER_HTTP_PORT_HIGH=9081 CLUSTER_HTTP_PORT_LOW=9083 \
tox -e dev.k8s.launch.datasite.highlow
```

Or just starting a low side:
```bash tox -e dev.k8s.launch.datasite.low```

There is a script to get credentials:
```bash
CLUSTER_NAME="test-datasite-1" ./scripts/get_k8s_secret_ci.sh
```

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@shubham3121 great start, looks like theres still a typo here `CLUSTER_NAME_LOW = {env:CLUSTER_NAME_LOW:test-dasite-low-1}` also when I run it I only get a low side.

Can we make it so that it actually runs the get credentials commands for you and then echos out the entire string like:


```
# copy and paste to jupyter
import syft as sy

high = sy.orchestra.launch(...)
high_client = high.login(...)
# or just the sy.login if thats easier

```

**Comment by shubham3121** [comment]
> @shubham3121 great start, looks like theres still a typo here `CLUSTER_NAME_LOW = {env:CLUSTER_NAME_LOW:test-dasite-low-1}` also when I run it I only get a low side.
> 
> Can we make it so that it actually runs the get credentials commands for you and then echos out the entire string like:
> 
> ```
> # copy and paste to jupyter
> import syft as sy
> 
> high = sy.orchestra.launch(...)
> high_client = high.login(...)
> # or just the sy.login if thats easier
> ```

@madhavajay yes we can do that, just that we need to wait for backend to be up before fetching the credentials.

**Comment by khoaguin** [comment]
@shubham3121 @madhavajay  I was trying to do this and waiting for the backend service to print out the credentials will make the tox task runs for 345s instead of 30s

**Comment by madhavajay** [comment]
@shubham3121 and @khoaguin why don't we just generate the email and password in the script then pass them through to the deployment so we don't need to wait to re-fetch them.

**Comment by khoaguin** [comment]
@madhavajay you mean that since the default root email and password are always "info@openmined.org" and "changethis" if we launch the datasites this way, we just set them as those in the `display_credentials.sh` and not calling the `get_k8s_secret_ci.sh` script?

**Comment by khoaguin** [comment]
@snwagh we can close this as the work is already done in [this merged PR](https://github.com/OpenMined/PySyft/pull/9281), right?

**Comment by snwagh** [comment]
@khoaguin Thanks for checking this, I verified this can be closed and closing it now.

**Pull request closed without merging**
