### PR TITLE
smartopen any cloud storage

### PR DESCRIPTION
**Pull request by yashgorana**
## Description

Part of https://github.com/OpenMined/Heartbeat/issues/1149

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by yashgorana** [comment]
Demo code

**Comment by kiendang** [comment]
Had a discussion with @tcp the other day around blob storage abstractions (client, connection, config). I do see now that the `BlobStorageConnection` interface does not really work here, at least not yet. The original intention behind `BlobStorageConnection` is that you can do 

```py
with blob_client.connect() as conn:
    conn.write(...)

with blob_client.connect() as conn:
    conn.read(...)
```

where `blob_client.connect()` returns a `BlobStorageConnection` via `BlobStorageConnection.__init__()`

I see that here we can't really do that yet since you need to pass different parameters to the connection to Smart Open depending on whether you write or read.

We could change the abstraction a bit to allow `client.connect()` and `BlobStorageConnection.__init__()` to accept extra parameters but that would leak abstraction. We probably needs a rework/rethinking around this.

**Comment by kiendang** [comment]
@yashgorana while working on integration with different blob storage services, if you think of any tweaks to these abstractions that better fit our use cases please push them.

**Comment by yashgorana** [comment]
@kiendang this is a spike PR to see if we can use smartopen, but as you rightly pointed out it just doesn't fit in well. Additionally, smartopen doesn't support deleting files which renders it partially useful. Meanwhile, @tcp has been working on using fsspec which feels much more complete and in-line with our use-case. There still remains some gaps, specifically how to upload blob from client to bucket (through backend) without seaweed's `/blob` API. As we solve it we may actually end up doing some much needed rework/refactoring of our blob store APIs. 

Regardless, thank you for your insights!

**Pull request closed without merging**
