### PR TITLE
removed test share since it was breaking on macos

### PR DESCRIPTION
**Pull request by robert-wagner**

### CODE REVIEW

**Comment by LaRiffle** [comment]
Coverage error

**Comment by robert-wagner** [comment]
@LaRiffle It actually was breaking for me. Had a long talk with @mortendahl and @jvmancuso about it yesterday evening and this seemed to be the most reasonable fix for now

**Comment by LaRiffle** [comment]
> @LaRiffle It actually was breaking for me. Had a long talk with @mortendahl and @jvmancuso about it yesterday evening and this seemed to be the most reasonable fix for now

Maybe we should file an Issue about it to address this, it's an important limitation

**Comment by robert-wagner** [comment]
> > @LaRiffle It actually was breaking for me. Had a long talk with @mortendahl and @jvmancuso about it yesterday evening and this seemed to be the most reasonable fix for now
> 
> Maybe we should file an Issue about it to address this, it's an important limitation

done #2208

**Pull request merged**
