### PR TITLE
Translation to Korean of the tutorial Part 01(#2794)

### PR DESCRIPTION
**Pull request by wonderit**
feat: Translation to Korean of Part 01 - The Basic Tools of 
private deep learning.

This comes as a response to the initiative to translate all the
PySyft tutorials, as it is desirable to learn PySyft in our native
language.

As requested, every part of the tutorial is done via pull request
separately to:

- Track better the changes in every document.

- Avoid double work.

Resolves: #2794
See also: #2782

### CODE REVIEW

**Comment by seungjaeryanlee** [comment]
Hi @wonderit ! I am also thinking of translating notebooks to Korean. Which notebook are you working on? I want to make there is no duplicate work.

**Comment by wonderit** [comment]
Hi @seungjaeryanlee ! I am working on the Part 02. I will leave comment on the issue #2794 if I start another one. Let’s leave comments there.

**Comment by fdroessler** [comment]
Hi, I have been working on the test suit for all notebooks. I have just updated it but the PR is not merged yet. However, I have now moved all the translations into a subfolder so maybe you could do the same?

As in move the `korean` folder into a subfolder of tutorials:
`examples/tutorials/translations/korean/`

That way once both of our PRs are merged, yours should be automatically included in the test suit.

**Comment by wonderit** [comment]
Sound good! I moved the folder to the path you mentioned.

**Pull request merged**
