### PR TITLE
Refactor tests/syft/grid/messages

### PR DESCRIPTION
**Pull request by teo-milea**
## Description
Refactoring tests/syft/grid/messages to make them easier to maintain

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by tudorcebere** [comment]
This is close to ready! :fire: :fire: 

Please run `pre-commit run --all-files` and address the changes requested there. This is looking pretty solid.

**Comment by teo-milea** [comment]
This should be ready, I was not sure what should be the type of a message so I just added sy.Serializable as sy.serialize is the only function used in the auxiliary function for the message integrity check.

**Review by tudorcebere — APPROVED** [review]

**Comment by tudorcebere** [comment]
Really nice work, congrats! :rocket:

**Comment by teo-milea** [comment]
Thanks a lot! :hugs:

**Pull request merged**
