### PR TITLE
Moving PyGrid module to PySyft

### PR DESCRIPTION
**Pull request by IonesioJunior**
# Description
Moving PyGrid library features to PySyft library.

## Features:
- [x] Move grid.WebsocketGridClient -> syft.workers.NodeClient
    - [x] Connect with Grid Nodes.
    - [x] Connect nodes between each other (allow SMPC operations).
    - [x] Search Dataset Tensors.
    - [x] Syft commands.
    - [x] Host Models (Create, Run inferences, Update, Delete)
    - [x] Authentication
- [x] Grid Module
     - [X] Abstract Grid Network
     - [X] Public Grid Network **(It uses grid gateway API to perform queries)**
         - [x] Search datasets by tags through all nodes.
         - [x] Host models inner grid network.
         - [x] Search models hosted on the grid network.
         - [x] Run Inferences using hosted/distributed models.
         - [x] Host encrypted models inner grid network.
         - [x] Run encrypted inferences.
     - [X] Private Grid Network **(Directly connected, It doesn't use grid gateway to perform queries)**
         - [x] Search datasets by tags through all nodes.
         - [x] Host models inner grid network.
         - [x] Search models hosted on the grid network.
         - [x] Run Inferences using hosted/distributed models.
         - [x] Host encrypted models inner grid network.
         - [x] Run encrypted inferences.
- [x] Add Grid codes.
- [x] Add Notebooks

### CODE REVIEW

**Comment by iamtrask** [comment]
So close!!!

**Comment by IonesioJunior** [comment]
Notebooks:
 - [Intro to Grid Platform](https://github.com/IonesioJunior/PySyft/blob/add_grid_workers/examples/tutorials/grid/Part%2001%20-%20Intro%20to%20Grid%20Platform.ipynb)
 - [Grid as s Secure MLaaS](https://github.com/IonesioJunior/PySyft/blob/add_grid_workers/examples/tutorials/grid/Part%2002%20-%20Grid%20as%20a%20Secure%20MLaaS%20to%20Cloud%20Providers.ipynb)
 - [Grid applied to smart cities and smart homes](https://github.com/IonesioJunior/PySyft/blob/add_grid_workers/examples/tutorials/grid/Part%2003%20-%20Grid%20applied%20to%20Smart%20Cities%20and%20Smart%20Homes.ipynb)
 - Federated Learning
    - [MNIST](https://github.com/IonesioJunior/PySyft/tree/add_grid_workers/examples/tutorials/grid/federated_learning/mnist)
    - [SPAM Prediction](https://github.com/IonesioJunior/PySyft/tree/add_grid_workers/examples/tutorials/grid/federated_learning/spam_prediction)

**Comment by karlhigley** [comment]
@IonesioJunior Re-ran the CI tests, which passed following fixes merged into master. Unless merging master again breaks the tests for some reason, it looks like the checklist on this PR will be complete.

**Comment by IonesioJunior** [comment]
Hello @karlhigley! I just restart the CI tests and it works well! Maybe some CI timeout flag was triggered for the first time that it ran.

**Comment by IonesioJunior** [comment]
About the checklist, Yeah! It's complete. I was wondering to perform CI tests about grid nodes on this repository, but I feel It would be a bad idea ( We would probably need to download, install and run PyGrid's stuff on this CI environment which will turn our CI complex and slower). So, I think it'll be better if we did it at PyGrid's repository (Actually we already do it that way).

**Comment by karlhigley** [comment]
@IonesioJunior The tests were broken on master for a while. The failures had nothing to do with this PR. 😅

**Comment by karlhigley** [comment]
Confused why CI tests just started failing again, but pretty sure it's not an issue with the content of this PR.

**Comment by karlhigley** [comment]
Ah, the translation that just got merged was based on a version of the notebook from before the changes in this PR.

**Pull request merged**
