### PR TITLE
Reduce duplication in serde test logic #1740

### PR DESCRIPTION
**Pull request by amit-rastogi**
Updated the following test cases to reduce redundancy-

Merged the following test cases into a single test case - test_compress_decompress
test_compress_decompress_lz4
test_compress_decompress_zstd

Merged the following test cases into a single test case - test_compressed_serde
test_compressed_serde_lz4
test_compressed_serde_zstd

Ran black on test folder
Ran unit tests

### CODE REVIEW

**Comment by robert-wagner** [comment]
Thank you for this pr but I fundamentally disagree with this change. Tests are supposed to help identify where problems come into existence in the code. By combining these two types of tests we make it harder to identify if the problem is in the general compress method or just in one of the compression schemes. This increased difficulty in identifying where the problem is increases the cognitive burden of debugging later on

**Comment by Nivek92** [comment]
I see your point but I would argue code duplication is bad in tests also. One would then have to first need a test if the method works and second a test to test all compress methods

**Comment by iamtrask** [comment]
Seems like best of both worlds here is to have a general "setup" and "teardown" method which is called in separate unit tests for each compression type.

**Comment by Ogofo** [comment]
@robert-wagner I suggest using something like https://github.com/OpenMined/PySyft/pull/1752/commits/1499769da312aa449722d3d90d046ad9a5206102 where I set parameters and just for-looped through them. I'm not sure if this is the most elegant way, but once a test fails the argument values are clearly displayed so you see where the problem is.

**Comment by Nivek92** [comment]
After thinking about it, I actually have a suggestion that would combine both. 

Why not just do something like

def createTest(name):
    def func(*args):
        ....
    func.__name__ = name
    return func

for arg in [arg1, arg2]:
  createTest(f"test_func_{arg1}")

that way you have different tests for each argument but in seperate test. 

No code duplication, Seperate Tests = best of both worlds

**Comment by robert-wagner** [comment]
There is also parameterize in pytest which may be the best of both worlds. Ie we have test compression but we run it with multiple sets of parameters for the compression

```@pytest.mark.parametrize("method", ["","zstd")
def test_compress(method)
```

**Comment by Ogofo** [comment]
Because of the approval of #1762, I think this is obsolete. Thank you @amit-rastogi for the PR :) 

If this one should stay open message me.

**Pull request closed without merging**
