### PR TITLE
Add Bengali Translated Notebooks #Part 10

### PR DESCRIPTION
**Pull request by adventuroussrv**
Translated Notebook:

Part 10 - Federated Learning with Secure Aggregation.ipynb

### CODE REVIEW

**Comment by karlhigley** [comment]
@ucalyptus Could you review this one? Happy to merge once someone who knows Bengali gives it a look.

**Comment by adventuroussrv** [comment]
Hi @karlhigley the tests build failed again!!

**Comment by adventuroussrv** [comment]
https://github.com/OpenMined/PySyft/pull/3049#issuecomment-588571418

@ucalyptus 🙌

**Comment by karlhigley** [comment]
@adventuroussrv It looks like the version of Part 10 in this PR has conflicts with the one from the other PR I just merged. Could you resolve the conflicts? I would do it myself, but I have no idea which version of the text is preferable. 😅

**Comment by adventuroussrv** [comment]
I pushed both the translated notebooks! Part 9 and Part 10 in #3050 :sweat_smile: :grin: 

good close this PR! @karlhigley  :)

**Pull request closed without merging**
