### PR TITLE
added a new comment

### PR DESCRIPTION
**Pull request by abdullah-byte**
I added a new comment to make the code easier for people to understand

### CODE REVIEW

**Comment by gmuraru** [comment]
Hmm...there is only a commented line with an ```import```

**Review by gmuraru — CHANGES_REQUESTED** [review]
Hmm...there is only a commented line with an ```import```

**Comment by abdullah-byte** [comment]
Yes I just wanted to make it easier to understand for any other person who
wants to go through it

**Comment by TTitcombe** [comment]
Are you taking part in Hacktoberfest, by any chance? I see that this is your first PR - I recommend checking out OpenMined's contributing guide https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md for information on how to make the best impact on our projects.

This PR doesn't add anything as the comment is just a duplication of the code. Generally, although documentation changes are vital to ensure a project remains useful, PRs with small changes to documentation / comments don't add much but do take up quite a bit of the maintainers' time. Wanting to contribute to Open Source is great, and I encourage you to continue doing so, but PRs like this aren't helpful.

**Comment by LaRiffle** [comment]
You can check in the "files" tab the changes that your PR provide, it might not be what you expected (ie a simple line change)!

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.

**Pull request closed without merging**
