### PR TITLE
Add verbose workers

### PR DESCRIPTION
**Pull request by robert-wagner**
Should this go to dev or master? Doesn't break anything

### CODE REVIEW

**Comment by iamtrask** [comment]
Just as a matter of practice -  let's do dev

**Comment by iamtrask** [comment]
seems customary to only update master when we actually change version numbers (which we can totally do regularly... but we want to be intentional about it)

**Comment by iamtrask** [comment]
this will allow people to know that if they keep using the same version of the software nothing changes

**Comment by robert-wagner** [comment]
Sounds good

**Pull request merged**
