### PR TITLE
update compatibility with pygrid

### PR DESCRIPTION
**Pull request by vkkhare**
## Description
Add request id in the model centric notebooks

## Affected Dependencies
model centric fl worker
## How has this been tested?
- unit tests
- running the notebooks

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Review by mccorby — APPROVED** [review]
lgtm.
Any chance of adding a test?

**Review by vvmnnnkv — COMMENTED** [review]
Hmm, since this client is sync and doesn't make use of request_id, maybe we can leave it as is and make req_id optional?

**Comment by vkkhare** [comment]
@mccorby there are integration tests in pygrid already and here the changes were done only in the notebook for compatibility

**Comment by vkkhare** [comment]
Okay I will do the necessary changes in PyGrid @vvmnnnkv

**Comment by vkkhare** [comment]
Closing this PR while making req_id optional

**Pull request closed without merging**
